Repository kubermatic/dashboard, pull requests merged in 2020-08, with the labels that each got.

#2527 Rename prow jobs
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2539 Update e2e docker image
  .prow.yaml
  containers/cypress/Dockerfile
  containers/cypress/build-and-release.sh
  containers/cypress/start.sh
  containers/cypress/utils/deploy.sh
  containers/cypress/utils/expose.sh
  containers/cypress/utils/patch/oauth_configmap.yaml
  containers/cypress/utils/patch/oauth_values.yaml
  containers/cypress/utils/yamls/datacenters.yaml
  containers/cypress/utils/yamls/presets.yaml
  containers/cypress/utils/yamls/user.yaml
  containers/e2e/Dockerfile
  containers/e2e/build-and-release.sh
  containers/e2e/start.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#2541 Choose smallest/cheapest instance as the default one
  src/app/node-data/basic/provider/alibaba/component.ts
  src/app/node-data/basic/provider/alibaba/template.html
  src/app/node-data/basic/provider/aws/component.ts
  src/app/node-data/basic/provider/aws/template.html
  src/app/node-data/basic/provider/azure/component.ts
  src/app/node-data/basic/provider/azure/template.html
  src/app/node-data/basic/provider/gcp/component.ts
  src/app/node-data/basic/provider/gcp/template.html
  src/app/node-data/basic/provider/packet/component.ts
  src/app/node-data/basic/provider/packet/template.html
  src/app/node-data/service/provider/alibaba.ts
  src/app/node-data/service/provider/aws.ts
  src/app/node-data/service/provider/azure.ts
  src/app/node-data/service/provider/digitalocean.ts
  src/app/node-data/service/provider/gcp.ts
  src/app/node-data/service/provider/hetzner.ts
  src/app/node-data/service/provider/openstack.ts
  src/app/node-data/service/provider/packet.ts
  src/app/shared/utils/common-utils.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2490 Improve sorting method
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/add-cluster-sshkeys.component.ts
  src/app/cluster/cluster-details/rbac/add-binding/add-binding.component.spec.ts
  src/app/cluster/cluster-details/rbac/add-binding/add-binding.component.ts
  src/app/core/components/navigation/project/selector.component.ts
  src/app/core/services/datacenter/datacenter.service.ts
  src/app/node-data/basic/provider/alibaba/component.ts
  src/app/node-data/basic/provider/aws/component.ts
  src/app/node-data/basic/provider/azure/component.ts
  src/app/node-data/basic/provider/gcp/component.ts
  src/app/project/project.component.ts
  src/app/settings/admin/admins/admins.component.ts
  src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.ts
  src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
  src/app/wizard/step/provider-settings/provider/extended/gcp/component.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
  src/app/wizard/step/provider-settings/ssh-keys/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2548 Fix pagination on projects view when switching layout
  src/app/core/services/project/project.service.ts
  src/app/project/project.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2551 Fix add/edit mode text
  src/app/node-data/dialog/component.ts
  src/app/node-data/extended/provider/aws/component.ts
  src/app/node-data/extended/provider/azure/component.ts
  src/app/node-data/extended/provider/vsphere/component.ts
  src/app/node-data/service/service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2550 Exclude enterprise edition files from community edition builds
  angular.json
  package.json
  src/tsconfig.ce.json
  src/tsconfig.ee.json
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#2565 Skip ND test case
  cypress/integration/stories/machine-deployments.spec.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2558 Move show all projects to the project list view
  src/app/project/project.component.html
  src/app/project/project.component.scss
  src/app/project/project.component.ts
  src/app/settings/user/user-settings.component.html
  src/assets/css/_theme.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2574 Remove list of orphaned nodes from cluster view
  src/app/cluster/cluster-details/cluster-details.component.html
  src/app/cluster/cluster-details/cluster-details.component.spec.ts
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/core/services/cluster/cluster.service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2575 Update owners file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
