Repository kubermatic/dashboard, pull requests merged in 2020-09, with the labels that each got.

#2607 Remove token param from kubeconfig query
  src/app/core/services/api/api.service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2616 Update company name
  src/app/cluster/cluster-details/share-kubeconfig/share-kubeconfig.component.html
  src/app/dynamic/enterprise/LICENSE
  src/app/pages/terms-of-service/terms-of-service.component.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2617 Add option to restrict project creation to admins
  src/app/project/project.component.html
  src/app/project/project.component.ts
  src/app/settings/admin/admin-settings.component.html
  src/app/shared/entity/settings.ts
  src/app/testing/services/settings-mock.service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#2622 Fix custom links and missing info icon
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.html
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.html
  src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.html
  src/app/cluster/cluster-details/node-list/node-list.component.html
  src/app/node-data/basic/provider/openstack/template.html
  src/app/settings/admin/admin-settings.component.html
  src/app/settings/admin/custom-link-form/custom-links-form.component.ts
  src/app/settings/user/user-settings.component.html
  src/app/wizard/step/cluster/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2624 Fix swagger and build warning
  angular.json
  package-lock.json
  package.json
  src/app/pages/api-docs/api-docs.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2626 Multiple UI/UX improvements
  src/app/cluster/cluster-details/cluster-delete-confirmation/cluster-delete-confirmation.component.scss
  src/app/cluster/cluster-details/revoke-token/revoke-token.component.html
  src/app/cluster/cluster-details/version-picker/style.scss
  src/app/core/components/footer/style.scss
  src/app/core/components/navigation/project/component.ts
  src/app/core/components/sidenav/theme.scss
  src/app/node-data/template.html
  src/app/pages/api-docs/theme.scss
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.html
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.scss
  src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.html
  src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.scss
  src/app/shared/components/combobox/style.scss
  src/app/shared/components/combobox/template.html
  src/app/shared/components/property-usage/theme.scss
  src/app/shared/components/tag-list/style.scss
  src/app/theme.scss
  src/app/wizard/step/provider-settings/preset/style.scss
  src/app/wizard/step/provider-settings/preset/template.html
  src/assets/css/global/_main.scss
  src/assets/css/global/_theme.scss
  src/assets/css/material/_main.scss
  src/assets/css/material/_theme.scss
  src/assets/css/theme/_component.scss
  src/assets/themes/light.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2630 Remove non-existing default project selections
  src/app/settings/user/user-settings.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#2632 [release/v2.15] Fix e2e
  hack/e2e/ci-setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2629 [release/v2.15] Multiple UI/UX improvements
  src/app/cluster/cluster-details/cluster-delete-confirmation/cluster-delete-confirmation.component.scss
  src/app/cluster/cluster-details/revoke-token/revoke-token.component.html
  src/app/cluster/cluster-details/version-picker/style.scss
  src/app/core/components/footer/style.scss
  src/app/core/components/navigation/project/component.ts
  src/app/core/components/sidenav/theme.scss
  src/app/node-data/template.html
  src/app/pages/api-docs/theme.scss
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.html
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.scss
  src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.html
  src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.scss
  src/app/shared/components/combobox/style.scss
  src/app/shared/components/combobox/template.html
  src/app/shared/components/property-usage/theme.scss
  src/app/shared/components/tag-list/style.scss
  src/app/theme.scss
  src/app/wizard/step/provider-settings/preset/style.scss
  src/app/wizard/step/provider-settings/preset/template.html
  src/assets/css/global/_main.scss
  src/assets/css/global/_theme.scss
  src/assets/css/material/_main.scss
  src/assets/css/material/_theme.scss
  src/assets/css/theme/_component.scss
  src/assets/themes/light.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2637 Update external cluster naming
  src/app/cluster/cluster-list/cluster-list.component.html
  src/app/cluster/cluster-list/cluster-list.component.ts
  src/app/cluster/external-cluster-details/component.ts
  src/app/cluster/external-cluster-details/template.html
  src/app/core/services/cluster/cluster.service.ts
  src/app/shared/components/external-cluster-data-dialog/component.ts
  src/assets/css/_images.scss
  src/assets/images/icons/disconnect.svg
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2638 Fix project selector jumping to selected value on refresh
  src/app/core/components/navigation/project/component.ts
  src/app/core/components/navigation/project/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2640 Fix text overlapping clear button in our custom combobox
  src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.html
  src/app/shared/components/combobox/template.html
  src/app/wizard/step/provider-settings/preset/template.html
  src/assets/css/global/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2643 Fix selection panel positioning
  src/app/cluster/cluster-details/version-picker/template.html
  src/app/shared/components/combobox/template.html
  src/app/wizard/step/provider-settings/preset/template.html
  src/assets/css/material/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2641 Switch to new cluster endpoints without seed param
  src/app/cluster/cluster-details/add-machine-network/add-machine-network.component.spec.ts
  src/app/cluster/cluster-details/add-machine-network/add-machine-network.component.ts
  src/app/cluster/cluster-details/change-cluster-version/change-cluster-version.component.ts
  src/app/cluster/cluster-details/cluster-delete-confirmation/cluster-delete-confirmation.component.ts
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.ts
  src/app/cluster/cluster-details/machine-networks-display/machine-networks-display.component.ts
  src/app/cluster/cluster-list/cluster-list.component.ts
  src/app/core/services/cluster/cluster.service.ts
  src/app/core/services/page-title/page-title.service.ts
  src/app/core/services/params/params.service.ts
  src/app/wizard/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2618 Add flag continuouslyReconcile to addons
  src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.html
  src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.ts
  src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.html
  src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.ts
  src/app/shared/entity/addon.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2644 Add option to enable/disable external cluster import from admin settings
  src/app/cluster/cluster-list/cluster-list.component.html
  src/app/cluster/cluster-list/cluster-list.component.spec.ts
  src/app/cluster/cluster-list/cluster-list.component.ts
  src/app/core/interceptors/error-notifications/error-notifications.service.ts
  src/app/core/services/cluster/cluster.service.ts
  src/app/project/project.component.spec.ts
  src/app/project/project.module.ts
  src/app/settings/admin/admin-settings.component.html
  src/app/shared/entity/settings.ts
  src/app/testing/services/settings-mock.service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2645 Fix call order in the SSH key view
  src/app/sshkey/sshkey.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#2655 Fix admission plugin selection in wizard
  src/app/shared/services/cluster.service.ts
  src/app/wizard/step/cluster/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2661 Fix wizard rendering in Safari
  src/app/wizard/step/cluster/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2668 Improve browsers support
  package-lock.json
  package.json
  src/assets/css/global/_main.scss
  src/assets/css/material/_main.scss
  src/assets/css/root.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2671 Change flag icons default ratio to 4x3
  src/assets/css/root.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2672 Fix styling issues
  src/app/shared/components/event-list/event-list.component.scss
  src/app/sshkey/sshkey.component.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2674 Mark addons in deletion
  src/app/shared/components/addon-list/addon-list.component.html
  src/app/shared/components/addon-list/addon-list.component.scss
  src/app/shared/components/addon-list/addon-list.component.ts
  src/app/shared/components/dialog-title/dialog-title.component.html
  src/assets/css/global/_main.scss
  src/assets/themes/dark.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#2669 Update project configuration
  .prow.yaml
  angular.json
  containers/custom-dashboard/Dockerfile
  containers/cypress/Dockerfile
  containers/cypress/build-and-release.sh
  containers/go-node/Dockerfile
  containers/go-node/build-and-release.sh
  containers/localdev/Dockerfile
  containers/test-chrome/Dockerfile
  containers/test-chrome/release.sh
  cypress/tsconfig.e2e.json
  package-lock.json
  package.json
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts
  src/app/shared/validators/autocomplete-filter.validator.ts
  src/app/wizard/step/network/component.ts
  tsconfig.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#2675 Fix settings UI
  src/app/dynamic/enterprise/theming/picker/style.scss
  src/app/settings/admin/admin-settings.component.html
  src/app/settings/admin/admin-settings.component.scss
  src/app/settings/user/user-settings.component.html
  src/app/settings/user/user-settings.component.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
