Repository kubermatic/dashboard, pull requests merged in 2020-07, with the labels that each got.

#2402 Add Availability Zones for Openstack
  src/app/cluster/cluster-details/node-list/node-list.component.html
  src/app/core/services/api/api.service.ts
  src/app/core/services/wizard/provider/openstack.ts
  src/app/node-data-new/basic/provider/openstack/component.ts
  src/app/node-data-new/basic/provider/openstack/template.html
  src/app/node-data-new/service/provider/openstack.ts
  src/app/node-data/node-data.component.spec.ts
  src/app/node-data/openstack-node-data/openstack-node-data.component.html
  src/app/node-data/openstack-node-data/openstack-node-data.component.spec.ts
  src/app/node-data/openstack-node-data/openstack-node-data.component.ts
  src/app/shared/entity/node.ts
  src/app/shared/entity/provider/openstack.ts
  src/app/testing/fake-data/addNodeModal.fake.ts
  src/app/wizard-new/step/summary/template.html
  src/app/wizard/summary/summary.component.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2439 Fix provider names display
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.ts
  src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.ts
  src/app/shared/model/NodeProviderConstants.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2434 [release/2.14] Enable flatcar for openstack
  src/app/node-data-new/component.ts
  src/app/node-data/node-data.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2443 Fix notification display in the panel
  src/app/core/components/notification-panel/notification-panel.component.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2441 Monitor theme changes globally and fix system theme option
  src/app/dynamic/enterprise/theming/picker/component.ts
  src/app/dynamic/enterprise/theming/services/manager.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2445 Fix summary view for admission plugins
  src/app/wizard/summary/summary.component.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2444 Fix default image for openstack for rhel and flatcar
  src/app/node-data-new/basic/provider/openstack/component.ts
  src/app/node-data/openstack-node-data/openstack-node-data.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2416 Rename Node Deployments to Machine Deployments
  cypress/integration/stories/machine-deployments.spec.ts
  cypress/pages/clusters.po.ts
  cypress/pages/machine-deployment-details.po.ts
  src/app/cluster/cluster-details/change-cluster-version/change-cluster-version.component.html
  src/app/cluster/cluster-details/change-cluster-version/change-cluster-version.component.spec.ts
  src/app/cluster/cluster-details/change-cluster-version/change-cluster-version.component.ts
  src/app/cluster/cluster-details/cluster-details.component.html
  src/app/cluster/cluster-details/cluster-details.component.spec.ts
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/cluster-panel.component.html
  src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/cluster-panel.component.ts
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.html
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.scss
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.spec.ts
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.ts
  src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.html
  src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.scss
  src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.spec.ts
  src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.ts
  src/app/cluster/cluster-details/node-data-modal/node-data-modal.component.spec.ts
  src/app/cluster/cluster-details/node-data-modal/node-data-modal.component.ts
  src/app/cluster/cluster-details/version-picker/version-picker.component.spec.ts
  src/app/cluster/cluster-list/cluster-list.component.ts
  src/app/cluster/cluster-routing.module.ts
  src/app/cluster/cluster.module.ts
  src/app/cluster/services/node.service.spec.ts
  src/app/cluster/services/node.service.ts
  src/app/core/services/api/api.service.ts
  src/app/core/services/cluster/cluster.service.ts
  src/app/core/services/page-title/page-title.service.ts
  src/app/core/services/params/params.service.ts
  src/app/node-data/aws-node-data/aws-node-options/aws-node-options.component.ts
  src/app/node-data/node-data.component.html
  src/app/node-data/node-data.component.scss
  src/app/node-data/node-data.component.ts
  src/app/settings/admin/admin-settings.component.html
  src/app/settings/admin/admin-settings.component.scss
  src/app/shared/entity/common.ts
  src/app/shared/entity/machine-deployment.ts
  src/app/shared/model/Config.ts
  src/app/shared/model/CreateClusterModel.ts
  src/app/shared/utils/health-status/machine-deployment-health-status.spec.ts
  src/app/shared/utils/health-status/machine-deployment-health-status.ts
  src/app/testing/fake-data/node.fake.ts
  src/app/testing/fake-data/userGroupConfig.fake.ts
  src/app/testing/services/api-mock.service.ts
  src/app/testing/services/cluster-mock-service.ts
  src/app/testing/services/node-mock.service.ts
  src/assets/config/userGroupConfig.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#2459 Align footer icon color with the text
  src/assets/css/_theme.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2429 Use the new seed endpoint and refactor the datacenters handling
  src/app/cluster/cluster-details/add-machine-network/add-machine-network.component.spec.ts
  src/app/cluster/cluster-details/add-machine-network/add-machine-network.component.ts
  src/app/cluster/cluster-details/change-cluster-version/change-cluster-version.component.spec.ts
  src/app/cluster/cluster-details/change-cluster-version/change-cluster-version.component.ts
  src/app/cluster/cluster-details/cluster-delete-confirmation/cluster-delete-confirmation.component.spec.ts
  src/app/cluster/cluster-details/cluster-delete-confirmation/cluster-delete-confirmation.component.ts
  src/app/cluster/cluster-details/cluster-details.component.html
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.spec.ts
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/add-cluster-sshkeys.component.ts
  src/app/cluster/cluster-details/edit-sshkeys/edit-sshkeys.component.ts
  src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/cluster-panel.component.ts
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.html
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.spec.ts
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.ts
  src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.ts
  src/app/cluster/cluster-details/machine-networks-display/machine-networks-display.component.ts
  src/app/cluster/cluster-details/node-data-modal/node-data-modal.component.html
  src/app/cluster/cluster-details/node-data-modal/node-data-modal.component.spec.ts
  src/app/cluster/cluster-details/node-data-modal/node-data-modal.component.ts
  src/app/cluster/cluster-details/node-list/node-list.component.spec.ts
  src/app/cluster/cluster-details/node-list/node-list.component.ts
  src/app/cluster/cluster-details/rbac/add-binding/add-binding.component.spec.ts
  src/app/cluster/cluster-details/rbac/add-binding/add-binding.component.ts
  src/app/cluster/cluster-details/rbac/rbac.component.spec.ts
  src/app/cluster/cluster-details/rbac/rbac.component.ts
  src/app/cluster/cluster-details/revoke-token/revoke-token.component.ts
  src/app/cluster/cluster-details/share-kubeconfig/share-kubeconfig.component.spec.ts
  src/app/cluster/cluster-details/share-kubeconfig/share-kubeconfig.component.ts
  src/app/cluster/cluster-details/version-picker/version-picker.component.spec.ts
  src/app/cluster/cluster-details/version-picker/version-picker.component.ts
  src/app/cluster/cluster-list/cluster-list.component.ts
  src/app/cluster/services/node.service.ts
  src/app/core/services/api/api.service.ts
  src/app/core/services/cluster/cluster.service.ts
  src/app/core/services/datacenter/datacenter.service.ts
  src/app/core/services/rbac/rbac.service.ts
  src/app/core/services/wizard/provider/aws.ts
  src/app/core/services/wizard/provider/gcp.ts
  src/app/node-data/alibaba-node-data/alibaba-node-data.component.ts
  src/app/node-data/aws-node-data/aws-node-data.component.ts
  src/app/node-data/azure-node-data/azure-node-data.component.ts
  src/app/node-data/digitalocean-node-data/digitalocean-node-data.component.ts
  src/app/node-data/gcp-node-data/gcp-node-data.component.ts
  src/app/node-data/hetzner-node-data/hetzner-node-data.component.ts
  src/app/node-data/node-data.component.html
  src/app/node-data/node-data.component.ts
  src/app/node-data/openstack-node-data/openstack-node-data.component.ts
  src/app/node-data/packet-node-data/packet-node-data.component.ts
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.html
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.ts
  src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.ts
  src/app/testing/fake-data/datacenter.fake.ts
  src/app/testing/services/datacenter-mock.service.ts
  src/app/wizard/set-settings/set-settings.component.html
  src/app/wizard/set-settings/set-settings.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#2463 Add user project limit to the admin panel
  src/app/settings/admin/admin-settings.component.html
  src/app/shared/entity/settings.ts
  src/app/testing/services/settings-mock.service.ts
  tsconfig.json
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#2469 Do not filter seeds from datacenters as API does no longer mix them
  src/app/core/services/datacenter/datacenter.service.ts
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.ts
  src/app/shared/entity/datacenter.ts
  src/app/testing/fake-data/datacenter.fake.ts
  src/app/wizard-new/step/provider-datacenter/component.ts
  src/app/wizard/set-datacenter/set-datacenter.component.ts
  src/app/wizard/set-provider/set-provider.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2480 Fix status and deletion in the cluster list
  src/app/cluster/cluster-list/cluster-list.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2482 Update OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2486 Improve the styling
  src/app/cluster/cluster-details/rbac/rbac.component.html
  src/app/shared/components/event-list/event-list.component.html
  src/assets/css/_theme.scss
  src/assets/themes/dark.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2476 Implement user WebSocket
  cypress/pages/user-settings.po.ts
  src/app/app.module.ts
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/add-cluster-sshkeys.component.ts
  src/app/cluster/cluster-details/edit-sshkeys/edit-sshkeys.component.ts
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.ts
  src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.ts
  src/app/cluster/cluster-details/node-list/node-list.component.ts
  src/app/cluster/cluster-details/revoke-token/revoke-token.component.ts
  src/app/cluster/cluster-details/share-kubeconfig/share-kubeconfig.component.ts
  src/app/cluster/cluster-list/cluster-list.component.ts
  src/app/core/components/navigation/navigation.component.ts
  src/app/core/components/navigation/project/selector.component.ts
  src/app/core/components/sidenav/sidenav.component.ts
  src/app/core/components/user-panel/user-panel.component.ts
  src/app/core/services/auth/auth.guard.ts
  src/app/core/services/project/project.service.ts
  src/app/core/services/settings/settings.service.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/dynamic/enterprise/theming/picker/component.ts
  src/app/dynamic/enterprise/theming/services/manager.ts
  src/app/member/member.component.ts
  src/app/project/project.component.html
  src/app/project/project.component.ts
  src/app/serviceaccount/serviceaccount-token/serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount.component.ts
  src/app/settings/admin/admin-settings.component.ts
  src/app/settings/admin/admins/admins.component.ts
  src/app/settings/admin/dynamic-datacenters/dynamic-datacenters.component.ts
  src/app/settings/user/user-settings.component.ts
  src/app/shared/components/event-list/event-list.component.spec.ts
  src/app/shared/components/event-list/event-list.component.ts
  src/app/shared/entity/member.ts
  src/app/shared/utils/member-utils/member-utils.ts
  src/app/sshkey/sshkey.component.ts
  src/app/testing/fake-data/datacenter.fake.ts
  src/app/testing/services/settings-mock.service.ts
  src/app/testing/services/user-mock.service.ts
  src/app/wizard-new/step/provider-settings/ssh-keys/component.ts
  src/app/wizard/set-settings/ssh-keys/cluster-ssh-keys.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#2483 Add and use gcp subnetworks path
  src/app/shared/entity/provider/gcp.ts
  src/app/wizard/step/provider-settings/provider/extended/gcp/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2495 Fix add/edit ND for AWS
  src/app/node-data/basic/provider/aws/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2501 Improve e2e tests stability
  cypress/integration/stories/basic.spec.ts
  cypress/integration/stories/edition.spec.ts
  cypress/integration/stories/machine-deployments.spec.ts
  cypress/integration/stories/multi-owner.spec.ts
  cypress/integration/stories/service-accounts.spec.ts
  cypress/pages/clusters.po.ts
  cypress/pages/members.po.ts
  cypress/pages/projects.po.ts
  cypress/pages/service-accounts.po.ts
  cypress/pages/user-settings.po.ts
  cypress/pages/wizard.po.ts
  cypress/utils/endpoint.ts
  cypress/utils/monitor.ts
  cypress/utils/view.ts
  hack/e2e/ci-setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2507 [v2.14] Improve e2e tests stability
  cypress/integration/stories/basic.spec.ts
  cypress/integration/stories/edition.spec.ts
  cypress/integration/stories/multi-owner.spec.ts
  cypress/integration/stories/node-deployments.spec.ts
  cypress/integration/stories/service-accounts.spec.ts
  cypress/pages/clusters.po.ts
  cypress/pages/dex.po.ts
  cypress/pages/members.po.ts
  cypress/pages/projects.po.ts
  cypress/pages/service-accounts.po.ts
  cypress/pages/user-settings.po.ts
  cypress/pages/wizard.po.ts
  cypress/tsconfig.e2e.json
  cypress/utils/auth.ts
  cypress/utils/endpoint.ts
  cypress/utils/monitor.ts
  cypress/utils/view.ts
  cypress/utils/wait.ts
  hack/e2e/ci-setup-kubermatic-in-kind.sh
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#2494 [release/2.14] Add and use gcp subnetworks path
  src/app/shared/entity/provider/gcp/GCP.ts
  src/app/wizard-new/step/provider-settings/provider/extended/gcp/template.html
  src/app/wizard/set-settings/provider-settings/gcp/gcp-provider-options/gcp-provider-options.component.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2517 Improve e2e
  cypress/pages/clusters.po.ts
  cypress/pages/projects.po.ts
  cypress/utils/endpoint.ts
  cypress/utils/monitor.ts
  hack/e2e/ci-setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2524 Fix issue with Openstack provider in the wizard
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/component.ts
  src/app/node-data/extended/provider/vsphere/component.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/provider-datacenter/component.ts
  src/app/wizard/step/provider-datacenter/template.html
  src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
  src/app/wizard/step/summary/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
