Repository kubermatic/dashboard, pull requests merged in 2020-12, with the labels that each got.

#2834 Update Go dependencies
  Dockerfile
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2840 Replace first() with take(1)
  package.json
  src/app/cluster/cluster-details/add-machine-network/component.ts
  src/app/cluster/cluster-details/change-cluster-version/component.ts
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/component.ts
  src/app/cluster/cluster-details/machine-deployment-details/component.ts
  src/app/cluster/cluster-details/node-list/component.ts
  src/app/cluster/cluster-details/rbac/component.ts
  src/app/cluster/cluster-details/revoke-token/component.ts
  src/app/cluster/cluster-details/share-kubeconfig/component.ts
  src/app/cluster/cluster-details/version-picker/component.ts
  src/app/cluster/cluster-list/component.ts
  src/app/cluster/services/node.service.ts
  src/app/core/services/auth/service.ts
  src/app/core/services/datacenter/service.ts
  src/app/core/services/project/service.ts
  src/app/core/services/user/service.ts
  src/app/dynamic/enterprise/theming/picker/component.ts
  src/app/member/member.component.ts
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/component.ts
  src/app/node-data/kubelet-version/component.ts
  src/app/node-data/service/provider/alibaba.ts
  src/app/node-data/service/provider/aws.ts
  src/app/node-data/service/provider/azure.ts
  src/app/node-data/service/provider/digitalocean.ts
  src/app/node-data/service/provider/gcp.ts
  src/app/node-data/service/provider/hetzner.ts
  src/app/node-data/service/provider/openstack.ts
  src/app/node-data/service/provider/packet.ts
  src/app/project/project.component.ts
  src/app/serviceaccount/add-serviceaccount/add-serviceaccount.component.ts
  src/app/serviceaccount/edit-serviceaccount/edit-serviceaccount.component.ts
  src/app/serviceaccount/serviceaccount-token/add-serviceaccount-token/add-serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount-token/edit-serviceaccount-token/edit-serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount-token/serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount.component.ts
  src/app/settings/admin/component.ts
  src/app/settings/user/user-settings.component.ts
  src/app/shared/components/addon-list/addon-list.component.ts
  src/app/shared/components/addon-list/select-addon-dialog/select-addon-dialog.component.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/ssh-keys/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
  src/app/wizard/step/summary/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2815 Use the new endpoints
  src/app/cluster/cluster-details/change-cluster-version/component.spec.ts
  src/app/cluster/cluster-details/change-cluster-version/component.ts
  src/app/cluster/cluster-details/cluster-delete-confirmation/component.spec.ts
  src/app/cluster/cluster-details/cluster-delete-confirmation/component.ts
  src/app/cluster/cluster-details/component.spec.ts
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/edit-cluster/component.spec.ts
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/template.html
  src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/component.ts
  src/app/cluster/cluster-details/machine-deployment-details/component.spec.ts
  src/app/cluster/cluster-details/machine-deployment-details/component.ts
  src/app/cluster/cluster-details/machine-deployment-details/template.html
  src/app/cluster/cluster-details/machine-deployment-list/component.ts
  src/app/cluster/cluster-details/machine-networks-display/component.ts
  src/app/cluster/cluster-details/node-list/component.spec.ts
  src/app/cluster/cluster-details/node-list/component.ts
  src/app/cluster/cluster-details/rbac/add-binding/component.spec.ts
  src/app/cluster/cluster-details/rbac/add-binding/component.ts
  src/app/cluster/cluster-details/rbac/component.spec.ts
  src/app/cluster/cluster-details/rbac/component.ts
  src/app/cluster/cluster-details/revoke-token/component.ts
  src/app/cluster/cluster-details/share-kubeconfig/component.spec.ts
  src/app/cluster/cluster-details/template.html
  src/app/cluster/cluster-details/version-picker/component.spec.ts
  src/app/cluster/cluster-details/version-picker/component.ts
  src/app/cluster/cluster-list/component.ts
  src/app/cluster/services/node.service.spec.ts
  src/app/cluster/services/node.service.ts
  src/app/core/interceptors/loader/interceptor.ts
  src/app/core/services/api/service.ts
  src/app/core/services/cluster/service.ts
  src/app/core/services/page-title/service.ts
  src/app/core/services/params/service.ts
  src/app/core/services/rbac/service.ts
  src/app/node-data/service/provider/aws.ts
  src/app/routing.ts
  src/app/settings/admin/dynamic-datacenters/component.ts
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/component.ts
  src/app/settings/user/user-settings.component.ts
  src/app/shared/components/add-ssh-key-dialog/add-ssh-key-modal.component.spec.ts
  src/app/testing/fake-data/datacenter.fake.ts
  src/app/wizard/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2839 Update displayed distributions logic to use admin settings
  src/app/wizard/step/cluster/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2849 Update login page background
  src/assets/images/branding/bg.svg
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#2848 Fix listing all projects
  src/app/project/project.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2851 Fix group display name logic
  src/app/shared/utils/member-utils/member-utils.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2850 Fix add rbac dialog styling
  src/app/cluster/cluster-details/rbac/add-binding/style.scss
  src/app/cluster/cluster-details/rbac/add-binding/template.html
  src/app/cluster/cluster-details/rbac/add-binding/theme.scss
  src/assets/css/theme/_component.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2854 Remove list of internal domains from bug template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2856 Fix dark theme provider logo centering
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/theme.scss
  src/assets/css/_images.scss
  src/assets/css/_mixins.scss
  src/assets/themes/dark.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2867 Fix icon colors
  src/app/wizard/step/cluster/theme.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2855 Use the new endpoints
  src/app/cluster/cluster-details/component.ts
  src/app/core/services/api/service.ts
  src/app/node-data/service/provider/alibaba.ts
  src/app/node-data/service/provider/azure.ts
  src/app/node-data/service/provider/digitalocean.ts
  src/app/node-data/service/provider/gcp.ts
  src/app/node-data/service/provider/hetzner.ts
  src/app/node-data/service/provider/openstack.ts
  src/app/node-data/service/provider/packet.ts
  src/app/node-data/service/service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2883 Remove mat icons
  src/app/cluster/cluster-details/node-list/style.scss
  src/app/cluster/cluster-details/node-list/template.html
  src/app/cluster/cluster-details/template.html
  src/app/cluster/cluster-details/version-picker/template.html
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html
  src/app/settings/admin/dynamic-datacenters/template.html
  src/app/shared/components/addon-list/addon-list.component.html
  src/app/shared/components/combobox/template.html
  src/app/shared/components/search-field/template.html
  src/app/shared/components/tag-list/tag-list.component.html
  src/app/wizard/step/provider-settings/preset/template.html
  src/app/wizard/template.html
  src/assets/css/_images.scss
  src/assets/css/global/_main.scss
  src/assets/images/icons/points-menu.svg
  src/assets/images/icons/remove.svg
  src/index.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2886 UI/UX fixes
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/core/components/notification-panel/style.scss
  src/app/core/components/notification-panel/template.html
  src/app/node-data/dialog/component.ts
  src/app/node-data/dialog/template.html
  src/app/shared/components/event-list/event-list.component.html
  src/app/shared/components/external-cluster-data-dialog/component.ts
  src/app/shared/components/external-cluster-data-dialog/style.scss
  src/app/wizard/template.html
  src/assets/css/global/_theme.scss
  src/assets/css/material/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2889 Fix theme save status indicator
  src/app/dynamic/enterprise/theming/picker/component.ts
  src/app/dynamic/enterprise/theming/picker/style.scss
  src/app/dynamic/enterprise/theming/picker/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2885 Do not allow HTML inside notification messages
  src/app/cluster/cluster-details/add-machine-network/component.ts
  src/app/cluster/cluster-details/change-cluster-version/component.ts
  src/app/cluster/cluster-details/cluster-delete-confirmation/component.ts
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/component.ts
  src/app/cluster/cluster-details/machine-deployment-details/component.ts
  src/app/cluster/cluster-details/machine-deployment-list/component.ts
  src/app/cluster/cluster-details/node-list/component.ts
  src/app/cluster/cluster-details/rbac/add-binding/component.ts
  src/app/cluster/cluster-details/rbac/component.ts
  src/app/cluster/cluster-details/revoke-token/component.ts
  src/app/cluster/cluster-list/component.ts
  src/app/cluster/external-cluster-details/component.ts
  src/app/cluster/services/node.service.ts
  src/app/core/components/notification-panel/template.html
  src/app/core/components/notification/template.html
  src/app/core/services/cluster/service.ts
  src/app/member/add-member/add-member.component.ts
  src/app/member/edit-member/edit-member.component.ts
  src/app/member/member.component.ts
  src/app/project/edit-project/edit-project.component.ts
  src/app/project/project.component.ts
  src/app/serviceaccount/add-serviceaccount/add-serviceaccount.component.ts
  src/app/serviceaccount/edit-serviceaccount/edit-serviceaccount.component.ts
  src/app/serviceaccount/serviceaccount-token/add-serviceaccount-token/add-serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount-token/edit-serviceaccount-token/edit-serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount-token/serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount.component.ts
  src/app/settings/admin/admins/add-admin-dialog/component.ts
  src/app/settings/admin/admins/component.ts
  src/app/settings/admin/dynamic-datacenters/component.ts
  src/app/shared/components/add-project-dialog/add-project-dialog.component.ts
  src/app/shared/components/add-ssh-key-dialog/add-ssh-key-dialog.component.ts
  src/app/shared/components/addon-list/addon-list.component.ts
  src/app/shared/pipes/relativetime.ts
  src/app/sshkey/sshkey.component.ts
  src/app/wizard/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
