Repository kubermatic/dashboard, pull requests merged in 2020-10, with the labels that each got.

#2687 Make vsphere VM template a required parameter
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/basic/provider/vsphere/template.html
  src/app/node-data/extended/provider/vsphere/component.ts
  src/app/node-data/extended/provider/vsphere/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2695 Add cluster search/filter
  src/app/cluster/cluster-list/cluster-list.component.html
  src/app/cluster/cluster-list/cluster-list.component.ts
  src/app/shared/components/search-field/component.ts
  src/app/shared/components/search-field/template.html
  src/app/shared/entity/cluster.ts
  src/app/shared/shared.module.ts
  src/assets/css/_images.scss
  src/assets/css/global/_main.scss
  src/assets/images/icons/search.svg
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2704 UI/UX fixes
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.html
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.scss
  src/app/member/member.component.html
  src/app/member/member.component.ts
  src/app/project/project.component.html
  src/app/project/project.component.scss
  src/app/settings/user/user-settings.component.scss
  src/app/shared/components/add-ssh-key-dialog/add-ssh-key-dialog.component.html
  src/app/shared/components/editor/component.ts
  src/assets/css/_images.scss
  src/assets/css/material/_main.scss
  src/assets/images/clouds/azure.png
  src/assets/images/clouds/azure.svg
  src/assets/images/clouds/digitalocean.png
  src/assets/images/clouds/digitalocean.svg
  src/assets/images/clouds/hetzner.png
  src/assets/images/clouds/hetzner.svg
  src/assets/images/clouds/openstack.png
  src/assets/images/clouds/openstack.svg
  src/assets/images/clouds/vsphere.png
  src/assets/images/clouds/vsphere.svg
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2708 Update dependencies
  package-lock.json
  package.json
  src/polyfills.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#2723 Fix cluster search
  src/app/cluster/cluster-list/cluster-list.component.html
  src/app/cluster/cluster-list/cluster-list.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2718 Improve UI/UX
  src/app/cluster/cluster-details/rbac/rbac.component.scss
  src/app/node-data/template.html
  src/app/shared/components/editor/component.ts
  src/app/shared/components/editor/style.scss
  src/app/shared/components/event-list/event-list.component.scss
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/provider-datacenter/template.html
  src/app/wizard/step/provider-settings/ssh-keys/template.html
  src/assets/css/global/_main.scss
  src/assets/css/global/_theme.scss
  src/assets/css/material/_main.scss
  src/assets/css/material/_theme.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2724 Update Container Linux EOL messages
  src/app/cluster/cluster-details/machine-deployment-details/machine-deployment-details.component.html
  src/app/cluster/cluster-details/machine-deployment-list/machine-deployment-list.component.html
  src/app/cluster/cluster-details/node-list/node-list.component.html
  src/app/cluster/cluster-list/cluster-list.component.html
  src/app/node-data/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2731 Fix addon edit dialog
  src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.html
  src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.ts
  src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.ts
  src/app/shared/entity/addon.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2747 Allow to add ssh keys for kubeadm provider
  src/app/cluster/cluster-details/template.html
  src/app/shared/services/cluster.service.ts
  src/app/wizard/module.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/ssh-keys/component.spec.ts
  src/app/wizard/step/cluster/ssh-keys/component.ts
  src/app/wizard/step/cluster/ssh-keys/style.scss
  src/app/wizard/step/cluster/ssh-keys/template.html
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/provider-settings/component.ts
  src/app/wizard/step/provider-settings/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#2752 [release/v2.15] Allow to add ssh keys for kubeadm provider
  src/app/cluster/cluster-details/cluster-details.component.html
  src/app/shared/services/cluster.service.ts
  src/app/wizard/module.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/ssh-keys/component.spec.ts
  src/app/wizard/step/cluster/ssh-keys/component.ts
  src/app/wizard/step/cluster/ssh-keys/style.scss
  src/app/wizard/step/cluster/ssh-keys/template.html
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/provider-settings/component.ts
  src/app/wizard/step/provider-settings/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
