Repository kubermatic/dashboard, pull requests merged in 2020-06, with the labels that each got.

#2395 [release/v2.14] Update README and add FOSS and KERO License (#2394)
  CONTRIBUTING.md
  DCO
  Development.md
  LICENSE
  NOTICE
  README.md
  Zenhub.md
  code-of-conduct.md
  src/app/ee/LICENSE
  src/app/ee/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#2400 Fix E2E tests
  hack/e2e/ci-setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2403 Remove circular dependency for datacenterService <> index
  src/app/core/services/datacenter/datacenter.service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2399 Move user panel to new component
  src/app/core/components/navigation/navigation.component.html
  src/app/core/components/navigation/navigation.component.scss
  src/app/core/components/navigation/navigation.component.ts
  src/app/core/components/navigation/project/selector.component.spec.ts
  src/app/core/components/notification-panel/notification-panel.component.html
  src/app/core/components/notification-panel/notification-panel.component.scss
  src/app/core/components/user-panel/user-panel.component.html
  src/app/core/components/user-panel/user-panel.component.scss
  src/app/core/components/user-panel/user-panel.component.spec.ts
  src/app/core/components/user-panel/user-panel.component.ts
  src/app/core/core.module.ts
  src/app/shared/shared.module.ts
  src/assets/css/_theme.scss
  src/assets/css/_variables.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2405 Restructure Admission Plugins
  src/app/cluster/cluster-details/cluster-details.component.html
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.html
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.scss
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.spec.ts
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts
  src/app/core/services/api/api.service.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/model/ClusterForm.ts
  src/app/shared/utils/admission-plugin-utils/admission-plugin-utils.ts
  src/app/testing/services/api-mock.service.ts
  src/app/wizard-new/service/cluster.ts
  src/app/wizard-new/step/cluster/component.ts
  src/app/wizard-new/step/cluster/style.scss
  src/app/wizard-new/step/cluster/template.html
  src/app/wizard-new/step/provider-settings/ssh-keys/template.html
  src/app/wizard-new/step/summary/component.ts
  src/app/wizard-new/step/summary/template.html
  src/app/wizard/set-cluster-spec/set-cluster-spec.component.html
  src/app/wizard/set-cluster-spec/set-cluster-spec.component.scss
  src/app/wizard/set-cluster-spec/set-cluster-spec.component.ts
  src/app/wizard/set-datacenter/set-datacenter.component.ts
  src/app/wizard/set-settings/ssh-keys/cluster-ssh-keys.component.html
  src/app/wizard/summary/summary.component.html
  src/app/wizard/summary/summary.component.scss
  src/app/wizard/summary/summary.component.ts
  src/app/wizard/wizard.component.ts
  src/assets/css/_theme.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#2407 Add logout endpoint support
  src/app/app.config.ts
  src/app/core/components/footer/footer.component.html
  src/app/core/components/footer/footer.component.ts
  src/app/core/components/user-panel/user-panel.component.ts
  src/app/core/core.module.ts
  src/app/core/services/auth/auth.service.spec.ts
  src/app/core/services/auth/auth.service.ts
  src/app/core/services/project/project.service.ts
  src/app/core/services/token/token.service.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/pages/frontpage/frontpage.component.html
  src/app/pages/frontpage/frontpage.component.ts
  src/app/project/project.component.ts
  src/app/testing/services/auth-mock.service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2406 Split enterprise and community builds
  .gitignore
  Development.md
  package.json
  src/app/dynamic/common.ts
  src/app/dynamic/community/theming/module.ts
  src/app/dynamic/enterprise/LICENSE
  src/app/dynamic/enterprise/README.md
  src/app/dynamic/enterprise/theming/module.ts
  src/app/dynamic/enterprise/theming/picker/component.ts
  src/app/dynamic/enterprise/theming/picker/style.scss
  src/app/dynamic/enterprise/theming/picker/template.html
  src/app/dynamic/enterprise/theming/services/color-scheme.ts
  src/app/dynamic/enterprise/theming/services/manager.ts
  src/app/dynamic/enterprise/theming/services/theme.ts
  src/app/settings/user/user-settings.routing.module.ts
  src/app/theming/README.md
  src/environments/environment.e2e.local.ts
  src/environments/environment.e2e.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  tsconfig.json
  version.js
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2411 Add complexity check
  package.json
  src/app/node-data/aws-node-data/aws-node-data.component.ts
  src/app/node-data/gcp-node-data/gcp-node-data.component.ts
  src/app/node-data/node-data.component.ts
  src/app/node-data/vsphere-add-node/vsphere-node-options/vsphere-node-options.component.ts
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/datacenter-data-dialog.component.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/app/wizard/set-settings/provider-settings/openstack/openstack-provider-options/openstack-provider-options.component.html
  src/app/wizard/set-settings/provider-settings/openstack/openstack-provider-options/openstack-provider-options.component.spec.ts
  src/app/wizard/set-settings/provider-settings/openstack/openstack-provider-options/openstack-provider-options.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2413 Update company name and webpage in the footer
  src/app/core/components/footer/footer.component.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2412 Add e2e tests for community edition and remove redundant prow jobs
  .prow.yaml
  cypress/integration/stories/edition.spec.ts
  cypress/pages/login.po.ts
  cypress/pages/user-panel.po.ts
  cypress/pages/user-settings.po.ts
  cypress/utils/auth.ts
  cypress/utils/condition.ts
  hack/e2e/ci-e2e.sh
  src/app/core/components/footer/footer.component.html
  src/app/core/components/user-panel/user-panel.component.html
  src/app/dynamic/enterprise/theming/picker/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2415 Update design.md
  .github/ISSUE_TEMPLATE/design-change.md
  .github/ISSUE_TEMPLATE/design.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2426 Fix e2e
  hack/e2e/ci-setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2427 Disable name generation on enter
  src/app/node-data-new/template.html
  src/app/node-data/node-data.component.html
  src/app/wizard-new/step/cluster/template.html
  src/app/wizard/set-cluster-spec/set-cluster-spec.component.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2410 Set page title according to view
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/add-cluster-sshkeys.component.ts
  src/app/cluster/cluster-details/edit-sshkeys/edit-sshkeys.component.ts
  src/app/core/components/sidenav/sidenav.component.html
  src/app/core/components/sidenav/sidenav.component.ts
  src/app/core/core.module.ts
  src/app/core/services/auth/auth.guard.ts
  src/app/core/services/page-title/page-title.service.ts
  src/app/core/services/params/params.service.ts
  src/app/kubermatic.component.ts
  src/app/shared/entity/common.ts
  src/app/shared/model/Config.ts
  src/app/sshkey/sshkey.component.ts
  src/app/testing/fake-data/userGroupConfig.fake.ts
  src/app/wizard-new/step/provider-settings/ssh-keys/component.ts
  src/app/wizard/set-settings/ssh-keys/cluster-ssh-keys.component.ts
  src/assets/config/userGroupConfig.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2428 Use View enum
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/cluster/cluster-details/revoke-token/revoke-token.component.ts
  src/app/cluster/cluster-list/cluster-list.component.ts
  src/app/core/components/sidenav/sidenav.component.ts
  src/app/member/member.component.ts
  src/app/project/project.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2391 hack/run-in-docker.sh: use node 12 which is now required
  hack/run-in-docker.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2431 Fix build/push for the CE image
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2430 Enable flatcar for openstack
  src/app/node-data-new/component.ts
  src/app/node-data/node-data.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2436 Cherry-pick CI/CD changes into v2.14 release branch
  .prow.yaml
  Makefile
  cypress/integration/stories/edition.spec.ts
  cypress/pages/login.po.ts
  cypress/pages/user-panel.po.ts
  cypress/pages/user-settings.po.ts
  cypress/utils/auth.ts
  cypress/utils/condition.ts
  hack/e2e/ci-e2e.sh
  hack/e2e/ci-setup-kubermatic-in-kind.sh
  package.json
  src/app/core/components/footer/footer.component.html
  src/app/core/components/navigation/navigation.component.html
  src/app/theming/picker/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
