Repository kubermatic/dashboard, pull requests merged in 2020-11, with the labels that each got.

#2760 Use the new endpoints
  cypress/integration/stories/machine-deployments.spec.ts
  cypress/utils/endpoint.ts
  src/app/cluster/cluster-details/change-cluster-version/component.ts
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/component.ts
  src/app/cluster/cluster-details/node-list/component.ts
  src/app/cluster/cluster-list/component.ts
  src/app/cluster/services/node.service.ts
  src/app/core/services/api/service.ts
  src/app/core/services/cluster/service.ts
  src/app/wizard/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2762 Add datastore support to vsphere provider
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2767 Change create cluster button label
  src/app/cluster/cluster-list/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2770 Add help text to addon forms
  src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.html
  src/app/shared/components/addon-list/edit-addon-dialog/edit-addon-dialog.component.scss
  src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.html
  src/app/shared/components/addon-list/install-addon-dialog/install-addon-dialog.component.scss
  src/app/shared/entity/addon.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2693 Add support for Anexia cloud provider
  src/app/cluster/cluster-details/node-list/template.html
  src/app/core/services/datacenter/service.ts
  src/app/core/services/wizard/presets.service.ts
  src/app/node-data/basic/provider/anexia/component.ts
  src/app/node-data/basic/provider/anexia/template.html
  src/app/node-data/basic/provider/template.html
  src/app/node-data/component.ts
  src/app/node-data/module.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/datacenter.ts
  src/app/shared/entity/node.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/app/wizard/module.ts
  src/app/wizard/step/provider-settings/provider/basic/anexia/component.ts
  src/app/wizard/step/provider-settings/provider/basic/anexia/template.html
  src/app/wizard/step/provider-settings/provider/basic/template.html
  src/app/wizard/step/summary/style.scss
  src/app/wizard/step/summary/template.html
  src/assets/css/_images.scss
  src/assets/images/clouds/anexia.svg
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2773 Restore list of cluster nodes
  src/app/cluster/cluster-details/component.spec.ts
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/template.html
  src/app/core/services/cluster/service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2774 [v2.15] Revert "Remove list of orphaned nodes from cluster view (#2574)"
  src/app/cluster/cluster-details/cluster-details.component.html
  src/app/cluster/cluster-details/cluster-details.component.spec.ts
  src/app/cluster/cluster-details/cluster-details.component.ts
  src/app/core/services/cluster/cluster.service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2782 Provide a better version info
  Makefile
  src/app/core/components/footer/template.html
  src/app/shared/entity/version-info.ts
  src/app/testing/fake-data/versionInfo.fake.ts
  version.js
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2781 Add support for new Openstack variables
  src/app/cluster/cluster-details/node-list/template.html
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/openstack/template.html
  src/app/shared/entity/node.ts
  src/app/testing/fake-data/node.fake.ts
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
