Repository kubermatic/dashboard, pull requests merged in 2021-12, with the labels that each got.

#3907 Downgrade ngx-clipboard
  package-lock.json
  package.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3912 Add seed dns overwrite option to mla links
  src/app/cluster/cluster-details/mla/alertmanager-config/component.ts
  src/app/shared/entity/datacenter.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3892 Update import cluster dialog & add GKE support
  cypress/integration/stories/external-cluster.spec.ts
  cypress/pages/clusters.po.ts
  cypress/pages/projects.po.ts
  src/app/cluster/cluster-list/component.ts
  src/app/cluster/cluster-list/template.html
  src/app/cluster/external-cluster-details/component.ts
  src/app/core/interceptors/error-notifications.ts
  src/app/core/services/cluster.ts
  src/app/shared/components/add-external-cluster-dialog/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/gke/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/gke/style.scss
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/gke/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/style.scss
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/custom/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/custom/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/gke/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/gke/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/style.scss
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/provider/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/provider/style.scss
  src/app/shared/components/add-external-cluster-dialog/steps/provider/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/service.ts
  src/app/shared/components/add-external-cluster-dialog/style.scss
  src/app/shared/components/add-external-cluster-dialog/template.html
  src/app/shared/components/external-cluster-data-dialog/component.ts
  src/app/shared/components/external-cluster-data-dialog/template.html
  src/app/shared/entity/external-cluster.ts
  src/app/shared/module.ts
  src/app/shared/validators/async-credentials.validator.ts
  src/app/shared/validators/base-form.validator.ts
  src/assets/css/_images.scss
  src/assets/images/clouds/gke.svg
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#3918 Adjust endpoint name
  src/app/core/interceptors/error-notifications.ts
  src/app/shared/validators/async-credentials.validator.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3919 Small sidenav logic update
  src/app/core/components/navigation/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3916 Add support for external providers presets
  src/app/settings/admin/module.ts
  src/app/settings/admin/presets/component.ts
  src/app/settings/admin/presets/dialog/steps/provider/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/aks/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/aks/template.html
  src/app/settings/admin/presets/dialog/steps/settings/provider/eks/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/eks/template.html
  src/app/settings/admin/presets/dialog/steps/settings/provider/gke/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/gke/template.html
  src/app/settings/admin/presets/dialog/steps/settings/template.html
  src/app/shared/entity/preset.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/assets/css/_images.scss
  src/assets/images/clouds/aks.svg
  src/assets/images/clouds/eks.svg
Labels: lgtm, release-note, approved, size/XL, dco-signoff: yes

#3925 Add health status for mla
  src/app/cluster/cluster-details/cluster-secrets/component.spec.ts
  src/app/cluster/cluster-details/cluster-secrets/component.ts
  src/app/cluster/cluster-details/cluster-secrets/template.html
  src/app/shared/entity/health.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3940 Only display cni versions greater than current one
  src/app/cluster/cluster-details/cni-version/cni-version-dialog/component.ts
  src/app/cluster/cluster-details/cni-version/component.ts
  src/app/cluster/cluster-details/cni-version/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3811 Add wizard options for AWS AssumeRole
  hack/run-in-docker.sh
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/edit-provider-settings/aws-provider-settings/component.ts
  src/app/cluster/cluster-details/edit-provider-settings/aws-provider-settings/template.html
  src/app/cluster/cluster-details/edit-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/component.ts
  src/app/cluster/cluster-details/edit-provider-settings/template.html
  src/app/core/services/node-data/provider/aws.ts
  src/app/core/services/wizard/provider/aws.ts
  src/app/shared/entity/cluster.ts
  src/app/testing/fake-data/cluster.ts
  src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
  src/app/wizard/step/provider-settings/provider/basic/aws/template.html
  src/app/wizard/step/provider-settings/provider/extended/aws/component.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3951 Display more external cluster details
  src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/component.ts
  src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/template.html
  src/app/cluster/cluster-details/machine-deployment-details/component.ts
  src/app/cluster/cluster-details/machine-deployment-details/template.html
  src/app/cluster/cluster-details/machine-deployment-list/component.ts
  src/app/cluster/cluster-details/machine-deployment-list/template.html
  src/app/cluster/cluster-details/node-list/component.ts
  src/app/cluster/cluster-details/node-list/template.html
  src/app/cluster/cluster-details/version-picker/component.ts
  src/app/cluster/cluster-details/version-picker/template.html
  src/app/cluster/cluster-list/component.ts
  src/app/cluster/external-cluster-details/component.ts
  src/app/cluster/external-cluster-details/style.scss
  src/app/cluster/external-cluster-details/template.html
  src/app/core/services/cluster.ts
  src/app/core/services/page-title.ts
  src/app/node-data/kubelet-version/component.ts
  src/app/node-data/kubelet-version/template.html
  src/app/shared/components/add-external-cluster-dialog/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/eks/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/gke/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/provider/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/service.ts
  src/app/shared/components/external-cluster-data-dialog/component.ts
  src/app/shared/entity/cluster.spec.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/external-cluster-model.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3957 Enable presets for AKS and EKS
  src/app/settings/admin/presets/dialog/steps/settings/provider/aws/template.html
  src/app/settings/admin/presets/dialog/steps/settings/provider/eks/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/eks/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/aks/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/aks/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/eks/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/service.ts
  src/app/shared/entity/external-cluster-model.ts
  src/app/shared/entity/preset.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3953 Add destination to etcd restore
  src/app/backup/details/automatic-backup/backups/component.ts
  src/app/backup/details/automatic-backup/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3960 Update supported Cilium version to 1.11
  src/app/shared/entity/cluster.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3961 Enable konnectivity by default
  src/app/wizard/step/cluster/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3966 Fix project card buttons styling
  src/app/project/style.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3969 [release/v2.18] Version bump for 2.18.4
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3972 Fix icon button borders
  src/assets/css/material/_main.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3970 Fix checkbox cursor
  src/assets/css/material/_main.scss
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3978 Use destination in restore dialog
  src/app/backup/list/snapshot/restore-dialog/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3981 Update Canal supported versions - add v3.21, remove v3.8
  src/app/shared/entity/cluster.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3991 Use cni version endpoints
  src/app/cluster/cluster-details/cni-version/component.ts
  src/app/cluster/cluster-details/component.spec.ts
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/template.html
  src/app/core/services/api.ts
  src/app/core/services/cluster.ts
  src/app/shared/entity/cluster.ts
  src/app/testing/services/cluster-mock.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3979 Display and handle status updates
  src/app/cluster/cluster-details/machine-deployment-details/template.html
  src/app/cluster/cluster-details/node-list/component.ts
  src/app/cluster/cluster-details/template.html
  src/app/cluster/external-cluster-details/component.ts
  src/app/cluster/external-cluster-details/external-machine-deployment-details/component.ts
  src/app/cluster/external-cluster-details/external-machine-deployment-details/template.html
  src/app/cluster/external-cluster-details/external-machine-deployment-list/component.ts
  src/app/cluster/external-cluster-details/external-machine-deployment-list/template.html
  src/app/cluster/external-cluster-details/external-node-list/component.ts
  src/app/cluster/external-cluster-details/external-node-list/template.html
  src/app/cluster/external-cluster-details/style.scss
  src/app/cluster/external-cluster-details/template.html
  src/app/cluster/list/external-cluster/component.ts
  src/app/cluster/list/external-cluster/template.html
  src/app/core/services/cluster.ts
  src/app/shared/entity/external-cluster.ts
  src/app/shared/entity/external-machine-deployment.ts
  src/app/shared/entity/machine-deployment.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3980 Support for OSM in dashboard
  src/app/cluster/cluster-details/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#3948 Add support for EventRateLimit admission plugin
  src/app/cluster/cluster-details/edit-cluster/component.spec.ts
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/cluster/cluster-details/template.html
  src/app/core/services/cluster-spec.ts
  src/app/shared/components/cluster-summary/style.scss
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/event-rate-limit/component.spec.ts
  src/app/shared/components/event-rate-limit/component.ts
  src/app/shared/components/event-rate-limit/style.scss
  src/app/shared/components/event-rate-limit/template.html
  src/app/shared/components/number-stepper/component.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/module.ts
  src/app/shared/utils/admission-plugin-utils/admission-plugin-utils.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3996 Use delete endpoint for backup destinations
  src/app/core/services/backup.ts
  src/app/settings/admin/bucket-settings/destinations/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4000 Bump END_OF_DOCKER_SUPPORT_VERSION to 1.24.0
  src/app/shared/entity/cluster.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3998 Do not allow ebpf proxy mode if konnectivity is disabled
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4004 Bump Cypress version
  cypress/integration/stories/external-cluster.spec.ts
  package-lock.json
  package.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4005 External clusters improvements
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4006 Refactor entities and provider-related logic
  src/app/cluster-template/component.ts
  src/app/cluster-template/template.html
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/template.html
  src/app/cluster/details/cluster/machine-deployment-details/component.ts
  src/app/cluster/list/cluster/component.ts
  src/app/cluster/list/cluster/template.html
  src/app/core/services/api.ts
  src/app/core/services/cluster-spec.ts
  src/app/core/services/cluster.ts
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/component.ts
  src/app/node-data/kubelet-version/component.ts
  src/app/project/edit-project/component.ts
  src/app/shared/components/add-project-dialog/component.ts
  src/app/shared/entity/cluster.spec.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/project.ts
  src/app/shared/model/CreateClusterModel.ts
  src/app/shared/model/CreateProjectModel.ts
  src/app/shared/model/NodeSpecChange.ts
  src/app/testing/services/api-mock.ts
  src/app/testing/services/cluster-mock.ts
  src/app/wizard/component.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4007 Hide CNI version picker arrow if it is disabled
  src/assets/css/global/_main.scss
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes
