Repository kubermatic/dashboard, pull requests merged in 2021-06, with the labels that each got.

#3399 Use vNet resource group instead of resource group if it is specified
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3386 Redesign service account group picker
  cypress/pages/members.po.ts
  cypress/pages/service-accounts.po.ts
  src/app/member/add-member/template.html
  src/app/member/edit-member/template.html
  src/app/serviceaccount/add-serviceaccount/template.html
  src/app/serviceaccount/edit-serviceaccount/template.html
  src/assets/css/global/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3407 Update text in some places
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/cluster/cluster-details/edit-sshkeys/component.ts
  src/app/shared/components/add-ssh-key-dialog/component.ts
  src/app/shared/components/add-ssh-key-dialog/template.html
  src/app/shared/components/addon-list/template.html
  src/app/wizard/step/cluster/template.html
  src/assets/css/material/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3400 Add spot instance checkbox
  src/app/cluster/cluster-details/node-list/template.html
  src/app/node-data/extended/provider/aws/component.ts
  src/app/node-data/extended/provider/aws/style.scss
  src/app/node-data/extended/provider/aws/template.html
  src/app/shared/entity/node.ts
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3402 Fix replica count
  src/app/node-data/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3419 Presets improvements
  src/app/serviceaccount/component.ts
  src/app/settings/admin/presets/dialog/steps/preset/component.ts
  src/app/settings/admin/presets/dialog/steps/preset/template.html
  src/app/settings/admin/presets/dialog/steps/service.ts
  src/app/settings/admin/presets/dialog/steps/settings/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3409 Dark mode improvements
  src/app/cluster/cluster-details/constraints/template.html
  src/app/cluster/cluster-details/gatekeeper-config/template.html
  src/app/cluster/cluster-details/machine-networks-display/template.html
  src/app/cluster/cluster-details/rbac/template.html
  src/app/core/components/sidenav/theme.scss
  src/app/serviceaccount/token/template.html
  src/app/settings/admin/admins/template.html
  src/app/settings/admin/constraint-templates/template.html
  src/app/settings/admin/dynamic-datacenters/template.html
  src/app/settings/admin/presets/template.html
  src/app/shared/components/addon-list/template.html
  src/app/shared/components/loader/template.html
  src/app/shared/components/search-field/template.html
  src/assets/css/global/_theme.scss
  src/assets/css/material/_theme.scss
  src/assets/themes/dark.scss
  src/assets/themes/light.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3412 Remove option to reset admin settings to defaults
  src/app/settings/admin/component.ts
  src/app/settings/admin/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#3427 bumped dashboard to 2.17.1
  Makefile
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3421 Buttons styling improvements
  src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/style.scss
  src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/template.html
  src/app/cluster/cluster-details/style.scss
  src/app/cluster/cluster-details/template.html
  src/app/shared/components/addon-list/install-addon-dialog/component.ts
  src/app/shared/components/addon-list/install-addon-dialog/template.html
  src/app/shared/components/addon-list/install-addon-dialog/theme.scss
  src/app/shared/components/addon-list/select-addon-dialog/style.scss
  src/app/shared/components/tab-card/theme.scss
  src/app/wizard/step/cluster/ssh-keys/template.html
  src/assets/css/global/_main.scss
  src/assets/css/material/_main.scss
  src/assets/css/material/_theme.scss
  src/assets/themes/light.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3431 Fix button styling
  src/assets/css/material/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3392 Align enforce setting behavior
  cypress/integration/stories/admin-settings/opa-integration.spec.ts
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/settings/admin/template.html
  src/app/wizard/step/cluster/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3433 Fix sorting on node list
  src/app/cluster/cluster-details/node-list/component.ts
  src/app/cluster/cluster-details/node-list/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3432 Add search for projects
  src/app/cluster/cluster-list/template.html
  src/app/project/component.ts
  src/app/project/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3439 Fix custom link icon display in the sidenav
  src/app/core/components/sidenav/style.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3429 Clarify PV cleanup during cluster delete
  src/app/cluster/cluster-details/cluster-delete-confirmation/template.html
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#3447 Fix add icon placement
  src/app/cluster/cluster-details/constraints/template.html
  src/app/cluster/cluster-details/gatekeeper-config/template.html
  src/app/cluster/cluster-details/machine-networks-display/template.html
  src/app/cluster/cluster-details/rbac/template.html
  src/app/serviceaccount/token/template.html
  src/app/settings/admin/admins/template.html
  src/app/settings/admin/constraint-templates/template.html
  src/app/settings/admin/dynamic-datacenters/template.html
  src/app/settings/admin/presets/template.html
  src/app/shared/components/addon-list/template.html
  src/app/wizard/step/cluster/ssh-keys/template.html
  src/assets/css/_images.scss
  src/assets/css/material/_main.scss
  src/assets/images/icons/plus.svg
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3450 Embed fonts
  package-lock.json
  package.json
  src/assets/css/root.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3448 Add container runtime selector
  cypress/integration/providers/vsphere.spec.ts
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/cluster/cluster-details/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3441 Add condition to opa components call
  src/app/cluster/cluster-details/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3455 Add Azure LoadBalancer SKU
  src/app/settings/admin/presets/dialog/steps/settings/provider/azure/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/azure/template.html
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/preset.ts
  src/app/testing/fake-data/cluster.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3463 [release/v2.17] Add Azure LoadBalancer SKU
  src/app/settings/admin/presets/dialog/steps/settings/provider/azure/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/azure/template.html
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/preset.ts
  src/app/testing/fake-data/cluster.fake.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3471 Add vSphere resource pool
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#3474 Reduce minimum tab width
  src/app/shared/components/tab-card/style.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
