Repository kubermatic/dashboard, pull requests merged in 2021-02, with the labels that each got.

#3025 Add option to disable User SSH Key Agent from the cluster wizard
  src/app/cluster/cluster-details/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3034 Update pod security policy warning
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/wizard/step/cluster/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3033 Fix subscription memory leak
  src/app/core/services/cluster/service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3028 Refactor and update service account token management UI
  cypress/integration/stories/machine-deployments.spec.ts
  cypress/pages/clusters.po.ts
  cypress/pages/members.po.ts
  cypress/pages/projects.po.ts
  cypress/pages/service-accounts.po.ts
  src/app/core/module.ts
  src/app/routing.ts
  src/app/serviceaccount/component.spec.ts
  src/app/serviceaccount/component.ts
  src/app/serviceaccount/module.ts
  src/app/serviceaccount/routing.module.ts
  src/app/serviceaccount/serviceaccount-token/add-serviceaccount-token/add-serviceaccount-token.component.html
  src/app/serviceaccount/serviceaccount-token/add-serviceaccount-token/add-serviceaccount-token.component.spec.ts
  src/app/serviceaccount/serviceaccount-token/add-serviceaccount-token/add-serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount-token/edit-serviceaccount-token/edit-serviceaccount-token.component.html
  src/app/serviceaccount/serviceaccount-token/edit-serviceaccount-token/edit-serviceaccount-token.component.spec.ts
  src/app/serviceaccount/serviceaccount-token/edit-serviceaccount-token/edit-serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount-token/serviceaccount-token.component.scss
  src/app/serviceaccount/serviceaccount-token/token-dialog/token-dialog.component.html
  src/app/serviceaccount/serviceaccount-token/token-dialog/token-dialog.component.ts
  src/app/serviceaccount/serviceaccount.component.scss
  src/app/serviceaccount/style.scss
  src/app/serviceaccount/template.html
  src/app/serviceaccount/token/add/component.spec.ts
  src/app/serviceaccount/token/add/component.ts
  src/app/serviceaccount/token/add/steps/information/component.spec.ts
  src/app/serviceaccount/token/add/steps/information/component.ts
  src/app/serviceaccount/token/add/steps/information/style.scss
  src/app/serviceaccount/token/add/steps/information/template.html
  src/app/serviceaccount/token/add/steps/name/component.spec.ts
  src/app/serviceaccount/token/add/steps/name/component.ts
  src/app/serviceaccount/token/add/steps/name/style.scss
  src/app/serviceaccount/token/add/steps/name/template.html
  src/app/serviceaccount/token/add/steps/service.ts
  src/app/serviceaccount/token/add/style.scss
  src/app/serviceaccount/token/add/template.html
  src/app/serviceaccount/token/component.spec.ts
  src/app/serviceaccount/token/component.ts
  src/app/serviceaccount/token/style.scss
  src/app/serviceaccount/token/template.html
  src/app/settings/admin/presets/dialog/steps/preset/component.ts
  src/app/settings/admin/presets/dialog/steps/preset/template.html
  src/app/settings/admin/presets/dialog/steps/settings/component.ts
  src/app/settings/admin/presets/dialog/template.html
  src/app/settings/admin/template.html
  src/app/shared/shared.module.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#3038 Add GPU information to AWS node sizes
  src/app/node-data/basic/provider/aws/component.ts
  src/app/node-data/basic/provider/aws/template.html
  src/app/shared/entity/provider/aws.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#3027 Remove CoreOS
  .editorconfig
  hack/e2e/fixtures/seed.yaml
  hack/run-in-docker.sh
  src/app/cluster/cluster-details/machine-deployment-details/template.html
  src/app/cluster/cluster-details/node-list/template.html
  src/app/cluster/cluster-list/component.ts
  src/app/cluster/cluster-list/template.html
  src/app/cluster/services/node.service.ts
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/component.ts
  src/app/node-data/template.html
  src/app/shared/entity/datacenter.ts
  src/app/shared/entity/node.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/app/shared/model/NodeSpecChange.ts
  src/app/testing/fake-data/datacenter.fake.ts
  src/app/testing/fake-data/node.fake.ts
  src/app/wizard/service/wizard.ts
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3043 Cluster health state should only be checked for known statuses
  src/app/shared/entity/health.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3053 Filter external networks in openstack wizard
  src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XS

#3063 Validate name during cluster creation with the same pattern as on edit
  src/app/wizard/step/cluster/component.ts
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#3008 OPA - Add Constraints table to cluster details view
  src/app/cluster/cluster-details/component.spec.ts
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/constraints/component.ts
  src/app/cluster/cluster-details/constraints/constraint-dialog/component.ts
  src/app/cluster/cluster-details/constraints/constraint-dialog/style.scss
  src/app/cluster/cluster-details/constraints/constraint-dialog/template.html
  src/app/cluster/cluster-details/constraints/style.scss
  src/app/cluster/cluster-details/constraints/template.html
  src/app/cluster/cluster-details/constraints/violation-details/component.ts
  src/app/cluster/cluster-details/constraints/violation-details/style.scss
  src/app/cluster/cluster-details/constraints/violation-details/template.html
  src/app/cluster/module.ts
  src/app/core/services/opa/service.ts
  src/app/shared/entity/opa.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#3056 OPA - Gatekeeper Config
  src/app/cluster/cluster-details/component.spec.ts
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/gatekeeper-config/component.ts
  src/app/cluster/cluster-details/gatekeeper-config/gatekeeper-config-dialog/component.ts
  src/app/cluster/cluster-details/gatekeeper-config/gatekeeper-config-dialog/style.scss
  src/app/cluster/cluster-details/gatekeeper-config/gatekeeper-config-dialog/template.html
  src/app/cluster/cluster-details/gatekeeper-config/style.scss
  src/app/cluster/cluster-details/gatekeeper-config/template.html
  src/app/cluster/cluster-details/gatekeeper-config/theme.scss
  src/app/cluster/module.ts
  src/app/core/interceptors/error-notifications/interceptor.ts
  src/app/core/services/opa/service.ts
  src/app/shared/entity/opa.ts
  src/assets/css/theme/_component.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3082 Check if OPA is enabled, before calling endpoints
  src/app/cluster/cluster-details/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3083 fix makefile for commits with multiple version tags
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3099 OPA- filter constraints by constraint template
  src/app/cluster/cluster-details/constraints/component.ts
  src/app/cluster/cluster-details/constraints/style.scss
  src/app/cluster/cluster-details/constraints/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3080 OPA - Add gatekeeper status to cluster details view
  src/app/cluster/cluster-details/cluster-secrets/component.ts
  src/app/cluster/cluster-details/cluster-secrets/template.html
  src/app/shared/entity/health.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3100 Remove OpenShift support
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/template.html
  src/app/core/services/api/service.ts
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/component.ts
  src/app/settings/admin/component.spec.ts
  src/app/settings/admin/component.ts
  src/app/settings/admin/template.html
  src/app/shared/entity/cluster.spec.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/settings.ts
  src/app/shared/model/ClusterForm.ts
  src/app/testing/services/api-mock.service.ts
  src/app/testing/services/settings-mock.service.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/summary/template.html
  src/assets/css/_images.scss
  src/assets/css/global/_main.scss
  src/assets/images/icons/openshift.svg
  src/assets/themes/dark.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3102 Fix label styling
  src/app/core/components/changelog/style.scss
  src/app/core/components/changelog/template.html
  src/app/core/components/changelog/theme.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3052 Fix issue with watching system color scheme and edition e2e tests
  cypress/integration/stories/edition.spec.ts
  cypress/pages/user-panel.po.ts
  cypress/pages/user-settings.po.ts
  src/app/dynamic/enterprise/theming/services/color-scheme.ts
  src/app/dynamic/enterprise/theming/services/manager.ts
  src/app/testing/router-stubs.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3104 Redesign add/edit member dialog
  cypress/pages/members.po.ts
  src/app/core/components/changelog/template.html
  src/app/core/module.ts
  src/app/member/add-member/component.spec.ts
  src/app/member/add-member/component.ts
  src/app/member/add-member/template.html
  src/app/member/edit-member/component.spec.ts
  src/app/member/edit-member/component.ts
  src/app/member/edit-member/template.html
  src/app/member/member.component.ts
  src/app/member/member.module.ts
  src/app/shared/shared.module.ts
  src/assets/css/global/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3113 Display GPU count for Alibaba instance types
  src/app/node-data/basic/provider/alibaba/component.ts
  src/app/node-data/basic/provider/alibaba/template.html
  src/app/shared/entity/provider/alibaba.ts
  src/app/testing/fake-data/alibaba.fake.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#3114 Remove duplicated kubeadm instructions
  src/app/cluster/cluster-details/node-list/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
