Repository kubermatic/dashboard, pull requests merged in 2021-01, with the labels that each got.

#2903 Do not remove labels when pressing enter key in the label form
  src/app/shared/components/label-form/label-form.component.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2547 Align azure spec with the API
  src/app/cluster/cluster-details/node-list/template.html
  src/app/node-data/basic/provider/azure/component.ts
  src/app/node-data/basic/provider/azure/template.html
  src/app/shared/components/combobox/component.ts
  src/app/shared/components/combobox/template.html
  src/app/shared/entity/node.ts
  src/app/testing/fake-data/node.fake.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2890 Added keydown.enter to forms
  src/app/cluster/cluster-details/cluster-delete-confirmation/template.html
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/template.html
  src/app/cluster/cluster-details/rbac/add-binding/component.ts
  src/app/cluster/cluster-details/rbac/add-binding/template.html
  src/app/cluster/cluster-details/revoke-token/template.html
  src/app/member/add-member/add-member.component.html
  src/app/member/add-member/add-member.component.ts
  src/app/member/edit-member/edit-member.component.html
  src/app/member/edit-member/edit-member.component.ts
  src/app/project/delete-project/delete-project.component.html
  src/app/project/edit-project/edit-project.component.html
  src/app/project/edit-project/edit-project.component.ts
  src/app/serviceaccount/add-serviceaccount/add-serviceaccount.component.html
  src/app/serviceaccount/add-serviceaccount/add-serviceaccount.component.ts
  src/app/serviceaccount/edit-serviceaccount/edit-serviceaccount.component.html
  src/app/serviceaccount/edit-serviceaccount/edit-serviceaccount.component.ts
  src/app/serviceaccount/serviceaccount-token/add-serviceaccount-token/add-serviceaccount-token.component.html
  src/app/serviceaccount/serviceaccount-token/add-serviceaccount-token/add-serviceaccount-token.component.ts
  src/app/serviceaccount/serviceaccount-token/edit-serviceaccount-token/edit-serviceaccount-token.component.html
  src/app/serviceaccount/serviceaccount-token/edit-serviceaccount-token/edit-serviceaccount-token.component.ts
  src/app/settings/admin/admins/add-admin-dialog/component.ts
  src/app/settings/admin/admins/add-admin-dialog/template.html
  src/app/shared/components/add-project-dialog/add-project-dialog.component.html
  src/app/shared/components/add-project-dialog/add-project-dialog.component.ts
  src/app/shared/components/add-ssh-key-dialog/add-ssh-key-dialog.component.html
  src/app/shared/components/add-ssh-key-dialog/add-ssh-key-dialog.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2929 Pod Node Selector Config
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-cluster/style.scss
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/shared/components/label-form/label-form.component.html
  src/app/shared/components/label-form/label-form.component.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/model/ClusterForm.ts
  src/app/shared/services/cluster.service.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2909 Use an endpoint to get AWS Security Group IDs in the wizard for the cluster creation
  src/app/core/services/wizard/provider/aws.ts
  src/app/shared/entity/provider/aws.ts
  src/app/shared/shared.module.ts
  src/app/wizard/step/provider-settings/provider/extended/aws/component.ts
  src/app/wizard/step/provider-settings/provider/extended/aws/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2956 UI/UX Fixes
  src/app/cluster/cluster-details/node-list/template.html
  src/app/cluster/cluster-details/rbac/template.html
  src/assets/css/_variables.scss
  src/assets/css/material/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2784 [WIP] Guided Tour
  src/app/project/project.component.html
  src/app/project/project.component.ts
  src/app/shared/components/add-project-dialog/add-project-dialog.component.html
  src/app/shared/components/add-project-dialog/add-project-dialog.component.ts
  src/app/shared/components/guided-tour/dialog/component.ts
  src/app/shared/components/guided-tour/dialog/entity.ts
  src/app/shared/components/guided-tour/dialog/helper.service.ts
  src/app/shared/components/guided-tour/dialog/overlay-ref.ts
  src/app/shared/components/guided-tour/dialog/service.ts
  src/app/shared/components/guided-tour/dialog/template.html
  src/app/shared/components/guided-tour/dialog/theme.scss
  src/app/shared/components/guided-tour/directive.ts
  src/app/shared/components/guided-tour/entity.ts
  src/app/shared/components/guided-tour/steps/add-project-btn/component.ts
  src/app/shared/components/guided-tour/steps/add-project-btn/template.html
  src/app/shared/components/guided-tour/steps/add-project-dialog/component.ts
  src/app/shared/components/guided-tour/steps/add-project-dialog/template.html
  src/app/shared/components/guided-tour/steps/project-item/component.ts
  src/app/shared/components/guided-tour/steps/project-item/template.html
  src/app/shared/components/guided-tour/utils.ts
  src/app/shared/shared.module.ts
  src/assets/css/theme/_component.scss
Labels: approved, dco-signoff: yes, do-not-merge/work-in-progress, release-note-none, size/XL

#2957 [release/v2.15] Pod Node Selector Config
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.html
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.scss
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts
  src/app/shared/components/label-form/label-form.component.html
  src/app/shared/components/label-form/label-form.component.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/model/ClusterForm.ts
  src/app/shared/services/cluster.service.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2976 update Go dependencies, cleanup .prow.yaml
  .prow.yaml
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2961 [release/v2.14] Pod Node Selector Config
  .prow.yaml
  hack/e2e/ci-setup-kubermatic-in-kind.sh
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.html
  src/app/cluster/cluster-details/edit-cluster/edit-cluster.component.ts
  src/app/shared/components/label-form/label-form.component.html
  src/app/shared/components/label-form/label-form.component.ts
  src/app/shared/entity/ClusterEntity.ts
  src/app/shared/entity/ClusterEntityPatch.ts
  src/app/shared/model/ClusterForm.ts
  src/app/wizard/set-cluster-spec/set-cluster-spec.component.html
  src/app/wizard/set-cluster-spec/set-cluster-spec.component.ts
  src/app/wizard/set-datacenter/set-datacenter.component.ts
  src/app/wizard/summary/summary.component.html
  src/app/wizard/wizard.component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2936 Use endpoints to get Azure resource groups, security groups and route tables
  src/app/core/services/wizard/provider/azure.ts
  src/app/core/services/wizard/provider/provider.ts
  src/app/shared/entity/provider/azure.ts
  src/app/wizard/step/provider-settings/provider/extended/aws/component.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#2971 Add OPA table to admin view
  src/app/core/services/api/service.ts
  src/app/settings/admin/module.ts
  src/app/settings/admin/opa/component.ts
  src/app/settings/admin/opa/template.html
  src/app/shared/entity/opa.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2988 Use endpoint to load Azure subnets
  src/app/core/services/wizard/provider/azure.ts
  src/app/shared/entity/provider/azure.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3000 OPA - Added options to enable/disable OPA Integration
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-cluster/style.scss
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/shared/entity/cluster.ts
  src/app/shared/model/ClusterForm.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2982 Migrate from Helm to Kubermatic Installer in e2e tests
  .prow.yaml
  Makefile
  containers/cypress/Dockerfile
  containers/cypress/build-and-release.sh
  hack/e2e/ci-setup-kubermatic-in-kind.sh
  hack/e2e/fixtures/kubermatic.yaml
  hack/e2e/fixtures/oauth_values.yaml
  hack/e2e/fixtures/seed.yaml
  hack/e2e/run-tests.sh
  hack/e2e/setup-kind-cluster.sh
  hack/e2e/setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#2999 OPA - Add actions for Constraint Templates in Admin Settings
  src/app/core/module.ts
  src/app/core/services/api/service.ts
  src/app/core/services/opa/service.ts
  src/app/settings/admin/constraint-templates/component.ts
  src/app/settings/admin/constraint-templates/constraint-template-dialog/component.ts
  src/app/settings/admin/constraint-templates/constraint-template-dialog/style.scss
  src/app/settings/admin/constraint-templates/constraint-template-dialog/template.html
  src/app/settings/admin/constraint-templates/template.html
  src/app/settings/admin/module.ts
  src/app/settings/admin/opa/component.ts
  src/app/shared/entity/opa.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#2928 openstack wizard: pre-fill username and domain fields
  src/app/shared/model/Config.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
  src/assets/config/config.json
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/S

#3005 Update Angular and other dependencies
  angular.json
  jest.config.js
  package-lock.json
  package.json
  src/app/cluster/cluster-details/change-cluster-version/component.spec.ts
  src/app/cluster/cluster-details/cluster-delete-confirmation/component.spec.ts
  src/app/cluster/cluster-details/edit-cluster/component.spec.ts
  src/app/cluster/cluster-details/node-list/component.spec.ts
  src/app/cluster/services/node.service.spec.ts
  src/app/core/components/notification/style.scss
  src/app/core/components/notification/template.html
  src/app/member/add-member/add-member.component.spec.ts
  src/app/member/edit-member/edit-member.component.spec.ts
  src/app/project/edit-project/edit-project.component.spec.ts
  src/app/serviceaccount/add-serviceaccount/add-serviceaccount.component.spec.ts
  src/app/serviceaccount/edit-serviceaccount/edit-serviceaccount.component.spec.ts
  src/app/shared/components/add-project-dialog/add-project-dialog.component.spec.ts
  src/app/shared/components/add-ssh-key-dialog/add-ssh-key-modal.component.spec.ts
  src/assets/css/global/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#3012 declare master branch as 2.17-dev
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3013 revert ngx-monaco-editor to v9.0.0
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3019 Add resource quota settings to admin panel
  src/app/settings/admin/template.html
  src/app/shared/entity/settings.ts
  src/app/testing/services/settings-mock.service.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3020 Add autocompletions for vSphere datastores
  src/app/core/services/wizard/provider/vsphere.ts
  src/app/shared/entity/provider/vsphere.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M
