Repository kubermatic/dashboard, pull requests merged in 2021-08, with the labels that each got.

#3580 Improve aliababa wizard form handling
  src/app/core/components/notification-panel/component.ts
  src/app/core/interceptors/error-notifications.ts
  src/app/core/services/node-data/provider/alibaba.ts
  src/app/core/services/notification.ts
  src/app/node-data/basic/provider/alibaba/component.ts
  src/assets/css/global/_main.scss
  src/assets/css/global/_theme.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3582 Improve anexia wizard form handling
  src/app/core/interceptors/error-notifications.ts
  src/app/core/services/node-data/provider/anexia.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3586 Improve AWS wizard form handling
  src/app/core/interceptors/error-notifications.ts
  src/app/core/services/node-data/provider/aws.ts
  src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3594 Improve DigitalOcean/GCP/Hetzner wizard form handling
  src/app/core/interceptors/error-notifications.ts
  src/app/core/services/node-data/provider/digitalocean.ts
  src/app/core/services/node-data/provider/gcp.ts
  src/app/core/services/node-data/provider/hetzner.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
  src/app/wizard/step/provider-settings/provider/extended/gcp/component.ts
  src/app/wizard/step/provider-settings/provider/extended/hetzner/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3587 Improve Azure wizard form handling
  src/app/core/components/notification-panel/component.ts
  src/app/core/interceptors/error-notifications.ts
  src/app/core/services/node-data/provider/azure.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3598 [MLA] Rename User Cluster Alert Rules to User Cluster Recording & Alerting Rules
  src/app/cluster/cluster-details/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3595 Adjust changelog dialog to work with smaller screens
  src/app/core/components/changelog/style.scss
  src/assets/css/global/_main.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3602 Improve wizard provider forms handling and fix node data caching issue
  src/app/core/interceptors/error-notifications.ts
  src/app/core/services/node-data/provider/openstack.ts
  src/app/core/services/node-data/provider/packet.ts
  src/app/wizard/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/default/component.ts
  src/app/wizard/step/provider-settings/provider/basic/packet/template.html
  src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3607 Extend AWS spot instance configuration options
  src/app/node-data/extended/provider/aws/component.ts
  src/app/node-data/extended/provider/aws/style.scss
  src/app/node-data/extended/provider/aws/template.html
  src/app/shared/animations/push.ts
  src/app/shared/entity/node.ts
  src/app/wizard/step/summary/template.html
  src/app/wizard/template.html
  src/assets/css/material/_main.scss
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3605 Fix CE build, improve configs and add missing build check
  .prow.yaml
  angular.json
  package.json
  src/app/dynamic/module-registry.ce.ts
  src/app/dynamic/module-registry.ts
  src/app/settings/admin/opa/default-constraints/component.ts
  src/app/settings/user/routing.ts
  src/environments/environment.ts
  src/tsconfig.ce.json
  src/tsconfig.ee.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3614 Fix issue with wizard form validation on settings step
  src/app/shared/validators/base-form.validator.ts
  src/app/wizard/component.ts
  src/app/wizard/step/provider-settings/provider/basic/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3561 Add Flatcar support for KubeVirt
  src/app/node-data/component.ts
  src/app/testing/fake-data/node.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3615 Update aws spot instance max price to be bigger than 0
  src/app/cluster/cluster-details/node-list/template.html
  src/app/node-data/extended/provider/aws/component.ts
  src/app/node-data/extended/provider/aws/template.html
  src/app/shared/validators/larger-than.validator.ts
  src/app/shared/validators/validators.ts
  src/app/wizard/step/summary/template.html
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3558 Update share cluster dialog
  src/app/cluster/cluster-details/share-kubeconfig/component.spec.ts
  src/app/cluster/cluster-details/share-kubeconfig/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3612 Add checkbox for assigning Azure availability sets
  src/app/cluster/cluster-details/node-list/template.html
  src/app/cluster/cluster-details/template.html
  src/app/core/services/node-data/provider/azure.ts
  src/app/node-data/basic/provider/azure/component.ts
  src/app/node-data/basic/provider/azure/template.html
  src/app/node-data/basic/provider/digitalocean/template.html
  src/app/shared/components/combobox/component.ts
  src/app/shared/components/event-card/template.html
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/node.ts
  src/app/testing/fake-data/cluster.ts
  src/app/testing/fake-data/node.ts
  src/app/wizard/step/provider-settings/preset/component.ts
  src/app/wizard/step/provider-settings/preset/template.html
  src/app/wizard/step/provider-settings/provider/basic/azure/component.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/template.html
  src/app/wizard/step/summary/template.html
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3628 fix dev versions
  Makefile
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3632 Adjust User Cluster Alertmanager Link
  src/app/cluster/cluster-details/alertmanager-config/component.spec.ts
  src/app/cluster/cluster-details/alertmanager-config/component.ts
  src/app/settings/admin/defaults/template.html
  src/app/shared/entity/settings.ts
  src/app/testing/services/settings-mock.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3636 Fix Azure issues
  src/app/cluster/cluster-details/node-list/template.html
  src/app/core/services/node-data/provider/azure.ts
  src/app/node-data/basic/provider/azure/component.ts
  src/app/node-data/basic/provider/azure/template.html
  src/app/node-data/template.html
  src/app/shared/components/cluster-summary/template.html
Labels: release-note-none, lgtm, size/S, approved, priority/critical-urgent, dco-signoff: yes
