Repository kubermatic/dashboard, pull requests merged in 2021-03, with the labels that each got.

#3120 Redesign manage ssh keys dialog
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/component.spec.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/style.scss
  src/app/cluster/cluster-details/edit-sshkeys/add-cluster-sshkeys/template.html
  src/app/cluster/cluster-details/edit-sshkeys/component.spec.ts
  src/app/cluster/cluster-details/edit-sshkeys/component.ts
  src/app/cluster/cluster-details/edit-sshkeys/style.scss
  src/app/cluster/cluster-details/edit-sshkeys/template.html
  src/app/cluster/module.ts
  src/app/sshkey/sshkey.component.spec.ts
  src/assets/css/global/_main.scss
  src/assets/css/global/_theme.scss
  src/assets/css/material/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3121 Move VSphere diskSizeGB from extended to basic/required options
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/basic/provider/vsphere/template.html
  src/app/node-data/dialog/component.ts
  src/app/node-data/extended/provider/vsphere/component.ts
  src/app/node-data/extended/provider/vsphere/template.html
  src/app/node-data/extended/template.html
  src/app/node-data/module.ts
  src/app/shared/entity/node.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3127 Use global settings for initial replicas fields in wizard/edit md dialog
  src/app/cluster/cluster-details/machine-deployment-list/template.html
  src/app/node-data/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3128 Remove apache license from index.html and enterprise files
  license-checker-config.json
  src/app/dynamic/enterprise/theming/module.ts
  src/app/dynamic/enterprise/theming/picker/component.ts
  src/app/dynamic/enterprise/theming/picker/style.scss
  src/app/dynamic/enterprise/theming/picker/template.html
  src/app/dynamic/enterprise/theming/services/color-scheme.ts
  src/app/dynamic/enterprise/theming/services/manager.ts
  src/app/dynamic/enterprise/theming/services/theme.ts
  src/index.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3076 OPA - Constraint Templates improvements
  src/app/settings/admin/constraint-templates/component.ts
  src/app/settings/admin/constraint-templates/constraint-template-dialog/component.ts
  src/app/settings/admin/constraint-templates/constraint-template-dialog/template.html
  src/app/settings/admin/constraint-templates/style.scss
  src/app/settings/admin/constraint-templates/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3122 Redesign autocomplete inputs
  src/app/dynamic/enterprise/theming/picker/template.html
  src/app/settings/admin/custom-link-form/style.scss
  src/app/settings/admin/custom-link-form/template.html
  src/app/settings/admin/template.html
  src/app/settings/user/user-settings.component.html
  src/app/shared/components/autocomplete/component.ts
  src/app/shared/components/autocomplete/template.html
  src/app/shared/components/spinner-with-confirmation/component.ts
  src/app/shared/components/spinner-with-confirmation/style.scss
  src/app/shared/components/spinner-with-confirmation/template.html
  src/app/shared/shared.module.ts
  src/app/wizard/step/provider-settings/provider/extended/aws/component.ts
  src/app/wizard/step/provider-settings/provider/extended/aws/template.html
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/template.html
  src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#3140 Add GPU count for Azure instances
  src/app/node-data/basic/provider/azure/component.ts
  src/app/node-data/basic/provider/azure/template.html
  src/app/shared/entity/provider/azure.ts
  src/app/testing/fake-data/addNodeModal.fake.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#3144 Assign correct label to new issues
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/cleanup.md
  .github/ISSUE_TEMPLATE/design-change.md
  .github/ISSUE_TEMPLATE/design.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3147 OPA - enable and test
  src/app/cluster/cluster-details/constraints/component.spec.ts
  src/app/cluster/cluster-details/constraints/component.ts
  src/app/cluster/cluster-details/constraints/constraint-dialog/component.spec.ts
  src/app/cluster/cluster-details/constraints/constraint-dialog/template.html
  src/app/cluster/cluster-details/constraints/violation-details/component.spec.ts
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/cluster/cluster-details/gatekeeper-config/component.spec.ts
  src/app/cluster/cluster-details/gatekeeper-config/component.ts
  src/app/cluster/cluster-details/gatekeeper-config/gatekeeper-config-dialog/component.spec.ts
  src/app/cluster/cluster-details/gatekeeper-config/gatekeeper-config-dialog/template.html
  src/app/cluster/cluster-details/gatekeeper-config/template.html
  src/app/cluster/cluster-details/template.html
  src/app/settings/admin/component.spec.ts
  src/app/settings/admin/constraint-templates/component.spec.ts
  src/app/settings/admin/constraint-templates/constraint-template-dialog/component.spec.ts
  src/app/settings/admin/constraint-templates/constraint-template-dialog/template.html
  src/app/settings/admin/template.html
  src/app/shared/entity/opa.ts
  src/app/testing/fake-data/opa.fake.ts
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#3156 adjust .prow.yaml to recent cleanup efforts
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3149 Add e2e test for AWS
  .prow.yaml
  cypress/integration/providers/aws.spec.ts
  cypress/utils/preset.ts
  cypress/utils/provider.ts
  hack/e2e/setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3155 Update to Go 1.16.1
  .prow.yaml
  containers/custom-dashboard/Dockerfile
  containers/cypress/Dockerfile
  containers/cypress/build-and-release.sh
  containers/go-node/Dockerfile
  containers/go-node/build-and-release.sh
  containers/test-chrome/Dockerfile
  containers/test-chrome/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3158 Added network to Hetzner
  src/app/node-data/basic/provider/hetzner/component.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/datacenter.ts
  src/app/shared/entity/node.ts
  src/app/wizard/module.ts
  src/app/wizard/step/provider-settings/component.ts
  src/app/wizard/step/provider-settings/provider/extended/hetzner/component.ts
  src/app/wizard/step/provider-settings/provider/extended/hetzner/template.html
  src/app/wizard/step/provider-settings/provider/extended/template.html
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3160 OPA- fix typo
  src/app/cluster/cluster-details/constraints/constraint-dialog/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3163 Do not change the theme based on the color scheme if enforced_theme is set
  src/app/dynamic/enterprise/theming/picker/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3165 Fix switching provider issue in wizard
  src/app/node-data/component.ts
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3171 [release/v2.16] Fix switching provider issue in wizard
  src/app/node-data/component.ts
  src/app/wizard/step/summary/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3173 Add missing space to error notification
  src/app/core/interceptors/error-notifications/interceptor.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3176 Add e2e tests for the azure provider
  cypress/integration/providers/azure.spec.ts
  cypress/utils/preset.ts
  cypress/utils/provider.ts
  hack/e2e/setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3186 Increase speed of tab animation
  src/app/shared/components/tab-card/style.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3177 Add E2E tests for OpenStack
  cypress/integration/providers/openstack.spec.ts
  cypress/utils/preset.ts
  cypress/utils/provider.ts
  hack/e2e/setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3170 Improve dropdown styling
  src/app/cluster/cluster-details/constraints/template.html
  src/app/node-data/style.scss
  src/app/node-data/template.html
  src/app/settings/admin/dynamic-datacenters/template.html
  src/app/settings/admin/presets/template.html
  src/app/shared/components/combobox/template.html
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/cluster/theme.scss
  src/app/wizard/step/provider-settings/preset/template.html
  src/assets/css/global/_main.scss
  src/assets/css/global/_theme.scss
  src/assets/css/material/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3193 Add E2E tests for Packet
  .prow.yaml
  cypress/integration/providers/packet.spec.ts
  cypress/utils/preset.ts
  cypress/utils/provider.ts
  hack/e2e/setup-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3196 Add E2E tests for KubeVirt
  .prow.yaml
  cypress/integration/providers/kubevirt.spec.ts
  cypress/pages/wizard.po.ts
  cypress/utils/preset.ts
  cypress/utils/provider.ts
  hack/e2e/setup-kubermatic-in-kind.sh
  src/app/node-data/basic/provider/kubevirt/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
