Repository kubermatic/dashboard, pull requests merged in 2021-05, with the labels that each got.

#3331 Disable CentOS for GCP
  src/app/node-data/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3325 Extend endpoints to filter AWS sizes
  src/app/core/services/api/service.ts
  src/app/core/services/wizard/provider/aws.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3336 Fix sidenav background behaviour
  src/app/core/components/sidenav/style.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3341 Upgrade to GitHub-native dependabot
  .github/dependabot.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3353 Add e2e tests for admin settings related to wizard
  cypress/integration/stories/admin-settings/custom-links.spec.ts
  cypress/integration/stories/admin-settings/machine-deployment-replicas.spec.ts
  cypress/integration/stories/admin-settings/opa-integration.spec.ts
  cypress/integration/stories/admin-settings/resource-quota-spec.ts
  cypress/integration/stories/machine-deployment.spec.ts
  cypress/pages/admin-settings.po.ts
  cypress/pages/clusters.po.ts
  cypress/pages/members.po.ts
  cypress/pages/projects.po.ts
  cypress/pages/service-accounts.po.ts
  cypress/pages/ssh-keys.po.ts
  cypress/pages/wizard.po.ts
  cypress/support/index.ts
  cypress/utils/condition.ts
  cypress/utils/endpoint.ts
  cypress/utils/monitor.ts
  package-lock.json
  package.json
  src/app/node-data/basic/provider/digitalocean/template.html
  src/app/settings/admin/component.ts
  src/app/settings/admin/custom-link-form/component.ts
  src/app/settings/admin/template.html
  src/app/shared/components/combobox/component.ts
  src/app/shared/components/combobox/template.html
  src/app/wizard/step/cluster/template.html
  src/assets/config/changelog.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#3359 Update theme colors
  src/assets/themes/dark.scss
  src/assets/themes/light.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3342 Add project limit story
  cypress/integration/stories/admin-settings.spec.ts
  cypress/integration/stories/admin-settings/project-limit.spec.ts
  cypress/pages/admin-settings.po.ts
  cypress/pages/projects.po.ts
  cypress/utils/condition.ts
  src/app/settings/admin/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3363 Add e2e for the cluster admin settings
  cypress/integration/stories/admin-settings/cluster-settings.spec.ts
  cypress/integration/stories/admin-settings/resource-quota.spec.ts
  cypress/pages/admin-settings.po.ts
  cypress/pages/clusters.po.ts
  cypress/pages/projects.po.ts
  src/app/cluster/cluster-details/cluster-delete-confirmation/template.html
  src/app/cluster/cluster-details/template.html
  src/app/settings/admin/template.html
  src/assets/config/config.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3366 Add e2e tests for dynamic datacenters
  cypress/integration/stories/admin-settings/dynamic-datacenters.spec.ts
  cypress/pages/admin-settings.po.ts
  cypress/utils/provider.ts
  hack/e2e/run-tests.sh
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html
  src/app/settings/admin/dynamic-datacenters/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3375 Add project managers group to SA
  src/app/serviceaccount/add-serviceaccount/template.html
  src/app/serviceaccount/edit-serviceaccount/template.html
  src/app/shared/utils/member-utils/member-utils.spec.ts
  src/app/shared/utils/member-utils/member-utils.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3378 Add warning in the wizard when there is no configured seed
  src/app/wizard/step/provider-datacenter/style.scss
  src/app/wizard/step/provider-datacenter/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3377 Add e2e test for preset
  cypress/integration/stories/admin-settings/administrators.spec.ts
  cypress/integration/stories/admin-settings/custom-links.spec.ts
  cypress/integration/stories/admin-settings/presets.spec.ts
  cypress/pages/admin-settings.po.ts
  cypress/pages/wizard.po.ts
  src/app/settings/admin/presets/dialog/steps/preset/template.html
  src/app/settings/admin/presets/dialog/steps/provider/template.html
  src/app/settings/admin/presets/dialog/steps/settings/provider/digitalocean/template.html
  src/app/settings/admin/presets/dialog/template.html
  src/app/settings/admin/presets/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3380 Update button styling
  src/app/cluster/cluster-details/constraints/style.scss
  src/app/cluster/cluster-details/constraints/template.html
  src/app/cluster/cluster-details/gatekeeper-config/template.html
  src/app/cluster/cluster-details/machine-deployment-details/style.scss
  src/app/cluster/cluster-details/machine-deployment-details/template.html
  src/app/cluster/cluster-details/rbac/style.scss
  src/app/cluster/cluster-details/rbac/template.html
  src/app/cluster/cluster-details/style.scss
  src/app/cluster/cluster-details/template.html
  src/app/cluster/external-cluster-details/style.scss
  src/app/cluster/external-cluster-details/template.html
  src/app/serviceaccount/token/style.scss
  src/app/serviceaccount/token/template.html
  src/app/settings/admin/admins/style.scss
  src/app/settings/admin/admins/template.html
  src/app/settings/admin/constraint-templates/template.html
  src/app/settings/admin/dynamic-datacenters/style.scss
  src/app/settings/admin/dynamic-datacenters/template.html
  src/app/settings/admin/presets/style.scss
  src/app/settings/admin/presets/template.html
  src/app/shared/components/addon-list/component.ts
  src/app/shared/components/addon-list/style.scss
  src/app/shared/components/addon-list/template.html
  src/app/shared/components/addon-list/theme.scss
  src/assets/css/global/_main.scss
  src/assets/css/material/_main.scss
  src/assets/css/material/_theme.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3390 Redesign 404 page
  src/app/pages/page-not-found/style.scss
  src/app/pages/page-not-found/template.html
  src/assets/css/_images.scss
  src/assets/images/branding/404-illustration-dark.svg
  src/assets/images/branding/404-illustration-light.svg
  src/assets/themes/dark.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3383 Fix handling of instanceReadyCheckPeriod and instanceReadyCheckTimeout variables
  src/app/node-data/basic/provider/openstack/template.html
  src/app/shared/entity/node.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
