Repository kubermatic/dashboard, pull requests merged in 2021-11, with the labels that each got.

#3816 Improve azure error handling and more
  hack/check-licenses.sh
  hack/development/run-npm-in-docker.sh
  hack/e2e/run-tests.sh
  hack/e2e/setup-kind-cluster.sh
  hack/e2e/setup-kubermatic-in-kind.sh
  hack/extract-themes.sh
  hack/run-dashboard.sh
  hack/run-in-docker.sh
  hack/run-local-dashboard.sh
  hack/upload-coverage.sh
  src/app/core/components/notification/component.ts
  src/app/core/interceptors/error-notifications.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
  src/assets/css/global/_main.scss
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3817 Traffic monitor improvements
  cypress/fixtures/projects.json
  cypress/integration/stories/admin-settings/administrators.spec.ts
  cypress/integration/stories/multi-owner.spec.ts
  cypress/integration/stories/user-settings.spec.ts
  cypress/pages/clusters.po.ts
  cypress/pages/projects.po.ts
  cypress/pages/service-accounts.po.ts
  cypress/pages/ssh-keys.po.ts
  cypress/utils/auth.ts
  cypress/utils/mocks.ts
  cypress/utils/monitor.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3824 Update OS selection logic for vsphere and RHEL fields
  src/app/node-data/component.ts
  src/app/node-data/template.html
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#3823 Fix relative time display
  src/app/cluster/cluster-details/edit-sshkeys/component.ts
  src/app/shared/components/relativetime/component.spec.ts
  src/app/shared/components/relativetime/component.ts
  src/app/shared/pipes/relativetime.ts
  src/app/testing/services/app-config-mock.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3836 Disable form until existing template is selected
  package.json
  src/app/shared/components/select-cluster-template/component.ts
  src/app/shared/components/select-cluster-template/template.html
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#3856 Fix version in footer
  src/app/core/components/footer/component.ts
  src/app/core/components/footer/template.html
  src/assets/config/git-version.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3851 Improve OPA loading check
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/template.html
  src/app/shared/utils/health-status/cluster-health-status.ts
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#3860 Reduce height of formfields
  src/app/cluster/cluster-details/constraints/template.html
  src/app/cluster/cluster-details/mla/rule-groups/template.html
  src/app/cluster/cluster-details/version-picker/style.scss
  src/app/dynamic/enterprise/theming/picker/style.scss
  src/app/settings/admin/defaults/style.scss
  src/app/settings/admin/defaults/template.html
  src/app/settings/admin/dynamic-datacenters/template.html
  src/app/settings/admin/opa/default-constraints/template.html
  src/app/settings/admin/presets/template.html
  src/app/shared/components/cidr-form/style.scss
  src/app/shared/components/combobox/template.html
  src/app/shared/components/label-form/style.scss
  src/app/shared/components/taint-form/style.scss
  src/app/wizard/step/provider-settings/preset/template.html
  src/assets/css/global/_main.scss
  src/assets/css/material/_main.scss
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3865 Adjust button height
  src/app/cluster/cluster-details/machine-deployment-details/cluster-panel/style.scss
  src/app/cluster/cluster-details/rbac/add-binding/style.scss
  src/app/core/components/sidenav/style.scss
  src/app/dynamic/enterprise/allowed-registries/style.scss
  src/app/dynamic/enterprise/metering/config/style.scss
  src/app/dynamic/enterprise/theming/picker/style.scss
  src/app/machine-networks/style.scss
  src/app/node-data/style.scss
  src/app/project/style.scss
  src/app/settings/admin/admins/style.scss
  src/app/settings/admin/bucket-settings/style.scss
  src/app/settings/admin/dynamic-datacenters/style.scss
  src/app/settings/admin/nav/style.scss
  src/app/settings/admin/opa/constraint-templates/style.scss
  src/app/settings/admin/opa/default-constraints/style.scss
  src/app/settings/admin/presets/style.scss
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/provider-settings/provider/basic/openstack/style.scss
  src/assets/css/global/_main.scss
  src/assets/css/material/_main.scss
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3828 Update dependencies and Node to v16
  .gitignore
  .prow.yaml
  containers/chrome-headless/Dockerfile
  containers/chrome-headless/release.sh
  containers/custom-dashboard/Dockerfile
  containers/e2e-cypress/Dockerfile
  containers/e2e-cypress/release.sh
  containers/e2e-kind-cypress/Dockerfile
  containers/e2e-kind-cypress/release.sh
  cypress/support/paste.ts
  package-lock.json
  package.json
  src/app/cluster/cluster-details/constraints/constraint-dialog/component.ts
  src/app/cluster/cluster-details/edit-cluster/component.spec.ts
  src/app/cluster/cluster-details/gatekeeper-config/gatekeeper-config-dialog/component.ts
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/component.ts
  src/app/settings/admin/opa/constraint-templates/constraint-template-dialog/component.ts
  src/app/settings/admin/opa/default-constraints/default-constraint-dialog/component.ts
  src/app/shared/utils/mla-utils.ts
  src/assets/css/theme/_main.scss
  src/assets/themes/dark.scss
  src/assets/themes/light.scss
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#3862 Add audit policy preset to wizard
  src/app/cluster/cluster-details/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/style.scss
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/cluster/theme.scss
  src/assets/css/theme/_component.scss
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3831 Add custom number stepper input
  cypress/fixtures/datacenters.json
  src/app/backup/list/automatic-backup/add-dialog/template.html
  src/app/cluster/cluster-details/node-list/template.html
  src/app/core/services/node-data/provider/anexia.ts
  src/app/node-data/basic/provider/alibaba/template.html
  src/app/node-data/basic/provider/anexia/component.ts
  src/app/node-data/basic/provider/anexia/template.html
  src/app/node-data/basic/provider/aws/template.html
  src/app/node-data/basic/provider/azure/template.html
  src/app/node-data/basic/provider/gcp/template.html
  src/app/node-data/basic/provider/kubevirt/template.html
  src/app/node-data/basic/provider/openstack/template.html
  src/app/node-data/basic/provider/vsphere/template.html
  src/app/node-data/component.ts
  src/app/node-data/extended/provider/aws/template.html
  src/app/node-data/template.html
  src/app/settings/admin/defaults/template.html
  src/app/shared/components/cluster-from-template/component.ts
  src/app/shared/components/cluster-from-template/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/number-stepper/component.ts
  src/app/shared/components/number-stepper/style.scss
  src/app/shared/components/number-stepper/template.html
  src/app/shared/components/number-stepper/theme.scss
  src/app/shared/module.ts
  src/app/wizard/step/cluster/template.html
  src/assets/css/global/_main.scss
  src/assets/css/material/_main.scss
  src/assets/css/theme/_component.scss
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes

#3878 Update dependencies
  package-lock.json
  package.json
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#3854 Use openstack project auth
  hack/e2e/setup-kubermatic-in-kind.sh
  src/app/core/services/node-data/provider/openstack.ts
  src/app/core/services/wizard/provider/openstack.spec.ts
  src/app/core/services/wizard/provider/openstack.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/openstack/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/openstack/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/preset.ts
  src/app/testing/fake-data/cluster.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/default/component.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3893 Make footer a part of the content and fix styling on admin settings
  src/app/component.ts
  src/app/core/components/footer/style.scss
  src/app/settings/admin/nav/style.scss
  src/app/style.scss
  src/app/template.html
  src/assets/css/_variables.scss
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3908 Allow audit policy preset changes during cluster edit
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-cluster/style.scss
  src/app/cluster/cluster-details/edit-cluster/template.html
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#3910 Hide edit provider settings action for kubeAdm as it is not supported anyways
  src/app/cluster/cluster-details/template.html
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes
