Repository kubermatic/dashboard, pull requests merged in 2021-07, with the labels that each got.

#3485 Redesign kubeadm node manual
  src/app/cluster/cluster-details/machine-deployment-list/style.scss
  src/app/cluster/cluster-details/machine-deployment-list/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3475 Project page improvements
  src/app/project/component.ts
  src/app/project/template.html
  src/assets/css/global/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3486 Shorten imports by using aliases
  src/app/core/services/token.ts
  src/app/core/services/user.spec.ts
  src/app/core/services/wizard/provider/alibaba.ts
  src/app/core/services/wizard/provider/anexia.ts
  src/app/core/services/wizard/provider/gcp.ts
  src/app/core/services/wizard/provider/hetzner.ts
  src/app/core/services/wizard/provider/openstack.ts
  src/app/core/services/wizard/provider/packet.ts
  src/app/core/services/wizard/provider/provider.ts
  src/app/core/services/wizard/steps.ts
  src/app/node-data/basic/provider/component.ts
  src/app/node-data/basic/provider/digitalocean/component.ts
  src/app/node-data/basic/provider/gcp/component.ts
  src/app/node-data/basic/provider/kubevirt/component.ts
  src/app/node-data/basic/provider/packet/component.ts
  src/app/node-data/dialog/component.ts
  src/app/node-data/extended/component.ts
  src/app/node-data/extended/provider/alibaba/component.ts
  src/app/node-data/extended/provider/aws/component.ts
  src/app/node-data/extended/provider/azure/component.ts
  src/app/node-data/extended/provider/digitalocean/component.ts
  src/app/node-data/extended/provider/gcp/component.ts
  src/app/node-data/extended/provider/openstack/component.ts
  src/app/node-data/extended/provider/packet/component.ts
  src/app/project/delete-project/component.ts
  src/app/shared/components/addon-list/edit-addon-dialog/component.ts
  src/app/shared/entity/cluster.spec.ts
  src/app/shared/validators/no-ips-left.validator.spec.ts
  src/app/testing/fake-data/add-node-modal.ts
  src/app/testing/fake-data/app-config.ts
  src/app/testing/fake-data/aws-subnets.ts
  src/app/testing/fake-data/cloud-spec.ts
  src/app/testing/fake-data/cluster-spec.ts
  src/app/testing/fake-data/cluster-with-machine-networks.ts
  src/app/testing/fake-data/cluster.ts
  src/app/testing/fake-data/event.ts
  src/app/testing/fake-data/health.ts
  src/app/testing/fake-data/member.ts
  src/app/testing/fake-data/project.ts
  src/app/testing/fake-data/user-group-config.ts
  src/app/testing/fake-data/version-info.ts
  src/app/testing/fake-data/vsphere.ts
  src/app/wizard/step/base.ts
  src/app/wizard/step/network/component.ts
  src/app/wizard/step/provider-settings/component.ts
  src/app/wizard/step/provider-settings/provider/extended/component.ts
  src/main.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3484 Bump dependencies and fix scss warnings
  package-lock.json
  package.json
  src/app/core/components/navigation/project/style.scss
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#3480 Add support for app credentials to the openstack provider
  src/app/core/services/node-data/provider/openstack.ts
  src/app/core/services/wizard/provider/openstack.ts
  src/app/core/services/wizard/provider/provider.ts
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/template.html
  src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3483 Add icons to buttons
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/template.html
  src/app/cluster/cluster-list/template.html
  src/app/cluster/external-cluster-details/template.html
  src/app/member/template.html
  src/app/project/template.html
  src/app/serviceaccount/template.html
  src/app/settings/admin/template.html
  src/app/settings/user/template.html
  src/app/shared/components/dialog-title/template.html
  src/app/sshkey/template.html
  src/app/wizard/template.html
  src/assets/css/_images.scss
  src/assets/css/material/_theme.scss
  src/assets/images/icons/back.svg
  src/assets/images/icons/close.svg
  src/assets/images/icons/connect.svg
  src/assets/images/icons/external-link.svg
  src/assets/images/icons/share.svg
  src/assets/images/icons/x.svg
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3489 [v2.17] Add support for openstack app credentials
  src/app/core/services/wizard/provider/openstack.ts
  src/app/core/services/wizard/provider/provider.ts
  src/app/node-data/service/provider/openstack.ts
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/template.html
  src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3502 Bump the Dashboard version to v2.17.2
  Makefile
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3488 admin settings for alermanager domain + link to alertmanager ui
  src/app/cluster/cluster-details/alertmanager-config/component.spec.ts
  src/app/cluster/cluster-details/alertmanager-config/component.ts
  src/app/cluster/cluster-details/alertmanager-config/template.html
  src/app/settings/admin/component.spec.ts
  src/app/settings/admin/defaults/template.html
  src/app/shared/entity/settings.ts
  src/app/testing/services/settings-mock.ts
  src/assets/css/material/_main.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3490 Changelog design update
  src/app/core/components/changelog/dialog.ts
  src/app/core/components/changelog/style.scss
  src/app/core/components/changelog/template.html
  src/app/shared/animations/push.ts
  src/app/shared/model/changelog.ts
  src/assets/themes/dark.scss
  src/assets/themes/light.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3491 Add option to restart machine deployments
  src/app/cluster/cluster-details/machine-deployment-details/component.ts
  src/app/cluster/cluster-details/machine-deployment-details/template.html
  src/app/cluster/cluster-details/machine-deployment-list/component.ts
  src/app/cluster/cluster-details/machine-deployment-list/template.html
  src/app/core/services/api.ts
  src/app/core/services/node.ts
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3520 Update dependencies
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3519 Allow only one CIDR for pods and services
  src/app/shared/components/cidr-form/component.ts
  src/app/shared/validators/others.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3527 Fix base64 decoding/encoding
  package-lock.json
  package.json
  src/app/cluster/cluster-details/alertmanager-config/alertmanager-config-dialog/component.ts
  src/app/cluster/cluster-details/rule-groups/rule-group-dialog/component.ts
  src/app/shared/utils/mla-utils.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#3532 fix reset of opa integration checkbox
  src/app/wizard/step/cluster/component.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3537 Use merge when applying cluster network changes to avoid overrides
  src/app/core/services/cluster-spec.ts
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3554 Support external CCM migration
  src/app/cluster/cluster-details/component.ts
  src/app/cluster/cluster-details/template.html
  src/app/core/services/cluster.ts
  src/app/shared/entity/cluster.ts
  src/app/testing/fake-data/cluster-with-machine-networks.ts
  src/app/testing/fake-data/cluster.ts
  src/assets/css/global/_theme.scss
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3563 Remove status indicator from service account view
  src/app/serviceaccount/component.spec.ts
  src/app/serviceaccount/component.ts
  src/app/serviceaccount/template.html
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
