Repository kubermatic/dashboard, pull requests merged in 2021-09, with the labels that each got.

#3646 Disable telemetry in ci
  hack/e2e/setup-kubermatic-in-kind.sh
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3642 Add Grafana link to dashboard
  src/app/cluster/cluster-details/alertmanager-config/template.html
  src/app/cluster/cluster-details/mla/alertmanager-config/alertmanager-config-dialog/component.spec.ts
  src/app/cluster/cluster-details/mla/alertmanager-config/alertmanager-config-dialog/component.ts
  src/app/cluster/cluster-details/mla/alertmanager-config/alertmanager-config-dialog/style.scss
  src/app/cluster/cluster-details/mla/alertmanager-config/alertmanager-config-dialog/template.html
  src/app/cluster/cluster-details/mla/alertmanager-config/component.spec.ts
  src/app/cluster/cluster-details/mla/alertmanager-config/component.ts
  src/app/cluster/cluster-details/mla/alertmanager-config/style.scss
  src/app/cluster/cluster-details/mla/alertmanager-config/template.html
  src/app/cluster/cluster-details/mla/component.spec.ts
  src/app/cluster/cluster-details/mla/component.ts
  src/app/cluster/cluster-details/mla/rule-groups/component.spec.ts
  src/app/cluster/cluster-details/mla/rule-groups/component.ts
  src/app/cluster/cluster-details/mla/rule-groups/rule-group-dialog/component.spec.ts
  src/app/cluster/cluster-details/mla/rule-groups/rule-group-dialog/component.ts
  src/app/cluster/cluster-details/mla/rule-groups/rule-group-dialog/style.scss
  src/app/cluster/cluster-details/mla/rule-groups/rule-group-dialog/template.html
  src/app/cluster/cluster-details/mla/rule-groups/style.scss
  src/app/cluster/cluster-details/mla/rule-groups/template.html
  src/app/cluster/cluster-details/mla/template.html
  src/app/cluster/cluster-details/template.html
  src/app/cluster/module.ts
  src/app/settings/admin/defaults/template.html
  src/app/shared/entity/settings.ts
  src/app/testing/services/settings-mock.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3643 Improve ui for opa default constraints
  src/app/dynamic/enterprise/allowed-registries/style.scss
  src/app/dynamic/enterprise/allowed-registries/template.html
  src/app/settings/admin/nav/template.html
  src/app/settings/admin/opa/constraint-templates/style.scss
  src/app/settings/admin/opa/constraint-templates/template.html
  src/app/settings/admin/opa/default-constraints/style.scss
  src/app/settings/admin/opa/default-constraints/template.html
  src/app/settings/admin/opa/template.html
  src/app/shared/components/tab-card/style.scss
  src/app/shared/components/tab-card/theme.scss
  src/assets/themes/dark.scss
  src/assets/themes/light.scss
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3645 Fix issues in dark mode
  src/app/cluster-template/template.html
  src/app/cluster/cluster-details/constraints/template.html
  src/app/cluster/cluster-details/edit-sshkeys/template.html
  src/app/cluster/cluster-details/gatekeeper-config/template.html
  src/app/cluster/cluster-details/machine-deployment-details/template.html
  src/app/cluster/cluster-details/machine-deployment-list/template.html
  src/app/cluster/cluster-details/mla/alertmanager-config/template.html
  src/app/cluster/cluster-details/mla/rule-groups/template.html
  src/app/cluster/cluster-details/node-list/template.html
  src/app/cluster/cluster-details/rbac/template.html
  src/app/cluster/cluster-list/template.html
  src/app/cluster/external-cluster-details/external-node-list/template.html
  src/app/cluster/external-cluster-details/template.html
  src/app/dynamic/enterprise/allowed-registries/template.html
  src/app/member/template.html
  src/app/project/template.html
  src/app/serviceaccount/template.html
  src/app/serviceaccount/token/add/template.html
  src/app/serviceaccount/token/template.html
  src/app/settings/admin/admins/template.html
  src/app/settings/admin/custom-link-form/template.html
  src/app/settings/admin/dynamic-datacenters/template.html
  src/app/settings/admin/opa/constraint-templates/template.html
  src/app/settings/admin/opa/default-constraints/template.html
  src/app/settings/admin/presets/dialog/template.html
  src/app/settings/admin/presets/edit-dialog/template.html
  src/app/settings/admin/presets/template.html
  src/app/shared/components/addon-list/install-addon-dialog/template.html
  src/app/shared/components/cluster-from-template/template.html
  src/app/shared/components/event-card/template.html
  src/app/shared/components/label-form/template.html
  src/app/shared/components/taint-form/template.html
  src/app/sshkey/template.html
  src/assets/themes/dark.scss
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3649 Avoid setting custom page title when user is not logged in
  src/app/core/services/page-title.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3658 temporary skip provider + opa e2e tests
  cypress/plugins/index.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3657 Add SSH keys for cluster templates
  src/app/shared/components/cluster-from-template/component.ts
  src/app/shared/components/cluster-from-template/template.html
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/save-cluster-template/component.ts
  src/app/shared/components/save-cluster-template/template.html
  src/app/shared/entity/cluster-template.ts
  src/app/wizard/component.ts
  src/app/wizard/step/summary/component.ts
  src/app/wizard/step/summary/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3653 Fix grafana link
  src/app/cluster/cluster-details/mla/alertmanager-config/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3654 Use new cluster version API endpoint
  src/app/core/services/api.ts
  src/app/wizard/step/cluster/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3662 Replace tick icon
  src/assets/css/_images.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3660 Turn off e2e log colors and update job images
  .prow.yaml
  containers/chrome-headless/Dockerfile
  containers/chrome-headless/release.sh
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3661 add option to enable konnectivity on user-cluster
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/cluster/cluster-details/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#3674 Fix Azure cluster creation
  src/app/core/services/node-data/provider/azure.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3670 Stop pushing to quay.io/kubermatic/ui-v2
  Makefile
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3671 Request reports only if metering is enabled
  src/app/dynamic/enterprise/metering/list/component.ts
  src/app/dynamic/enterprise/metering/list/template.html
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3673 Revert "add option to enable konnectivity on user-cluster"
  src/app/cluster/cluster-details/edit-cluster/component.ts
  src/app/cluster/cluster-details/edit-cluster/template.html
  src/app/cluster/cluster-details/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3631 Add automatic backups/snapshots support
  src/app/backup/details/automatic-backup/backups/component.ts
  src/app/backup/details/automatic-backup/backups/template.html
  src/app/backup/details/automatic-backup/component.ts
  src/app/backup/details/automatic-backup/style.scss
  src/app/backup/details/automatic-backup/template.html
  src/app/backup/details/snapshot/component.ts
  src/app/backup/details/snapshot/style.scss
  src/app/backup/details/snapshot/template.html
  src/app/backup/list/automatic-backup/add-dialog/component.ts
  src/app/backup/list/automatic-backup/add-dialog/template.html
  src/app/backup/list/automatic-backup/component.ts
  src/app/backup/list/automatic-backup/style.scss
  src/app/backup/list/automatic-backup/template.html
  src/app/backup/list/component.ts
  src/app/backup/list/restore/component.ts
  src/app/backup/list/restore/style.scss
  src/app/backup/list/restore/template.html
  src/app/backup/list/snapshot/add-dialog/component.ts
  src/app/backup/list/snapshot/add-dialog/template.html
  src/app/backup/list/snapshot/component.ts
  src/app/backup/list/snapshot/delete-dialog/component.ts
  src/app/backup/list/snapshot/delete-dialog/template.html
  src/app/backup/list/snapshot/restore-dialog/component.ts
  src/app/backup/list/snapshot/restore-dialog/style.scss
  src/app/backup/list/snapshot/restore-dialog/template.html
  src/app/backup/list/snapshot/style.scss
  src/app/backup/list/snapshot/template.html
  src/app/backup/list/template.html
  src/app/backup/module.ts
  src/app/backup/routing.ts
  src/app/cluster/cluster-list/component.spec.ts
  src/app/cluster/cluster-list/component.ts
  src/app/cluster/cluster-list/template.html
  src/app/core/components/sidenav/component.spec.ts
  src/app/core/components/sidenav/template.html
  src/app/core/module.ts
  src/app/core/services/backup.ts
  src/app/core/services/cluster.ts
  src/app/node-data/extended/provider/digitalocean/template.html
  src/app/routing.ts
  src/app/shared/components/property/component.ts
  src/app/shared/components/property/template.html
  src/app/shared/entity/backup.ts
  src/app/shared/entity/common.ts
  src/app/shared/model/Config.ts
  src/app/shared/pipes/relativetime.ts
  src/app/shared/utils/health-status/backup-health-status.ts
  src/app/shared/utils/health-status/health-status.ts
  src/app/wizard/template.html
  src/assets/config/userGroupConfig.json
  src/assets/css/_images.scss
  src/assets/css/global/_main.scss
  src/assets/css/global/_theme.scss
  src/assets/css/material/_main.scss
  src/assets/css/material/_theme.scss
  src/assets/images/icons/backups.svg
  src/assets/themes/dark.scss
  src/assets/themes/light.scss
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#3682 Disable comboboxes if preset was selected
  src/app/node-data/extended/provider/digitalocean/template.html
  src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
  src/app/wizard/step/provider-settings/provider/basic/aws/template.html
  src/app/wizard/step/provider-settings/provider/basic/openstack/application/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/application/template.html
  src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/default/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/default/template.html
  src/app/wizard/step/provider-settings/provider/basic/openstack/template.html
  src/app/wizard/step/provider-settings/provider/basic/vsphere/template.html
  src/app/wizard/step/provider-settings/provider/extended/gcp/component.ts
  src/app/wizard/step/provider-settings/provider/extended/gcp/template.html
  src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/application/template.html
  src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/default/template.html
  src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
  src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3680 Fix change version dialog
  src/app/cluster/cluster-details/change-cluster-version/component.ts
  src/app/cluster/cluster-details/change-cluster-version/style.scss
  src/app/cluster/cluster-details/change-cluster-version/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3684 Do not send requests in wizard before Alibaba datacenter is picked
  src/app/core/services/node-data/provider/alibaba.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3693 Add vSphere resource pool to the preset
  src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html
  src/app/shared/entity/preset.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3690 Update backup credentials object
  src/app/settings/admin/bucket-settings/edit-credentials-dialog/component.ts
  src/app/shared/entity/backup.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#3689 Update pre-release procedure
  .github/ISSUE_TEMPLATE/pre-release.md
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3699 Update provider logos
  src/assets/css/_images.scss
  src/assets/images/clouds/azure.svg
  src/assets/images/clouds/bringyourown-dark.svg
  src/assets/images/clouds/bringyourown.svg
  src/assets/images/clouds/fake.png
  src/assets/themes/dark.scss
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#3700 [v2.18] Version bump
  package-lock.json
  package.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3695 Add changelog for v2.18
  src/assets/config/changelog.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3685 Enable provider tests
  cypress/plugins/index.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3709 Expose CNI config in wizard
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#3707 Skip provider tests in community edition and update the images
  .prow.yaml
  containers/chrome-headless/Dockerfile
  containers/chrome-headless/release.sh
  containers/e2e-kind-cypress/Dockerfile
  containers/e2e-kind-cypress/release.sh
  cypress/integration/providers/openstack.spec.ts
  cypress/integration/providers/vsphere.spec.ts
  cypress/integration/stories/admin-settings/administrators.spec.ts
  cypress/integration/stories/machine-deployment.spec.ts
  cypress/plugins/index.ts
  hack/e2e/setup-kubermatic-in-kind.sh
  package.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#3724 Fix labels view
  src/assets/css/material/_main.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3729 Remove changelog
  src/assets/config/changelog.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3726 Remove default endpoint hint
  src/app/settings/admin/bucket-settings/edit-bucket-setting-dialog/component.ts
  src/app/settings/admin/bucket-settings/edit-bucket-setting-dialog/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3723 Change Packet to Equinix Metal
  .github/ISSUE_TEMPLATE/pre-release.md
  cypress/integration/providers/equinix.spec.ts
  cypress/utils/preset.ts
  cypress/utils/provider.ts
  hack/e2e/setup-kubermatic-in-kind.sh
  src/app/cluster/cluster-details/edit-cluster/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/alibaba-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/anexia-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/aws-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/azure-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/digitalocean-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/equinix-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/equinix-provider-settings/component.ts
  src/app/cluster/cluster-details/edit-provider-settings/equinix-provider-settings/template.html
  src/app/cluster/cluster-details/edit-provider-settings/gcp-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/hetzner-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/kubevirt-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/openstack-provider-settings/component.spec.ts
  src/app/cluster/cluster-details/edit-provider-settings/template.html
  src/app/cluster/cluster-details/edit-provider-settings/vsphere-provider-settings/component.spec.ts
  src/app/cluster/module.ts
  src/app/core/services/api.ts
  src/app/core/services/node-data/provider/equinix.ts
  src/app/core/services/node-data/service.ts
  src/app/core/services/wizard/presets.ts
  src/app/core/services/wizard/provider/equinix.ts
  src/app/node-data/basic/provider/equinix/component.ts
  src/app/node-data/basic/provider/equinix/template.html
  src/app/node-data/basic/provider/template.html
  src/app/node-data/extended/provider/equinix/component.ts
  src/app/node-data/extended/provider/equinix/template.html
  src/app/node-data/extended/template.html
  src/app/node-data/module.ts
  src/app/settings/admin/module.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/equinix/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/equinix/template.html
  src/app/settings/admin/presets/dialog/steps/settings/template.html
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.spec.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/datacenter.ts
  src/app/shared/entity/node.ts
  src/app/shared/entity/preset.ts
  src/app/shared/entity/provider/equinix.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/app/testing/fake-data/add-node-modal.ts
  src/app/testing/fake-data/cluster.ts
  src/app/testing/services/api-mock.ts
  src/app/wizard/module.ts
  src/app/wizard/step/provider-settings/provider/basic/equinix/component.ts
  src/app/wizard/step/provider-settings/provider/basic/equinix/template.html
  src/app/wizard/step/provider-settings/provider/basic/template.html
  src/assets/css/_images.scss
  src/assets/images/clouds/equinix.svg
  src/assets/images/clouds/packet.svg
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#3733 [release/v2.18] remove default endpoint hint + make it required (#3726)
  src/app/settings/admin/bucket-settings/edit-bucket-setting-dialog/component.ts
  src/app/settings/admin/bucket-settings/edit-bucket-setting-dialog/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#3722 Update dependencies
  cypress/plugins/index.ts
  package-lock.json
  package.json
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#3741 Display CNI plugin type in cluster details
  src/app/cluster/cluster-details/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes
