Repository kubermatic/dashboard, pull requests merged in 2022-06, with the labels that each got.

#4411 Open dialog api method
  src/app/cluster-template/template.html
  src/app/cluster/details/cluster/share-kubeconfig/component.spec.ts
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/template.html
  src/app/cluster/list/external-cluster/component.ts
  src/app/core/services/cluster.ts
  src/app/settings/admin/dynamic-datacenters/component.ts
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/component.ts
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html
  src/app/shared/components/button/component.ts
  src/app/shared/components/button/template.html
  src/app/shared/components/confirmation-dialog/component.ts
  src/app/shared/components/confirmation-dialog/template.html
  src/app/shared/components/external-cluster-data-dialog/component.ts
  src/app/shared/components/external-cluster-data-dialog/template.html
  src/app/wizard/component.ts
  src/app/wizard/template.html
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4478 Add retention parameter to metering schedule configuration
  package-lock.json
  package.json
  src/app/backup/list/automatic-backup/add-dialog/component.ts
  src/app/backup/list/automatic-backup/add-dialog/template.html
  src/app/dynamic/enterprise/metering/component.ts
  src/app/dynamic/enterprise/metering/schedule-config/add-dialog/component.ts
  src/app/dynamic/enterprise/metering/schedule-config/add-dialog/template.html
  src/app/dynamic/enterprise/metering/schedule-config/component.ts
  src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/component.ts
  src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/template.html
  src/app/dynamic/enterprise/metering/schedule-config/report-list/component.ts
  src/app/dynamic/enterprise/metering/schedule-config/report-list/template.html
  src/app/dynamic/enterprise/metering/schedule-config/template.html
  src/app/dynamic/enterprise/metering/service/metering.ts
  src/app/shared/entity/datacenter.ts
  src/app/shared/validators/cron.validator.ts
  src/app/shared/validators/validators.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4515 4494 Add Rocky Linux OS for Hetzner cloud provider
  src/app/cluster/details/cluster/machine-deployment-details/template.html
  src/app/cluster/details/cluster/node-list/template.html
  src/app/core/services/node.ts
  src/app/node-data/basic/provider/nutanix/component.ts
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/component.ts
  src/app/node-data/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/datacenter.ts
  src/app/shared/entity/node.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/assets/css/_images.scss
  src/assets/images/os/rocky-linux.svg
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4496 Show updated config instead of default values in edit machine deployment dialog
  src/app/node-data/basic/provider/alibaba/component.ts
  src/app/node-data/basic/provider/anexia/component.ts
  src/app/node-data/basic/provider/aws/component.ts
  src/app/node-data/basic/provider/gcp/component.ts
  src/app/node-data/basic/provider/kubevirt/component.ts
  src/app/node-data/basic/provider/openstack/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4542 4529 display multiple internal IPs in node details of machine deployment
  src/app/cluster/details/cluster/node-list/component.ts
  src/app/cluster/details/cluster/node-list/style.scss
  src/app/cluster/details/cluster/node-list/template.html
  src/app/cluster/details/external-cluster/external-node-list/component.ts
  src/app/cluster/details/external-cluster/external-node-list/style.scss
  src/app/cluster/details/external-cluster/external-node-list/template.html
  src/app/shared/entity/node.ts
  src/app/shared/utils/node.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4552 Revert go back button function
  package-lock.json
  src/app/cluster/details/external-cluster/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4567 Configuration updates
  .github/ISSUE_TEMPLATE/pre-release.md
  .github/ISSUE_TEMPLATE/release.md
  .github/dependabot.yml
  .npmrc
  docs/manuals/release.md
  go.mod
  go.sum
  package.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4575 Remove `approved` label for dependabot
  .github/dependabot.yml
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4578 Revert `swagger-ui` version to `4.8.1`
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4594 Split prow jobs and update build image
  .prow/build-image.yaml
  .prow/tests-e2e.yaml
  .prow/tests-unit.yaml
  .prow/verify.yaml
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4588 Pre-select rocky linux while editing machine deployment
  src/app/cluster/details/cluster/machine-deployment-details/template.html
  src/app/cluster/details/cluster/node-list/template.html
  src/app/core/services/node.ts
  src/app/node-data/basic/provider/nutanix/component.ts
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/datacenter.ts
  src/app/shared/entity/node.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/assets/css/_images.scss
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4585 Update 'Open Dashboard' endpoint usage
  src/app/core/services/cluster.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4538 Disallow disabling Konnectivity for Cilium+ebpf
  src/app/cluster/details/cluster/edit-cluster/component.spec.ts
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/cluster/details/cluster/edit-cluster/template.html
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
  src/assets/css/material/_theme.scss
  src/test/data/cluster.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4605 Bump version to 2.19.6
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4610 Bump version to 2.20.4
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4577 External Clusters Machine Deployment Nodes Details Fix
  src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
  src/app/core/services/cluster.spec.ts
  src/app/core/services/cluster.ts
  src/app/shared/types/request-type.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4602 Add an option to specify "Operating System Profile" when creating machine deployments
  src/app/core/services/feature-gate.ts
  src/app/core/services/node.ts
  src/app/node-data/component.ts
  src/app/node-data/template.html
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/machine-deployment.ts
  src/app/shared/model/NodeSpecChange.ts
  src/app/wizard/component.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/summary/component.ts
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4617 Fixing upgrade external cluster
  src/app/cluster/details/shared/version-change-dialog/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4619 kubelet version selector fallback case fix
  src/app/node-data/kubelet-version/component.ts
Labels: size/XS, lgtm, release-note, approved, ok-to-test, dco-signoff: yes

#4613 Remove IPv6 control for DigitalOcean cloud provider
  cypress/fixtures/digitalocean/machinedeployment.json
  cypress/fixtures/digitalocean/machinedeployments.json
  src/app/cluster/details/cluster/node-list/template.html
  src/app/node-data/extended/provider/digitalocean/component.ts
  src/app/node-data/extended/provider/digitalocean/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/node.ts
  src/test/data/node.ts
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4604 Add dual stack network support
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/template.html
  src/app/core/services/cluster.ts
  src/app/shared/components/cidr-form/component.ts
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/number-stepper/component.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/datacenter.ts
  src/app/shared/validators/others.ts
  src/app/shared/validators/validators.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
  src/assets/css/material/_main.scss
Labels: lgtm, release-note, approved, size/XL, dco-signoff: yes

#4614 UI/UX improvement
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/custom/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/custom/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/provider/style.scss
  src/app/shared/components/add-external-cluster-dialog/steps/provider/template.html
  src/app/shared/components/validate-json-or-yaml/component.spec.ts
  src/app/shared/components/validate-json-or-yaml/component.ts
  src/app/shared/components/validate-json-or-yaml/template.html
  src/app/shared/module.ts
  src/app/shared/utils/common.ts
  src/app/wizard/step/provider-datacenter/component.ts
  src/app/wizard/style.scss
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4625 Filter subnets and VPCs when dual-stack network is selected for AWS cloud provider
  src/app/core/services/node-data/provider/aws.ts
  src/app/node-data/basic/provider/aws/component.ts
  src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4632 Fix default values of CIDR mask size controls
  src/app/wizard/step/cluster/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4634 [release/v2.20] Update owners
  OWNERS
  OWNERS_ALIASES
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes
