Repository kubermatic/dashboard, pull requests merged in 2022-05, with the labels that each got.

#4438 Add metering report removal action to the report list component.
  src/app/core/services/settings.ts
  src/app/dynamic/enterprise/metering/schedule-config/report-list/component.spec.ts
  src/app/dynamic/enterprise/metering/schedule-config/report-list/component.ts
  src/app/dynamic/enterprise/metering/schedule-config/report-list/template.html
  src/app/dynamic/enterprise/metering/service/metering.ts
  src/test/services/metering-mock.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4440 Provider logos adjustments
  package-lock.json
  src/app/cluster-template/style.scss
  src/app/cluster/details/cluster/style.scss
  src/app/cluster/list/cluster/style.scss
  src/app/cluster/list/external-cluster/style.scss
  src/app/settings/admin/dynamic-datacenters/style.scss
  src/app/settings/admin/dynamic-datacenters/template.html
  src/app/settings/admin/presets/component.ts
  src/app/settings/admin/presets/edit-dialog/style.scss
  src/app/settings/admin/presets/edit-dialog/template.html
  src/app/settings/admin/presets/style.scss
  src/app/settings/admin/presets/template.html
  src/app/shared/components/add-external-cluster-dialog/steps/cluster/style.scss
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/style.scss
  src/app/shared/components/add-external-cluster-dialog/steps/provider/style.scss
  src/app/shared/components/cluster-summary/style.scss
  src/assets/css/_images.scss
  src/assets/css/_mixins.scss
  src/assets/css/global/_main.scss
  src/assets/css/material/_main.scss
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4451 Update dependencies and adjust styling
  package-lock.json
  package.json
  src/app/backup/details/automatic-backup/component.ts
  src/app/backup/details/automatic-backup/template.html
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/machine-deployment-details/cluster-panel/component.ts
  src/app/cluster/details/cluster/machine-deployment-details/cluster-panel/template.html
  src/app/cluster/details/cluster/template.html
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/template.html
  src/app/core/components/changelog/style.scss
  src/app/core/components/changelog/template.html
  src/app/core/components/sidenav/template.html
  src/app/dynamic/enterprise/metering/schedule-config/report-list/style.scss
  src/app/dynamic/enterprise/metering/schedule-config/report-list/template.html
  src/app/settings/admin/component.ts
  src/app/settings/admin/nav/component.ts
  src/app/settings/admin/nav/style.scss
  src/app/settings/admin/nav/template.html
  src/app/settings/admin/opa/default-constraints/template.html
  src/app/settings/admin/style.scss
  src/app/settings/admin/template.html
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#4475 Konnectivity hint
  src/app/cluster/details/cluster/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4466 Register project overview
  cypress/integration/v2/stories/admin-settings/defaults.spec.ts
  cypress/integration/v2/stories/members.spec.ts
  cypress/integration/v2/stories/service-accounts.spec.ts
  cypress/integration/v2/stories/ssh-keys.spec.ts
  cypress/intercept/clusters.ts
  cypress/pages/v2/clusters/list/page.ts
  cypress/pages/v2/projects/page.ts
  cypress/types/endpoints.ts
  cypress/types/pages.ts
  cypress/types/view.ts
  src/app/core/components/sidenav/component.spec.ts
  src/app/core/components/sidenav/template.html
  src/app/core/services/cluster.ts
  src/app/core/services/project.ts
  src/app/project-overview/clusters-overview/component.ts
  src/app/project-overview/clusters-overview/template.html
  src/app/project-overview/component.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/common.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4430 Introduce tags for vSphere
  src/app/cluster/details/cluster/node-list/component.spec.ts
  src/app/cluster/details/cluster/node-list/component.ts
  src/app/cluster/details/cluster/node-list/template.html
  src/app/core/services/node-data/provider/vsphere.ts
  src/app/core/services/node-data/service.ts
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/dialog/component.ts
  src/app/node-data/extended/provider/vsphere/component.ts
  src/app/node-data/extended/provider/vsphere/template.html
  src/app/node-data/extended/template.html
  src/app/node-data/module.ts
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/label-form/component.ts
  src/app/shared/entity/node.ts
  src/app/shared/utils/common.ts
  src/app/wizard/component.ts
  src/app/wizard/template.html
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4488 Hide MLA section if it is not enabled on seed level
  src/app/cluster/details/cluster/template.html
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#4495 Revert Swagger version to the last one that is working
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4502 Fix Cilium and KubeVirt logos in the dark UI
  src/assets/images/cni/cilium-dark.svg
  src/assets/themes/dark.scss
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4504 Only consider MachineDeployment running if replicas are updated
  src/app/shared/utils/health-status.ts
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#4489 Remove Type any from services
  src/app/cluster/details/cluster/edit-sshkeys/component.ts
  src/app/core/services/addon.ts
  src/app/core/services/backup.ts
  src/app/core/services/cluster-spec.ts
  src/app/core/services/cluster-templates.ts
  src/app/core/services/cluster.ts
  src/app/core/services/datacenter.ts
  src/app/core/services/machine-deployment.ts
  src/app/core/services/member.ts
  src/app/core/services/mla.ts
  src/app/core/services/node.ts
  src/app/core/services/opa.ts
  src/app/core/services/rbac.ts
  src/app/core/services/service-account.ts
  src/app/core/services/settings.ts
  src/app/core/services/ssh-key.ts
  src/app/shared/components/add-cluster-from-template-dialog/component.ts
  src/app/shared/components/cluster-from-template/dialog/component.ts
  src/app/shared/entity/cluster-template.ts
  src/app/shared/entity/rbac.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4512 Add node version manager runtime configuration file
  .nvmrc
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4521 Add nvmrc configuration file to `.gitignore`
  .gitignore
  .nvmrc
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4520 [release/v2.20] Bump version to 2.20.3
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes
