Repository kubermatic/dashboard, pull requests merged in 2022-01, with the labels that each got.

#4010 UI/UX fixes
  cypress/integration/stories/admin-settings/presets.spec.ts
  cypress/pages/service-accounts.po.ts
  src/app/cluster/list/external-cluster/style.scss
  src/app/core/module.ts
  src/app/core/services/wizard/presets.ts
  src/app/serviceaccount/add-serviceaccount/template.html
  src/app/serviceaccount/component.ts
  src/app/serviceaccount/create-dialog/component.spec.ts
  src/app/serviceaccount/create-dialog/component.ts
  src/app/serviceaccount/create-dialog/template.html
  src/app/serviceaccount/edit-dialog/component.spec.ts
  src/app/serviceaccount/edit-dialog/component.ts
  src/app/serviceaccount/edit-dialog/template.html
  src/app/serviceaccount/edit-serviceaccount/template.html
  src/app/serviceaccount/template.html
  src/app/serviceaccount/token/template.html
  src/app/settings/admin/presets/dialog/component.ts
  src/app/settings/admin/presets/dialog/steps/provider/component.ts
  src/app/settings/admin/presets/dialog/steps/service.ts
  src/app/settings/admin/presets/dialog/steps/settings/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/style.scss
  src/app/settings/admin/presets/dialog/steps/settings/template.html
  src/app/settings/admin/presets/dialog/template.html
  src/app/settings/user/template.html
  src/app/shared/components/property/style.scss
  src/app/shared/entity/preset.ts
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes

#3997 Add warning to grafana link if special addons aren't enabled
  src/app/cluster/details/cluster/mla/alertmanager-config/component.spec.ts
  src/app/cluster/details/cluster/mla/alertmanager-config/component.ts
  src/app/cluster/details/cluster/mla/alertmanager-config/style.scss
  src/app/cluster/details/cluster/mla/alertmanager-config/template.html
  src/app/cluster/details/cluster/mla/component.ts
  src/app/cluster/details/cluster/mla/template.html
  src/app/cluster/details/cluster/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4011 Make cluster detail card unfoldable
  src/app/cluster/details/cluster/cluster-secrets/component.spec.ts
  src/app/cluster/details/cluster/cluster-secrets/component.ts
  src/app/cluster/details/cluster/cluster-secrets/template.html
  src/app/cluster/details/cluster/component.spec.ts
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/template.html
  src/app/cluster/details/shared/version-picker/component.spec.ts
  src/app/cluster/module.ts
  src/app/shared/components/expansion-panel/component.spec.ts
  src/app/shared/components/expansion-panel/component.ts
  src/app/shared/components/expansion-panel/style.scss
  src/app/shared/components/expansion-panel/template.html
  src/app/shared/components/property-health/component.spec.ts
  src/app/shared/components/property-health/component.ts
  src/app/shared/components/property-health/template.html
  src/app/shared/entity/health.ts
  src/app/shared/module.ts
  src/app/testing/fake-data/health.ts
  src/assets/css/global/_main.scss
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes

#4014 Do not show updates available badge if there are none
  src/app/cluster/details/shared/version-change-dialog/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4017 Update subscriptions to improve data load
  src/app/cluster/details/external-cluster/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4021 Update pre-release steps
  .github/ISSUE_TEMPLATE/pre-release.md
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4028 Hide external providers in datacenters view
  src/app/settings/admin/dynamic-datacenters/component.ts
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/component.ts
  src/app/settings/admin/presets/component.ts
  src/app/settings/admin/presets/dialog/steps/provider/component.ts
  src/app/settings/admin/presets/dialog/steps/service.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/assets/css/_images.scss
  src/assets/images/clouds/baremetal.png
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4025 Allow editing replica count for external clusters
  src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html
  src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
  src/app/cluster/details/external-cluster/replicas-dialog/component.ts
  src/app/cluster/details/external-cluster/replicas-dialog/template.html
  src/app/cluster/module.ts
  src/app/core/services/cluster.ts
  src/app/shared/entity/external-machine-deployment.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4027 Block non-admin access to admin settings
  src/app/core/module.ts
  src/app/core/services/auth/guard.ts
  src/app/routing.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4034 Fix MD edit
  src/app/core/services/node.ts
  src/app/node-data/component.ts
  src/app/node-data/dialog/component.ts
  src/app/node-data/dialog/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4037 Handle new external cluster statuses and few other improvements
  src/app/cluster/details/cluster/cluster-delete-confirmation/template.html
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/edit-cluster/template.html
  src/app/cluster/details/cluster/machine-deployment-list/component.ts
  src/app/cluster/details/cluster/rbac/add-binding/template.html
  src/app/cluster/details/cluster/template.html
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html
  src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  src/app/cluster/details/external-cluster/external-node-list/component.ts
  src/app/cluster/details/external-cluster/replicas-dialog/component.ts
  src/app/cluster/details/external-cluster/template.html
  src/app/project/edit-project/template.html
  src/app/settings/admin/admins/add-admin-dialog/template.html
  src/app/shared/components/add-project-dialog/template.html
  src/app/shared/entity/external-cluster.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4040 Fix typo
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/aks/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/credentials/provider/eks/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4052 Multiple fixes
  src/app/cluster/details/cluster/machine-deployment-details/style.scss
  src/app/cluster/details/cluster/machine-deployment-details/template.html
  src/app/cluster/details/cluster/mla/alertmanager-config/component.ts
  src/app/cluster/details/cluster/rbac/add-binding/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4054 UI fixes
  src/app/cluster/details/cluster/cluster-delete-confirmation/component.ts
  src/app/cluster/details/cluster/cluster-delete-confirmation/template.html
  src/app/cluster/details/cluster/mla/alertmanager-config/alertmanager-config-dialog/template.html
  src/app/cluster/details/cluster/mla/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4062 Block access to custom external clusters in error state
  src/app/cluster/list/external-cluster/component.ts
  src/app/cluster/list/external-cluster/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4069 Update event icons
  src/app/shared/components/event-card/component.ts
  src/app/shared/components/event-card/template.html
  src/app/shared/components/event-list/component.ts
  src/assets/css/_images.scss
  src/assets/images/icons/warning-event.svg
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4070 Update project statuses
  src/app/core/services/project.ts
  src/app/project/component.ts
  src/app/project/template.html
  src/app/shared/components/initials-circle/component.ts
  src/app/shared/components/property-health/component.ts
  src/app/shared/entity/external-cluster.ts
  src/app/shared/entity/project.ts
  src/app/shared/utils/health-status/backup-health-status.ts
  src/app/shared/utils/health-status/health-status.ts
  src/app/shared/utils/project-utils/project-utils.spec.ts
  src/app/shared/utils/project-utils/project-utils.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4073 Hide SLES if container runtime is containerd and remove RHEL as supported OS for GCP
  src/app/node-data/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4071 Remove unused code
  cypress/pages/clusters.po.ts
  src/app/cluster/details/cluster/mla/alertmanager-config/component.ts
  src/app/core/components/notification-panel/component.ts
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
  src/app/settings/admin/component.ts
  src/app/settings/admin/nav/component.ts
  src/app/shared/utils/admission-plugin-utils/admission-plugin-utils.ts
  src/app/testing/fake-data/node.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4076 Display operating system logos in machine deployment list
  src/app/cluster/details/cluster/machine-deployment-list/component.ts
  src/app/cluster/details/cluster/machine-deployment-list/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4077 Fix styling of disabled checkboxes
  src/assets/css/material/_theme.scss
  src/assets/themes/dark.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4074 ESLint/Jest config update
  jest.config.js
  package-lock.json
  package.json
  src/tsconfig.spec.json
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#4078 Update cluster additional details style
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/style.scss
  src/app/cluster/details/cluster/template.html
  src/app/cluster/details/shared/version-picker/style.scss
  src/app/shared/components/property-boolean/template.html
  src/app/shared/components/property-health/template.html
  src/app/shared/components/property-usage/style.scss
  src/app/shared/components/property-usage/template.html
  src/app/shared/components/property/component.ts
  src/app/shared/components/property/style.scss
  src/app/shared/components/property/template.html
  src/assets/css/global/_main.scss
  src/assets/css/global/_theme.scss
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4086 Update OPA enforcement message
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/cluster/details/cluster/edit-cluster/template.html
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4089 bump version to 2.18.5
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4084 Fix mla tab
  src/app/cluster/details/cluster/mla/component.ts
  src/app/cluster/details/cluster/mla/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4087 Get rid of the NaN warning in the console
  src/app/shared/components/number-stepper/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4080 Add option to set a default destination
  src/app/settings/admin/bucket-settings/destinations/component.ts
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/style.scss
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/template.html
  src/app/settings/admin/bucket-settings/destinations/template.html
  src/app/shared/entity/datacenter.ts
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4090 Fix icon styling
  src/app/settings/admin/bucket-settings/destinations/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4093 release v2.19.0-alpha.9
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4102 release v2.19.0-alpha.10
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4104 Fix undefined error on cluster details
  src/app/cluster/details/cluster/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4108 Fix long event messages causing page to stretch
  src/app/shared/components/event-list/style.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4110 Update provider/ssh keys fields key display
  src/app/cluster/details/cluster/template.html
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/property/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4109 Fix the default image selection in the MD edit dialog
  src/app/node-data/basic/provider/openstack/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4099 Enhance wording + add warnings for default destinations
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/style.scss
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4096 Minor fixes and notification updates
  src/app/backup/list/automatic-backup/add-dialog/component.ts
  src/app/backup/list/automatic-backup/component.ts
  src/app/backup/list/restore/component.ts
  src/app/backup/list/snapshot/add-dialog/component.ts
  src/app/backup/list/snapshot/delete-dialog/component.ts
  src/app/backup/list/snapshot/restore-dialog/component.ts
  src/app/cluster-template/component.ts
  src/app/cluster/details/cluster/add-machine-network/component.ts
  src/app/cluster/details/cluster/cluster-delete-confirmation/component.ts
  src/app/cluster/details/cluster/cni-version/cni-version-dialog/component.ts
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/constraints/component.ts
  src/app/cluster/details/cluster/constraints/constraint-dialog/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-sshkeys/component.ts
  src/app/cluster/details/cluster/gatekeeper-config/component.ts
  src/app/cluster/details/cluster/gatekeeper-config/gatekeeper-config-dialog/component.ts
  src/app/cluster/details/cluster/machine-deployment-details/component.ts
  src/app/cluster/details/cluster/machine-deployment-list/component.ts
  src/app/cluster/details/cluster/mla/alertmanager-config/component.ts
  src/app/cluster/details/cluster/mla/rule-groups/component.ts
  src/app/cluster/details/cluster/node-list/component.ts
  src/app/cluster/details/cluster/rbac/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  src/app/core/services/cluster.ts
  src/app/core/services/node.ts
  src/app/core/services/wizard/presets.ts
  src/app/dynamic/enterprise/allowed-registries/component.ts
  src/app/dynamic/enterprise/metering/config/config-dialog/component.ts
  src/app/dynamic/enterprise/metering/config/credentials-dialog/component.ts
  src/app/member/component.ts
  src/app/serviceaccount/component.ts
  src/app/serviceaccount/token/component.ts
  src/app/settings/admin/admins/add-admin-dialog/component.ts
  src/app/settings/admin/admins/component.ts
  src/app/settings/admin/bucket-settings/destinations/component.ts
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
  src/app/settings/admin/bucket-settings/destinations/edit-credentials-dialog/component.ts
  src/app/settings/admin/opa/constraint-templates/component.ts
  src/app/settings/admin/opa/default-constraints/component.ts
  src/app/settings/admin/presets/component.ts
  src/app/settings/admin/presets/dialog/component.ts
  src/app/shared/components/add-ssh-key-dialog/component.ts
  src/app/shared/components/addon-list/component.ts
  src/app/shared/components/chip/component.ts
  src/app/shared/components/chip/template.html
  src/app/shared/components/cluster-from-template/component.ts
  src/app/shared/components/search-field/component.ts
  src/app/shared/module.ts
  src/app/sshkey/component.ts
  src/app/wizard/component.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4118 Multiple UI/UX improvements
  src/app/backup/list/automatic-backup/add-dialog/template.html
  src/app/backup/list/snapshot/add-dialog/template.html
  src/app/cluster/details/cluster/cluster-delete-confirmation/component.ts
  src/app/cluster/details/cluster/cluster-delete-confirmation/template.html
  src/app/cluster/details/cluster/cni-version/style.scss
  src/app/cluster/details/cluster/cni-version/template.html
  src/app/cluster/details/cluster/cni-version/theme.scss
  src/app/cluster/details/cluster/style.scss
  src/app/cluster/details/cluster/template.html
  src/app/cluster/details/shared/version-change-dialog/component.ts
  src/app/cluster/details/shared/version-change-dialog/style.scss
  src/app/cluster/details/shared/version-picker/style.scss
  src/app/cluster/details/shared/version-picker/template.html
  src/app/cluster/details/shared/version-picker/theme.scss
  src/app/settings/admin/custom-link-form/style.scss
  src/app/settings/admin/presets/template.html
  src/app/shared/components/expansion-panel/style.scss
  src/app/shared/components/expansion-panel/template.html
  src/app/shared/utils/common-utils.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4117 Fixes for Kubevirt machine deployment creation
  cypress/integration/providers/kubevirt.spec.ts
  package-lock.json
  package.json
  src/app/node-data/basic/provider/kubevirt/component.ts
  src/app/node-data/basic/provider/kubevirt/template.html
  src/app/shared/entity/node.ts
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#4120 UI/UX fixes
  src/app/cluster-template/style.scss
  src/app/cluster/list/cluster/style.scss
  src/app/shared/components/cluster-summary/template.html
  src/assets/css/_mixins.scss
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4121 Move update indicator
  src/app/cluster/details/shared/version-picker/style.scss
  src/app/cluster/details/shared/version-picker/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4114 release v2.19.0-alpha.11
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4123 Update event grouping and more information section logic
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/template.html
  src/app/shared/components/event-list/component.ts
  src/app/shared/components/expansion-panel/component.ts
  src/app/shared/components/expansion-panel/template.html
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4098 Bump version to v2.19 and update changelog
  Makefile
  cypress/utils/endpoint.ts
  cypress/utils/mocks.ts
  package-lock.json
  package.json
  src/app/core/components/changelog/theme.scss
  src/assets/config/changelog.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4127 Bump version to v2.19 and update changelog
  Makefile
  cypress/utils/endpoint.ts
  cypress/utils/mocks.ts
  package-lock.json
  package.json
  src/app/core/components/changelog/theme.scss
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4139 Mock e2e tests
  cypress/fixtures/constraint.json
  cypress/fixtures/constraints.json
  cypress/fixtures/constrainttemplate.json
  cypress/fixtures/constrainttemplates.json
  cypress/fixtures/digitalocean/cluster.json
  cypress/fixtures/digitalocean/clusters.json
  cypress/fixtures/gatekeeperconfig.json
  cypress/fixtures/health.json
  cypress/integration/providers/digitalocean.spec.ts
  cypress/integration/stories/admin-settings/administrators.spec.ts
  cypress/integration/stories/admin-settings/cluster-settings.spec.ts
  cypress/integration/stories/admin-settings/custom-links.spec.ts
  cypress/integration/stories/admin-settings/opa-integration.spec.ts
  cypress/integration/stories/opa.spec.ts
  cypress/pages/admin-settings.po.ts
  cypress/plugins/index.ts
  cypress/utils/endpoint.ts
  cypress/utils/mocks.ts
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes

#4141 Fixes and cluster summary redesign
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/list/cluster/component.ts
  src/app/core/components/notification-panel/component.ts
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/components/cluster-summary/style.scss
  src/app/shared/components/cluster-summary/template.html
  src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
  src/assets/css/_images.scss
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes
