Repository kubermatic/dashboard, pull requests merged in 2022-02, with the labels that each got.

#4153 Fix the e2e tests
  cypress/integration/stories/admin-settings/cluster-settings.spec.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4151 Multiple UI fixes
  src/app/backup/details/automatic-backup/backups/template.html
  src/app/backup/list/automatic-backup/template.html
  src/app/backup/list/restore/template.html
  src/app/backup/list/snapshot/template.html
  src/app/cluster-template/template.html
  src/app/cluster/details/cluster/machine-deployment-list/template.html
  src/app/cluster/details/cluster/node-list/template.html
  src/app/cluster/details/cluster/template.html
  src/app/cluster/list/cluster/template.html
  src/app/cluster/list/external-cluster/template.html
  src/app/core/components/help-panel/component.ts
  src/app/core/components/help-panel/style.scss
  src/app/core/components/help-panel/template.html
  src/app/core/components/notification/theme.scss
  src/app/core/module.ts
  src/app/core/services/changelog-manager.ts
  src/app/core/services/changelog.ts
  src/app/dynamic/enterprise/allowed-registries/template.html
  src/app/dynamic/enterprise/metering/list/template.html
  src/app/member/template.html
  src/app/module.ts
  src/app/serviceaccount/template.html
  src/app/serviceaccount/token/template.html
  src/app/settings/admin/accounts/template.html
  src/app/settings/admin/admins/template.html
  src/app/settings/admin/defaults/template.html
  src/app/settings/admin/dynamic-datacenters/template.html
  src/app/settings/admin/opa/default-constraints/template.html
  src/app/settings/admin/presets/dialog/steps/settings/style.scss
  src/app/settings/admin/presets/dialog/steps/settings/template.html
  src/app/settings/admin/presets/template.html
  src/app/sshkey/template.html
  src/assets/css/_images.scss
  src/assets/css/global/_theme.scss
  src/assets/css/material/_theme.scss
  src/assets/images/icons/sparkles.svg
  src/assets/themes/dark.scss
  src/assets/themes/light.scss
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4164 Add option to get kubeconfig for external clusters
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/template.html
  src/app/core/services/cluster.ts
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#4165 Update dependencies
  package-lock.json
  package.json
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#4177 Fix unit test and update headless Chrome image
  .prow.yaml
  containers/chrome-headless/Dockerfile
  containers/chrome-headless/release.sh
  package-lock.json
  package.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4163 Fix ui in edit provider dialog
  src/app/settings/admin/presets/dialog/steps/settings/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/style.scss
  src/app/settings/admin/presets/dialog/steps/settings/template.html
  src/app/settings/admin/presets/dialog/template.html
  src/assets/css/global/_main.scss
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4149 Review and update the notification messages
  src/app/backup/list/automatic-backup/component.ts
  src/app/backup/list/restore/component.ts
  src/app/backup/list/snapshot/delete-dialog/component.ts
  src/app/cluster-template/component.ts
  src/app/cluster/details/cluster/add-machine-network/component.ts
  src/app/cluster/details/cluster/cni-version/cni-version-dialog/component.ts
  src/app/cluster/details/cluster/constraints/component.ts
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/cluster/details/cluster/edit-sshkeys/component.ts
  src/app/cluster/details/cluster/gatekeeper-config/component.ts
  src/app/cluster/details/cluster/machine-deployment-list/component.ts
  src/app/cluster/details/cluster/mla/alertmanager-config/alertmanager-config-dialog/component.ts
  src/app/cluster/details/cluster/mla/alertmanager-config/component.ts
  src/app/cluster/details/cluster/mla/rule-groups/component.ts
  src/app/cluster/details/cluster/mla/rule-groups/rule-group-dialog/component.ts
  src/app/cluster/details/cluster/node-list/component.ts
  src/app/cluster/details/cluster/rbac/add-binding/component.ts
  src/app/cluster/details/cluster/rbac/component.ts
  src/app/cluster/details/cluster/revoke-token/component.ts
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/replicas-dialog/component.ts
  src/app/cluster/details/shared/version-change-dialog/component.ts
  src/app/cluster/list/cluster/component.ts
  src/app/cluster/list/external-cluster/component.ts
  src/app/dynamic/enterprise/allowed-registries/allowed-registry-dialog/component.ts
  src/app/dynamic/enterprise/allowed-registries/component.ts
  src/app/member/add-member/component.ts
  src/app/member/component.ts
  src/app/member/edit-member/component.ts
  src/app/project/component.ts
  src/app/project/edit-project/component.ts
  src/app/serviceaccount/component.spec.ts
  src/app/serviceaccount/component.ts
  src/app/serviceaccount/create-dialog/component.ts
  src/app/serviceaccount/edit-dialog/component.ts
  src/app/serviceaccount/template.html
  src/app/serviceaccount/token/add/component.ts
  src/app/serviceaccount/token/component.ts
  src/app/settings/admin/admins/component.ts
  src/app/settings/admin/bucket-settings/destinations/component.ts
  src/app/settings/admin/component.ts
  src/app/settings/admin/defaults/component.ts
  src/app/settings/admin/dynamic-datacenters/component.ts
  src/app/settings/admin/interface/component.ts
  src/app/settings/admin/opa/constraint-templates/component.ts
  src/app/settings/admin/opa/constraint-templates/constraint-template-dialog/component.ts
  src/app/settings/admin/opa/default-constraints/component.ts
  src/app/settings/admin/opa/default-constraints/default-constraint-dialog/component.ts
  src/app/settings/admin/presets/edit-dialog/component.ts
  src/app/settings/user/component.ts
  src/app/shared/components/add-external-cluster-dialog/component.ts
  src/app/shared/components/add-project-dialog/component.ts
  src/app/shared/entity/backup.ts
  src/app/sshkey/component.ts
  src/app/wizard/component.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4181 Fix AWS wizard
  src/app/core/services/wizard/provider/aws.ts
  src/app/node-data/basic/provider/aws/component.ts
  src/app/shared/entity/provider/aws.ts
  src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
  src/app/wizard/step/provider-settings/provider/basic/aws/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4182 nutanix test
  .gitignore
  cypress/fixtures/datacenters.json
  cypress/fixtures/nutanix/cluster.json
  cypress/fixtures/nutanix/clusters.json
  cypress/fixtures/nutanix/machinedeployment.json
  cypress/fixtures/nutanix/machinedeployments.json
  cypress/fixtures/nutanix/subnets.json
  cypress/fixtures/preset.json
  cypress/integration/providers/nutanix.spec.ts
  cypress/utils/endpoint.ts
  cypress/utils/mocks.ts
  cypress/utils/preset.ts
  cypress/utils/provider.ts
  hack/e2e/fixtures/seed.yaml
  package-lock.json
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes

#4188 [release/v2.18] Bump release version to v2.18.6
  .prow.yaml
  Makefile
  hack/e2e/setup-kubermatic-in-kind.sh
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4191 Add license
  cypress/fixtures/nutanix/cluster.json
  cypress/fixtures/nutanix/clusters.json
  license-checker-config.json
  license-header.txt
  package-lock.json
  package.json
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes

#4206 changing the default OS disk size to 30
  src/app/node-data/basic/provider/azure/component.ts
  src/app/node-data/basic/provider/azure/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4208 [release/v2.18] Bump release version to v2.18.7
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4209 [release/v2.19] Bump release version to v2.19.2
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4216 Fix UI/UX issues
  src/app/settings/admin/defaults/template.html
  src/app/settings/admin/rule-groups/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4192 feat: support for application credentials in OpenStack preset
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/node-data/component.ts
  src/app/settings/admin/presets/dialog/steps/preset/component.ts
  src/app/settings/admin/presets/dialog/steps/preset/template.html
  src/app/settings/admin/presets/dialog/steps/settings/provider/openstack/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/openstack/template.html
  src/app/settings/admin/presets/dialog/steps/settings/style.scss
  src/app/settings/admin/rule-groups/rule-group-dialog/component.ts
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/openstack-credentials/application/component.ts
  src/app/shared/components/openstack-credentials/application/template.html
  src/app/shared/components/openstack-credentials/component.ts
  src/app/shared/components/openstack-credentials/default/component.ts
  src/app/shared/components/openstack-credentials/default/template.html
  src/app/shared/components/openstack-credentials/style.scss
  src/app/shared/components/openstack-credentials/template.html
  src/app/shared/components/openstack-credentials/theme.scss
  src/app/shared/entity/preset.ts
  src/app/shared/module.ts
  src/app/shared/validators/others.ts
  src/app/wizard/module.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/application/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/template.html
  src/assets/css/theme/_component.scss
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#4223 Require spot instance max price
  src/app/node-data/extended/provider/aws/component.ts
  src/app/node-data/extended/provider/aws/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4225 Update preset dialog button labels
  src/app/settings/admin/presets/dialog/component.ts
  src/app/settings/admin/presets/dialog/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes
