Repository kubermatic/dashboard, pull requests merged in 2022-03, with the labels that each got.

#4239 Update backup destinations and etcd backups handling
  src/app/backup/list/automatic-backup/add-dialog/component.ts
  src/app/backup/list/automatic-backup/add-dialog/style.scss
  src/app/backup/list/automatic-backup/add-dialog/template.html
  src/app/backup/list/snapshot/add-dialog/component.ts
  src/app/backup/list/snapshot/add-dialog/style.scss
  src/app/backup/list/snapshot/add-dialog/template.html
  src/app/settings/admin/bucket-settings/component.ts
  src/app/settings/admin/bucket-settings/destinations/component.ts
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/template.html
  src/app/settings/admin/bucket-settings/destinations/template.html
  src/app/settings/admin/bucket-settings/template.html
  src/app/shared/entity/backup.ts
  src/app/shared/entity/datacenter.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4242 Default unset settings returned from PATCH endpoint too
  src/app/core/services/settings.ts
  src/app/core/services/user.ts
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#4228 Fix GCP tag input
  src/app/node-data/extended/provider/gcp/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4246 fixing font weight for Add token Button
  src/app/serviceaccount/token/style.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4248 use title case where needed
  src/app/cluster/list/cluster/template.html
  src/app/shared/components/add-cluster-from-template-dialog/template.html
  src/app/shared/components/add-ssh-key-dialog/template.html
  src/app/wizard/step/cluster/ssh-keys/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4244 Backup destination added to snapshot backup-list
  src/app/backup/details/snapshot/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4260 Fix an issue with continuous polling the azure sizes in the dialog mode
  src/app/core/services/node-data/provider/azure.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4251 Add Nutanix CSI properties
  src/app/settings/admin/presets/dialog/steps/settings/provider/nutanix/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/nutanix/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/number-stepper/component.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/preset.ts
  src/app/wizard/step/provider-settings/provider/basic/nutanix/component.ts
  src/app/wizard/step/provider-settings/provider/basic/nutanix/template.html
  src/app/wizard/step/provider-settings/provider/extended/nutanix/component.ts
  src/app/wizard/step/provider-settings/provider/extended/nutanix/template.html
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4270 Fix the MLA settings
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/entity/datacenter.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
  src/test/data/datacenter.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4255 CCM/CSI info addition
  src/app/cluster/details/cluster/template.html
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#4279 Project improvements
  src/app/core/services/project.ts
  src/app/project/component.ts
  src/app/project/style.scss
  src/app/project/template.html
  src/app/shared/entity/project.ts
  src/test/data/project.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4278 Update the MLA admin settings logic
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/settings/admin/defaults/template.html
  src/app/wizard/step/cluster/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4272 Fix an issue with preset creation when domain is provided
  src/app/shared/entity/preset.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4301 Remove debounce from provider settings form and fix subscription leak
  src/app/cluster/details/cluster/edit-provider-settings/alibaba-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/anexia-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/aws-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/azure-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/digitalocean-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/equinix-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/gcp-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/hetzner-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/kubevirt-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/nutanix-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/openstack-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4286 Update dependencies
  hack/check-licenses.sh
  package-lock.json
  package.json
  src/app/cluster/details/cluster/constraints/violation-details/component.spec.ts
  src/app/cluster/details/cluster/node-list/component.spec.ts
  src/app/cluster/details/cluster/node-list/component.ts
  src/app/cluster/details/cluster/node-list/template.html
  src/app/cluster/details/cluster/rbac/component.spec.ts
  src/app/cluster/list/cluster/component.spec.ts
  src/app/cluster/list/external-cluster/component.spec.ts
  src/app/shared/validators/no-ips-left.validator.spec.ts
  src/app/shared/validators/no-ips-left.validator.ts
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#4281 UI/UX adjustments
  src/app/cluster/details/cluster/machine-deployment-list/style.scss
  src/app/shared/components/event-list/style.scss
  src/app/shared/components/number-stepper/style.scss
  src/app/shared/components/number-stepper/template.html
  src/app/shared/model/NodeProviderConstants.ts
  src/assets/css/global/_main.scss
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4314 Add allowed IP range override support and update the azure os disk size default for RHEL
  src/app/node-data/basic/provider/azure/component.ts
  src/app/node-data/basic/provider/azure/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/openstack-credentials/application/component.ts
  src/app/shared/components/openstack-credentials/component.ts
  src/app/shared/components/openstack-credentials/default/component.ts
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
  src/app/wizard/step/provider-settings/provider/basic/aws/component.ts
  src/app/wizard/step/provider-settings/provider/basic/azure/component.ts
  src/app/wizard/step/provider-settings/provider/basic/gcp/component.ts
  src/app/wizard/step/provider-settings/provider/basic/openstack/component.ts
  src/app/wizard/step/provider-settings/provider/extended/aws/component.ts
  src/app/wizard/step/provider-settings/provider/extended/azure/component.ts
  src/app/wizard/step/provider-settings/provider/extended/gcp/component.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4312 Update changelog for the v2.20 release
  src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4326 Nutanix improvements
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/provider-settings/provider/basic/nutanix/component.ts
  src/app/wizard/step/provider-settings/provider/extended/nutanix/component.ts
  src/app/wizard/step/provider-settings/provider/extended/nutanix/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4329 Bump version to v2.20
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4325 Fix issue with Openstack preset creation
  src/app/settings/admin/presets/dialog/steps/settings/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4327 Make Domain optional when app credentials are used
  src/app/settings/admin/presets/dialog/steps/settings/provider/openstack/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/openstack/template.html
  src/app/shared/components/openstack-credentials/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4215 fixing height for add and edit machine deployment form
  src/app/shared/components/cluster-from-template/content/style.scss
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/components/cluster-summary/style.scss
  src/app/shared/components/cluster-summary/template.html
  src/app/wizard/step/summary/template.html
  src/assets/css/_variables.scss
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4320 ajust clear notification
  src/app/core/components/notification-panel/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4336 Update vSphere logo
  src/assets/css/_images.scss
  src/assets/images/clouds/vsphere-dark.svg
  src/assets/images/clouds/vsphere.png
  src/assets/images/clouds/vsphere.svg
  src/assets/themes/dark.scss
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4335 Styling improvements and dependency update
  .github/ISSUE_TEMPLATE/pre-release.md
  .github/ISSUE_TEMPLATE/release.md
  .github/dependabot.yml
  OWNERS
  docs/manuals/release.md
  package-lock.json
  package.json
  src/app/cluster/details/cluster/node-list/style.scss
  src/app/cluster/details/cluster/node-list/template.html
  src/app/core/module.ts
  src/app/core/services/history.ts
  src/app/core/services/notification.ts
  src/app/core/services/token.ts
  src/app/core/services/wizard/steps.ts
  src/app/shared/components/addon-list/edit-addon-dialog/template.html
  src/app/shared/components/addon-list/install-addon-dialog/template.html
  src/assets/css/global/_main.scss
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#4337 Add warning for invalid SA tokens
  .prow.yaml
  src/app/serviceaccount/token/template.html
  src/app/shared/entity/service-account.ts
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#4347 Update AKS and EKS logos
  src/assets/images/clouds/aks.svg
  src/assets/images/clouds/eks.svg
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4352 Fix Swagger UI
  package-lock.json
  package.json
  src/polyfills.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4353 [release/v2.18] Bump to v2.18.8 version
  Makefile
  hack/e2e/setup-kubermatic-in-kind.sh
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4359 Fix metering sort
  src/app/dynamic/enterprise/metering/list/component.ts
  src/app/dynamic/enterprise/metering/list/template.html
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#4360 Update external cluster statuses
  src/app/shared/entity/external-cluster.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4365 Bump to 2.19.3 version
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4376 [release/v2.19] Bump version to 2.19.4
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4375 [release/v2.18] Bump version to 2.18.9
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4377 [release/v2.20] Bump version to 2.20.1
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4374 support Redirects to external cluster view
  cypress/integration/stories/external-cluster.spec.ts
  cypress/pages/clusters.po.ts
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/list/component.ts
  src/app/cluster/list/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes
