Repository kubermatic/dashboard, pull requests merged in 2022-11, with the labels that each got.

#5125 Add project-scoped endpoints for EKS
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_a_m_i_types_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_a_m_i_types_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_capacity_types_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_capacity_types_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_cluster_roles_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_cluster_roles_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_regions_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_regions_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_security_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_security_groups_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_subnets_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_v_p_cs_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_v_p_cs_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_versions_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_versions_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/validate_project_e_k_s_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/validate_project_e_k_s_credentials_responses.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, kind/api-change, dco-signoff: yes, sig/api, docs/none

#5180 Mark E2E tests as optional in release v2.20
  .prow.yaml
Labels: release-note-none, size/XS, lgtm, approved, kind/failing-test, dco-signoff: yes

#5111 change label and icon for the edit button in edit dialog
  src/app/cluster/details/cluster/constraints/component.ts
  src/app/cluster/details/cluster/constraints/constraint-dialog/component.spec.ts
  src/app/cluster/details/cluster/constraints/constraint-dialog/component.ts
  src/app/cluster/details/cluster/constraints/constraint-dialog/template.html
  src/app/cluster/details/cluster/edit-provider-settings/template.html
  src/app/cluster/details/cluster/gatekeeper-config/component.ts
  src/app/cluster/details/cluster/gatekeeper-config/gatekeeper-config-dialog/component.spec.ts
  src/app/cluster/details/cluster/gatekeeper-config/gatekeeper-config-dialog/component.ts
  src/app/cluster/details/cluster/gatekeeper-config/gatekeeper-config-dialog/template.html
  src/app/dynamic/enterprise/allowed-registries/allowed-registry-dialog/component.ts
  src/app/dynamic/enterprise/allowed-registries/allowed-registry-dialog/template.html
  src/app/dynamic/enterprise/allowed-registries/component.ts
  src/app/dynamic/enterprise/group/edit-group-dialog/template.html
  src/app/dynamic/enterprise/metering/schedule-config/component.spec.ts
  src/app/dynamic/enterprise/metering/schedule-config/component.ts
  src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/template.html
  src/app/dynamic/enterprise/quotas/project-quota-dialog/template.html
  src/app/member/edit-member/template.html
  src/app/serviceaccount/edit-dialog/template.html
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/component.ts
  src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html
  src/app/settings/admin/opa/constraint-templates/component.ts
  src/app/settings/admin/opa/constraint-templates/constraint-template-dialog/component.spec.ts
  src/app/settings/admin/opa/constraint-templates/constraint-template-dialog/component.ts
  src/app/settings/admin/opa/constraint-templates/constraint-template-dialog/template.html
  src/app/settings/admin/opa/default-constraints/component.ts
  src/app/settings/admin/opa/default-constraints/default-constraint-dialog/component.spec.ts
  src/app/settings/admin/opa/default-constraints/default-constraint-dialog/component.ts
  src/app/settings/admin/opa/default-constraints/default-constraint-dialog/template.html
  src/app/settings/admin/presets/dialog/component.ts
  src/app/settings/admin/rule-groups/component.ts
  src/app/settings/admin/rule-groups/rule-group-dialog/component.ts
  src/app/settings/admin/rule-groups/rule-group-dialog/template.html
  src/app/shared/components/addon-list/edit-addon-dialog/template.html
  src/app/shared/components/application-list/edit-application-dialog/template.html
  src/app/shared/types/common.ts
  src/app/shared/utils/common.ts
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5185 add .envrc to gititnore
  .gitignore
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#5154 Add project-scoped endpoints for Nutanix
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/provider/nutanix.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_categories_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_categories_responses.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_category_values_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_category_values_responses.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_clusters_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_clusters_responses.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_projects_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_projects_responses.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_project_nutanix_subnets_responses.go
  pkg/test/e2e/utils/apiclient/client/nutanix/nutanix_client.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, kind/api-change, dco-signoff: yes, sig/api, docs/none

#5188 Upgrade to Go 1.19.3
  .prow/api.yaml
  .prow/verify.yaml
  containers/chrome-headless/Dockerfile
  containers/custom-dashboard/Dockerfile
  hack/gen-api-client.sh
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5186 Add interface option to enable/disable the web terminal
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/template.html
  src/app/settings/admin/interface/component.ts
  src/app/settings/admin/interface/template.html
  src/app/shared/entity/settings.ts
  src/test/services/settings-mock.ts
Labels: kind/feature, size/M, lgtm, release-note, approved, kind/design, dco-signoff: yes, kind/chore, docs/tbd

#5171 Display groups on project overview page
  src/app/dynamic/enterprise/group/module.ts
  src/app/dynamic/enterprise/group/service.ts
  src/app/project-overview/component.ts
  src/app/project-overview/members-overview/component.ts
  src/app/project-overview/members-overview/style.scss
  src/app/project-overview/members-overview/template.html
  src/app/project-overview/template.html
  src/assets/css/_images.scss
  src/assets/images/icons/groups.svg
Labels: kind/feature, size/L, lgtm, release-note, approved, kind/design, dco-signoff: yes, docs/tbd

#5183 KubeVirt UI/UX improvements
  src/app/node-data/basic/provider/kubevirt/component.ts
  src/app/node-data/basic/provider/kubevirt/template.html
  src/app/shared/components/chip-list/template.html
  src/app/shared/validators/others.ts
  src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
  src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5198 Add Support for ExposeStrategy in network defaults
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/networkdefaults/networkdefaults.go
  pkg/handler/v2/networkdefaults/networkdefaults_test.go
  pkg/handler/v2/networkdefaults/networkdefaults_unit_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/models/network_defaults.go
  pkg/validation/cluster.go
Labels: kind/feature, release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5201 Support for OpenStack server groups
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/api/v2/types.go
  pkg/handler/common/provider/openstack.go
  pkg/handler/v1/provider/openstack.go
  pkg/handler/v2/provider/openstack.go
  pkg/handler/v2/routes_v2.go
  pkg/machine/convert.go
  pkg/provider/cloud/openstack/provider.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_server_groups_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_server_groups_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_server_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_server_groups_responses.go
  pkg/test/e2e/utils/apiclient/client/openstack/openstack_client.go
  pkg/test/e2e/utils/apiclient/models/openstack_node_spec.go
  pkg/test/e2e/utils/apiclient/models/openstack_server_group.go
  src/app/core/services/node-data/provider/openstack.ts
  src/app/core/services/provider/openstack.ts
  src/app/core/services/wizard/provider/openstack.ts
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/openstack/template.html
  src/app/shared/entity/node.ts
  src/app/shared/entity/provider/openstack.ts
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, sig/ui, sig/api, docs/none

#5212 Kubernetes v1.25 doesn't support Pod Security Policy
  pkg/handler/v1/admission-plugin/admission_plugin.go
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5199 External Cluster(EKS): Support for assume role
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/api/v2/types.go
  pkg/defaulting/cluster.go
  pkg/defaulting/configuration.go
  pkg/defaulting/seed.go
  pkg/handler/auth/sa.go
  pkg/handler/common/cluster.go
  pkg/handler/common/provider/aws.go
  pkg/handler/common/provider/eks.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v1/cluster/upgrade_test.go
  pkg/handler/v1/node/node_test.go
  pkg/handler/v1/project/project_test.go
  pkg/handler/v1/serviceaccount/token.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/constraint/constraint.go
  pkg/handler/v2/constraint/constraint_test.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/handler/v2/machine/machine_test.go
  pkg/handler/v2/routing.go
  pkg/provider/cloud/eks/provider.go
  pkg/provider/cloud/kubevirt/data_volume.go
  pkg/provider/cloud/nutanix/provider.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/kubernetes/credentials.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/kubernetes/sa_token_test.go
  pkg/provider/kubernetes/util_test.go
  pkg/provider/watcher/types.go
  pkg/resources/cluster/cluster.go
  pkg/serviceaccount/jwt.go
  pkg/serviceaccount/jwt_test.go
  pkg/validation/cluster_test.go
  src/app/core/services/external-cluster.ts
  src/app/shared/components/external-cluster-credentials/provider/eks/component.ts
  src/app/shared/components/external-cluster-credentials/provider/eks/template.html
  src/app/shared/entity/provider/eks.ts
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, sig/ui, sig/api, externalcluster, docs/none

#5208 Fix E2E tests
  cypress/e2e/v2/stories/admin-settings/dynamic-datacenters.spec.ts
  cypress/e2e/v2/stories/service-accounts.spec.ts
  cypress/e2e/v2/stories/ssh-keys.spec.ts
  cypress/pages/v2/clusters/detail/page.ts
  cypress/pages/v2/serviceaccounts/page.ts
  cypress/pages/v2/settings/admin/dynamic-datacenters/page.ts
  cypress/utils/config.ts
  src/app/serviceaccount/token/template.html
Labels: release-note-none, size/M, lgtm, approved, kind/failing-test, dco-signoff: yes, docs/none

#5209 Remove Labels from Table Views
  src/app/cluster/details/cluster/machine-deployment-list/component.ts
  src/app/cluster/details/cluster/machine-deployment-list/template.html
  src/app/cluster/list/cluster/component.ts
  src/app/cluster/list/cluster/template.html
  src/app/cluster/list/external-cluster/component.ts
  src/app/cluster/list/external-cluster/template.html
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes, kind/chore, docs/tbd

#5182 Edit MD Dialog Enhancements
  src/app/node-data/basic/provider/alibaba/component.ts
  src/app/node-data/basic/provider/alibaba/template.html
  src/app/node-data/basic/provider/aws/component.ts
  src/app/node-data/basic/provider/aws/template.html
  src/app/node-data/basic/provider/gcp/component.ts
  src/app/node-data/basic/provider/gcp/template.html
  src/app/node-data/component.ts
  src/app/node-data/dialog/component.ts
  src/app/node-data/dialog/template.html
  src/app/node-data/template.html
  src/assets/css/material/_main.scss
Labels: size/L, lgtm, release-note, approved, kind/design, dco-signoff: yes, docs/none

#5221 KubeVirt switch from flavor to instancetype
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/machine/convert.go
  pkg/resources/machine/common.go
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/tbd

#5224 Move architecture radio button outside `form`
  src/app/node-data/basic/provider/aws/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#5229 Fix for server group defaulting
  src/app/node-data/basic/provider/openstack/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none

#5228 Support for configuring dashboard notification settings
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/ee/metering/report_config_handler_test.go
  pkg/handler/v1/admin/settings_test.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_cluster_roles_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_regions_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_security_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_v_p_c_s_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_cluster_roles_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_regions_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_security_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_project_e_k_s_v_p_cs_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/validate_e_k_s_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/validate_project_e_k_s_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_e_k_s_clusters_parameters.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/e_k_s.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/namespace_spec.go
  pkg/test/e2e/utils/apiclient/models/network_defaults.go
  pkg/test/e2e/utils/apiclient/models/notifications_options.go
  pkg/test/e2e/utils/apiclient/models/setting_spec.go
  src/app/core/interceptors/error-notifications.spec.ts
  src/app/core/interceptors/error-notifications.ts
  src/app/shared/components/event-list/component.spec.ts
  src/app/shared/components/event-list/component.ts
  src/app/shared/entity/settings.ts
Labels: kind/feature, release-note-none, lgtm, approved, size/XL, dco-signoff: yes, sig/api, docs/none

#5193 Update web-terminal Docker image to 0.3
  pkg/handler/websocket/terminal.go
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#4428 Proposal for unit test guideline
  Development.md
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#5237 [release/v2.19] Bump version to v2.19.12
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5238 [release/v2.20] Bump version to v2.20.10
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5239 [release/v2.21] Bump version to v2.21.3
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5072 Support limited data from applications API
  src/app/cluster/details/cluster/template.html
  src/app/core/services/application.ts
  src/app/shared/components/application-list/add-application-dialog/component.ts
  src/app/shared/components/application-list/add-application-dialog/template.html
  src/app/shared/components/application-list/component.ts
  src/app/shared/components/application-list/edit-application-dialog/component.ts
  src/app/shared/components/application-list/edit-application-dialog/template.html
Labels: kind/feature, release-note-none, size/L, lgtm, approved, dco-signoff: yes, docs/none

#5245 Add OpenIDAuthPlugin feature gate to API
  pkg/api/v2/types.go
  pkg/provider/kubernetes/featuregates.go
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, kind/regression, docs/none

#5226 Ignore broken seeds during API requests
  cmd/kubermatic-api/main.go
  pkg/handler/middleware/middleware.go
  pkg/handler/v1/project/project.go
  pkg/handler/v2/preset/preset.go
  pkg/provider/kubernetes/etcdbackupconfig.go
  pkg/provider/kubernetes/etcdrestore.go
Labels: kind/bug, size/M, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none

#5213 Seed overview API endpoint
  cmd/kubermatic-api/swagger.json
  hack/update-swagger.sh
  hack/verify-swagger.sh
  pkg/api/v2/types.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/seedoverview/seedoverview.go
  pkg/handler/v2/seedoverview/seedoverview_test.go
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/tbd

#5246 Add project-scoped API endpoint for Hetzner
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/provider/hetzner.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/hetzner/hetzner_client.go
  pkg/test/e2e/utils/apiclient/client/hetzner/list_project_hetzner_sizes_parameters.go
  pkg/test/e2e/utils/apiclient/client/hetzner/list_project_hetzner_sizes_responses.go
  pkg/test/e2e/utils/apiclient/models/instancetype_matcher.go
  pkg/test/e2e/utils/apiclient/models/preference_matcher.go
Labels: kind/feature, lgtm, release-note, approved, size/XL, kind/api-change, dco-signoff: yes, sig/api, docs/none

#5248 Sync json-server datacenter mock data with cypress fixtures data
  fixtures/db.json
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, kind/failing-test, dco-signoff: yes, docs/none

#5219 Remove vSphere overwrite cloud spec from machine deployment
  pkg/resources/machine/machinedeployment.go
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes, sig/api, docs/none

#5249 Update k8s version defaulting
  .wwhrd.yml
  go.mod
  go.sum
  pkg/defaulting/configuration.go
  pkg/handler/v1/admin/settings_test.go
  pkg/provider/kubernetes/cluster_test.go
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5247 Handle resource not found for missing user
  pkg/handler/v1/user/user.go
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none

#5264 Update trigger conditions for prow jobs
  .prow/api.yaml
  .prow/frontend.yaml
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#5267 Update configuration for E2E prow job
  .prow/frontend.yaml
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#5268 Revert prepare script to install husky dependency
  modules/web/package.json
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none

#5276 Upgrade dependencies to latest version
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#5269 Support to configure expose strategy and allow IP list for API server
  modules/web/.prettierignore
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/cluster/details/cluster/edit-cluster/style.scss
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/shared/components/cluster-summary/component.ts
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/cluster.ts
  modules/web/src/app/shared/functions/get-ip-count.ts
  modules/web/src/app/shared/validators/others.ts
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/style.scss
  modules/web/src/app/wizard/step/cluster/template.html
  modules/web/src/app/wizard/step/summary/component.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5278 Use the same version for the KKP installer as is pinned in go.mod
  hack/ci/setup-kubermatic-in-kind.sh
  hack/lib.sh
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#5279 KubeVirt fix swagger list preferences missing parameter
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/hack/gen-api-client.sh
  modules/api/hack/update-swagger.sh
  modules/api/hack/verify-api-client.sh
  modules/api/hack/verify-import-order.sh
  modules/api/hack/verify-licenses.sh
  modules/api/hack/verify-swagger.sh
  modules/api/pkg/handler/v2/provider/kubevirt.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_preferences_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_ref.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_node_spec.go
Labels: kind/bug, release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5250 Added logic disable "Enable Kubernetes Dashboard" checkbox
  modules/web/src/app/core/services/feature-gate.ts
  modules/web/src/app/settings/admin/interface/component.ts
  modules/web/src/app/settings/admin/interface/template.html
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5280 Updated Seed's overview endpoint
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v1/dc/datacenter.go
  modules/api/pkg/handler/v1/dc/datacenter_test.go
  modules/api/pkg/handler/v2/seedoverview/seedoverview.go
  modules/api/pkg/handler/v2/seedoverview/seedoverview_test.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_ref.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_node_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/seed_overview.go
Labels: kind/bug, release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5282 Remove Nutanix system categories from api response
  modules/api/pkg/machine/convert.go
Labels: kind/cleanup, size/XS, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none

#5291 Fix versioning for dashboard metrics wrapper
  modules/web/Makefile
  modules/web/cmd/dashboard/main.go
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore, docs/none

#5289 Replace flavor with instance type and preference in KubeVirt provider
  modules/web/src/app/cluster/details/cluster/node-list/template.html
  modules/web/src/app/core/services/node-data/provider/kubevirt.ts
  modules/web/src/app/core/services/provider/kubevirt.ts
  modules/web/src/app/core/services/wizard/provider/kubevirt.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/instance-details/component.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/instance-details/style.scss
  modules/web/src/app/node-data/basic/provider/kubevirt/instance-details/template.html
  modules/web/src/app/node-data/basic/provider/kubevirt/style.scss
  modules/web/src/app/node-data/basic/provider/kubevirt/template.html
  modules/web/src/app/node-data/module.ts
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/node.ts
  modules/web/src/app/shared/entity/provider/kubevirt.ts
Labels: kind/feature, lgtm, release-note, approved, size/XL, dco-signoff: yes, docs/tbd

#5294 Display instance type and preference category instead of kind
  modules/web/src/app/cluster/details/cluster/node-list/component.ts
  modules/web/src/app/cluster/details/cluster/node-list/template.html
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
  modules/web/src/app/shared/components/cluster-summary/component.ts
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/provider/kubevirt.ts
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5285 Add Seed UI implementation to display table
  modules/web/src/app/core/services/datacenter.ts
  modules/web/src/app/settings/admin/nav/template.html
  modules/web/src/app/settings/admin/routing.ts
  modules/web/src/app/settings/admin/seed-configurations/clusters-by-datacenter/component.ts
  modules/web/src/app/settings/admin/seed-configurations/clusters-by-datacenter/style.scss
  modules/web/src/app/settings/admin/seed-configurations/clusters-by-datacenter/template.html
  modules/web/src/app/settings/admin/seed-configurations/component.ts
  modules/web/src/app/settings/admin/seed-configurations/module.ts
  modules/web/src/app/settings/admin/seed-configurations/routing.ts
  modules/web/src/app/settings/admin/seed-configurations/seed-configurations-details/component.ts
  modules/web/src/app/settings/admin/seed-configurations/seed-configurations-details/style.scss
  modules/web/src/app/settings/admin/seed-configurations/seed-configurations-details/template.html
  modules/web/src/app/settings/admin/seed-configurations/style.scss
  modules/web/src/app/settings/admin/seed-configurations/template.html
  modules/web/src/app/settings/admin/seed-configurations/types/seed-configurations.ts
  modules/web/src/app/shared/entity/datacenter.ts
  modules/web/src/app/shared/utils/seed-configurations.ts
  modules/web/src/assets/css/_images.scss
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/images/icons/seed.svg
Labels: kind/feature, lgtm, release-note, approved, size/XL, kind/design, dco-signoff: yes, docs/tbd

#5293 Ignore OWNERS files to add license
  modules/web/license-checker-config.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#5298 [release/v2.21] Bump version to 2.21.4
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5301 Mini Quota Follow Up
  modules/web/src/app/cluster/details/cluster/machine-deployment-list/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
Labels: kind/bug, kind/feature, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#5312 Fix: Expose strategy not being set properly
  modules/api/pkg/handler/common/cluster.go
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/wizard/step/cluster/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none

#5320 Fix license checker
  modules/web/license-checker-config.json
  modules/web/license-header.txt
  modules/web/src/app/dynamic/enterprise/LICENSE
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#5318 KubeVirt split csi driver deployment
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v1/admin/settings_test.go
  modules/api/pkg/handler/v2/application_installation/application_installation_test.go
  modules/api/pkg/provider/cloud/kubevirt/provider.go
  modules/api/pkg/provider/kubernetes/credentials.go
  modules/api/pkg/validation/cluster.go
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none

#5321 Use KKP version in links
  modules/web/src/app/cluster/details/cluster/share-kubeconfig/component.ts
  modules/web/src/app/cluster/details/cluster/share-kubeconfig/template.html
  modules/web/src/app/project/component.ts
  modules/web/src/app/project/template.html
  modules/web/src/app/settings/admin/interface/component.ts
  modules/web/src/app/settings/admin/interface/template.html
  modules/web/src/app/settings/user/component.ts
  modules/web/src/app/settings/user/template.html
  modules/web/src/app/shared/components/addon-list/component.ts
  modules/web/src/app/shared/components/addon-list/install-addon-dialog/component.ts
  modules/web/src/app/shared/components/addon-list/install-addon-dialog/template.html
  modules/web/src/app/shared/components/addon-list/template.html
  modules/web/src/app/shared/components/application-list/add-application-dialog/component.ts
  modules/web/src/app/shared/components/application-list/add-application-dialog/template.html
  modules/web/src/app/shared/components/application-list/component.ts
  modules/web/src/app/shared/components/application-list/template.html
  modules/web/src/app/shared/utils/common.ts
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none

#5331 updated default resource filter minCPU from 1 to 2
  modules/api/pkg/handler/v1/admin/settings_test.go
  modules/api/pkg/provider/kubernetes/settings.go
Labels: kind/cleanup, size/XS, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none

#5333 [release/v2.19] Bump version to 2.19.13
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5334 [release/v2.20] Bump version to 2.20.11
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5211 Project sidebar redesign
  modules/web/cypress/e2e/v2/stories/admin-settings/defaults.spec.ts
  modules/web/cypress/e2e/v2/stories/members.spec.ts
  modules/web/cypress/e2e/v2/stories/service-accounts.spec.ts
  modules/web/cypress/e2e/v2/stories/ssh-keys.spec.ts
  modules/web/cypress/pages/v2/clusters/list/page.ts
  modules/web/cypress/pages/v2/members/page.ts
  modules/web/src/app/backup/list/component.ts
  modules/web/src/app/backup/list/template.html
  modules/web/src/app/cluster/details/cluster/machine-deployment-details/cluster-panel/component.ts
  modules/web/src/app/cluster/details/external-cluster/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  modules/web/src/app/cluster/list/component.ts
  modules/web/src/app/cluster/list/external-cluster/component.ts
  modules/web/src/app/cluster/list/template.html
  modules/web/src/app/cluster/routing.ts
  modules/web/src/app/core/components/sidenav/component.spec.ts
  modules/web/src/app/core/components/sidenav/component.ts
  modules/web/src/app/core/components/sidenav/style.scss
  modules/web/src/app/core/components/sidenav/template.html
  modules/web/src/app/core/components/sidenav/theme.scss
  modules/web/src/app/core/services/external-cluster.ts
  modules/web/src/app/core/services/page-title.ts
  modules/web/src/app/dynamic/enterprise/group/template.html
  modules/web/src/app/external-cluster-wizard/component.ts
  modules/web/src/app/member/component.spec.ts
  modules/web/src/app/member/component.ts
  modules/web/src/app/member/template.html
  modules/web/src/app/project-overview/clusters-overview/component.ts
  modules/web/src/app/routing.ts
  modules/web/src/app/settings/admin/nav/theme.scss
  modules/web/src/app/shared/components/add-external-cluster-dialog/component.ts
  modules/web/src/app/shared/components/side-nav-field/component.ts
  modules/web/src/app/shared/components/side-nav-field/style.scss
  modules/web/src/app/shared/components/side-nav-field/template.html
  modules/web/src/app/shared/components/side-nav-field/theme.scss
  modules/web/src/app/shared/entity/common.ts
  modules/web/src/app/shared/module.ts
  modules/web/src/assets/css/material/_main.scss
  modules/web/src/assets/css/theme/_component.scss
Labels: lgtm, release-note, approved, size/XXL, kind/design, dco-signoff: yes, docs/none

#5315 Resource quota calculation
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/ee/resource-quota/handler.go
  modules/api/pkg/ee/resource-quota/handler_test.go
  modules/api/pkg/handler/v2/resource_quota/resourequota.go
  modules/api/pkg/handler/v2/resource_quota/wrappers_ce.go
  modules/api/pkg/handler/v2/resource_quota/wrappers_ee.go
  modules/api/pkg/handler/v2/routes_v2.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, sig/api, docs/tbd

#5317 UI Adjustment and enhancements
  modules/web/src/app/cluster/details/cluster/node-list/template.html
  modules/web/src/app/project-overview/create-resource-panel/template.html
  modules/web/src/app/serviceaccount/component.ts
  modules/web/src/app/serviceaccount/template.html
  modules/web/src/app/settings/admin/bucket-settings/component.ts
  modules/web/src/app/settings/admin/bucket-settings/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/aks/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/alibaba/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/anexia/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/aws/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/azure/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/digitalocean/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/eks/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/equinix/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/gcp/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/gke/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/hetzner/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/kubevirt/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html
  modules/web/src/app/shared/components/editor/component.ts
  modules/web/src/app/shared/components/loader/component.ts
  modules/web/src/app/shared/components/loader/template.html
  modules/web/src/assets/css/_mixins.scss
Labels: release-note-none, size/L, lgtm, approved, docs/none

#5336 KubeVirt cleanup Flavor and instancetype
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/api/v1/types_test.go
  modules/api/pkg/machine/convert.go
  modules/api/pkg/resources/machine/common.go
Labels: kind/cleanup, lgtm, size/S, approved, release-note-action-required, dco-signoff: yes, sig/virtualization, sig/api, docs/provided

#5344 Add swagger and API client verification jobs
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/hack/gen-api-client.sh
  modules/api/hack/verify-api-client.sh
  modules/api/hack/verify-swagger.sh
  modules/api/hack/verify.sh
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/ee/resource-quota/handler.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v2/application_installation/application_installation_test.go
  modules/api/pkg/handler/v2/application_installation/conversion.go
  modules/api/pkg/handler/v2/networkdefaults/networkdefaults.go
  modules/api/pkg/handler/v2/networkdefaults/networkdefaults_unit_test.go
  modules/api/pkg/handler/v2/provider/azure.go
  modules/api/pkg/handler/v2/provider/openstack.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/azure/list_project_azure_availability_zones_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_server_groups_no_credentials_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/calculate_project_resource_quota_update_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/calculate_project_resource_quota_update_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/project_client.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_ref.go
  modules/api/pkg/test/e2e/utils/apiclient/models/cluster_networking_config.go
  modules/api/pkg/test/e2e/utils/apiclient/models/datacenter_spec_v_sphere.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_node_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/resource_quota_update_calculation.go
  modules/api/pkg/test/e2e/utils/apiclient/models/version.go
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, sig/api, kind/chore, docs/none

#5346 New field ClusterName in kubevirt providerconfig
  modules/api/pkg/resources/machine/common.go
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/tbd

#5354 Update developer certificate origin
  CONTRIBUTING.md
  DCO
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#5355 Fix typo in the apiserverallowedIPRanges field
  modules/api/pkg/api/v1/types.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5339 Move header items inside card on all dashboard screens
  modules/web/cypress/e2e/stories/admin-settings/cluster-settings.spec.ts
  modules/web/cypress/e2e/stories/external-cluster.spec.ts
  modules/web/cypress/e2e/v2/stories/admin-settings/defaults.spec.ts
  modules/web/cypress/e2e/v2/stories/admin-settings/dynamic-datacenters.spec.ts
  modules/web/cypress/pages/clusters.po.ts
  modules/web/cypress/pages/v2/clusters/detail/page.ts
  modules/web/src/app/backup/list/automatic-backup/component.ts
  modules/web/src/app/backup/list/automatic-backup/style.scss
  modules/web/src/app/backup/list/automatic-backup/template.html
  modules/web/src/app/backup/list/restore/component.ts
  modules/web/src/app/backup/list/restore/style.scss
  modules/web/src/app/backup/list/restore/template.html
  modules/web/src/app/backup/list/snapshot/component.ts
  modules/web/src/app/backup/list/snapshot/style.scss
  modules/web/src/app/backup/list/snapshot/template.html
  modules/web/src/app/cluster-template/component.ts
  modules/web/src/app/cluster-template/template.html
  modules/web/src/app/cluster/details/cluster/style.scss
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/cluster/details/external-cluster/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
  modules/web/src/app/cluster/details/external-cluster/style.scss
  modules/web/src/app/cluster/details/external-cluster/template.html
  modules/web/src/app/cluster/list/cluster/component.ts
  modules/web/src/app/cluster/list/cluster/template.html
  modules/web/src/app/cluster/list/component.ts
  modules/web/src/app/cluster/list/external-cluster/component.ts
  modules/web/src/app/cluster/list/external-cluster/template.html
  modules/web/src/app/cluster/list/style.scss
  modules/web/src/app/dynamic/enterprise/group/component.ts
  modules/web/src/app/dynamic/enterprise/group/style.scss
  modules/web/src/app/dynamic/enterprise/group/template.html
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
  modules/web/src/app/member/component.ts
  modules/web/src/app/member/style.scss
  modules/web/src/app/member/template.html
  modules/web/src/app/project/component.ts
  modules/web/src/app/routing.ts
  modules/web/src/app/serviceaccount/template.html
  modules/web/src/app/sshkey/template.html
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/global/_theme.scss
Labels: release-note-none, lgtm, approved, size/XL, kind/design, dco-signoff: yes, docs/none

#5358 Display Allowed IP ranges in summary and details page
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, kind/chore, docs/none

#5356 Allow to edit Allowed IP Ranges for apiserver in existing cluster
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/test/data/cluster.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#5353 Add refresh functionality for the web terminal UI
  modules/web/src/app/shared/components/terminal/component.ts
  modules/web/src/app/shared/components/terminal/template.html
  modules/web/src/app/shared/components/terminal/terminal-status-bar/component.ts
  modules/web/src/app/shared/components/terminal/terminal-status-bar/template.html
  modules/web/src/assets/css/_images.scss
  modules/web/src/assets/images/icons/clock.svg
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes, docs/tbd

#5258 Store a MachineDeployment instead of NodeDeployment in the initial-md annotation
  hack/lib.sh
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/common/cluster.go
  modules/api/pkg/handler/common/kubeconfig.go
  modules/api/pkg/handler/common/machine.go
  modules/api/pkg/handler/v2/cluster/serviceaccount_test.go
  modules/api/pkg/handler/v2/cluster_template/cluster_template.go
  modules/api/pkg/resources/machine/machinedeployment.go
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5365 Bump KKP dependency, remove defaulting package
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/defaulting/cluster.go
  modules/api/pkg/defaulting/cluster_test.go
  modules/api/pkg/defaulting/configuration.go
  modules/api/pkg/defaulting/configuration_integration_test.go
  modules/api/pkg/defaulting/configuration_test.go
  modules/api/pkg/defaulting/externalcluster.go.back
  modules/api/pkg/defaulting/images_ce.go
  modules/api/pkg/defaulting/images_ee.go
  modules/api/pkg/defaulting/seed.go
  modules/api/pkg/defaulting/usersshkey.go.back
  modules/api/pkg/defaulting/usersshkey_test.go.back
  modules/api/pkg/handler/common/cluster.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v1/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster_template/cluster_template.go
  modules/api/pkg/handler/v2/cniversion/cniversion.go
  modules/api/pkg/provider/kubernetes/external_cluster.go
  modules/api/pkg/resources/cluster/cluster.go
  modules/api/pkg/validation/cluster.go
  modules/api/pkg/validation/cluster_test.go
Labels: kind/cleanup, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, sig/api, kind/chore, docs/none
