Repository kubermatic/dashboard, pull requests merged in 2022-08, with the labels that each got.

#4754 Handle application `values`
  src/app/shared/components/application-list/add-application-dialog/component.ts
  src/app/shared/components/application-list/edit-application-dialog/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4749 Bump version to 2.20.6
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4755 Fix health check for dashboard
  src/app/cluster/details/cluster/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4748 Bump version to 2.19.8
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4760 Bump version to 2.21.0
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4765 Display Share Kubeconfig button even if OIDC Kubeconfig setting is enabled
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/template.html
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#4767 Remove share kubeconfig button checks from e2e tests
  cypress/integration/v2/stories/admin-settings/defaults.spec.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4764 Fixed quota-widget width on extended view
  src/app/dynamic/enterprise/quotas/quota-widget/style.scss
  src/app/dynamic/enterprise/quotas/quota-widget/template.html
  src/assets/css/global/_main.scss
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4782 Update docs URL to new pattern
  src/app/cluster/details/cluster/share-kubeconfig/template.html
  src/app/settings/admin/interface/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4790 Unified PR template update
  .github/pull_request_template.md
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4781 Bump package versions
  .stylelintrc.yml
  angular.json
  package-lock.json
  package.json
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#4794 Support for Amazon Linux 2
  src/app/cluster/details/cluster/machine-deployment-details/template.html
  src/app/cluster/details/cluster/node-list/template.html
  src/app/core/services/node.ts
  src/app/node-data/component.ts
  src/app/node-data/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/datacenter.ts
  src/app/shared/entity/node.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/assets/css/_images.scss
  src/assets/images/os/amazon-linux-2.svg
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes

#4795 Update OS compatibility matrix
  src/app/node-data/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4796 Add additional header to webserver serving dashboard
  main.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#4799 Filter OperatingSystemProfiles before listing them
  src/app/node-data/component.ts
  src/app/node-data/template.html
  src/app/shared/entity/operating-system-profile.ts
Labels: kind/feature, release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4802 Fix for edit event rate limit
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/cluster/details/cluster/edit-cluster/template.html
  src/app/shared/components/event-rate-limit/component.ts
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes

#4808 Check if plugin is enabled before consuming the event rate limit config
  src/app/cluster/details/cluster/edit-cluster/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4801 Applications UI/UX improvements
  src/app/core/services/application.ts
  src/app/shared/components/addon-list/install-addon-dialog/style.scss
  src/app/shared/components/addon-list/install-addon-dialog/template.html
  src/app/shared/components/addon-list/template.html
  src/app/shared/components/application-list/add-application-dialog/component.ts
  src/app/shared/components/application-list/add-application-dialog/style.scss
  src/app/shared/components/application-list/add-application-dialog/template.html
  src/app/shared/components/application-list/component.ts
  src/app/shared/components/application-list/edit-application-dialog/style.scss
  src/app/shared/components/application-list/edit-application-dialog/template.html
  src/app/shared/components/application-list/style.scss
  src/app/shared/components/application-list/template.html
  src/assets/css/global/_main.scss
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes

#4810 Update KubeVirt logo to mark technology preview
  src/assets/images/clouds/kubevirt-dark.svg
  src/assets/images/clouds/kubevirt.svg
Labels: size/L, lgtm, release-note, approved, kind/design, dco-signoff: yes

#4783 Fix external cluster machine deployment health status icons and status
  src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html
  src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
  src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts
  src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/template.html
  src/app/shared/entity/external-machine-deployment.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4814 UI improvements and fixes
  src/app/backup/list/automatic-backup/template.html
  src/app/backup/list/restore/template.html
  src/app/backup/list/snapshot/template.html
  src/app/cluster/details/cluster/machine-deployment-list/style.scss
  src/app/cluster/details/cluster/machine-deployment-list/template.html
  src/app/cluster/details/cluster/node-list/template.html
  src/app/dynamic/enterprise/metering/schedule-config/template.html
  src/assets/css/material/_theme.scss
  src/assets/css/theme/_main.scss
  src/assets/themes/dark.scss
  src/assets/themes/light.scss
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4813 KubeVirt UI improvements
  src/app/cluster/details/cluster/edit-cluster/template.html
  src/app/node-data/basic/provider/kubevirt/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/kubevirt-pre-allocated-data-volumes/component.ts
  src/app/shared/components/kubevirt-pre-allocated-data-volumes/template.html
  src/app/shared/module.ts
  src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes

#4816 Update KubeVirt docs link
  src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4817 Improve GCP dual stack usability
  src/app/shared/entity/provider/gcp.ts
  src/app/wizard/step/provider-settings/provider/basic/gcp/component.ts
  src/app/wizard/step/provider-settings/provider/extended/gcp/component.ts
  src/app/wizard/step/provider-settings/provider/extended/gcp/template.html
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes

#4822 prepare for kubevirt kubeconfig fixes
  hack/e2e/setup-kubermatic-in-kind.sh
Labels: kind/cleanup, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4831 External cluster bug fixes
  src/app/cluster/details/external-cluster/template.html
  src/app/cluster/list/external-cluster/template.html
  src/app/core/services/external-cluster.ts
  src/app/core/services/external-machine-deployment.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  src/app/shared/entity/provider/aks.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4830 Hide add MD button in custom external cluster details page
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/template.html
  src/app/cluster/list/external-cluster/template.html
Labels: kind/cleanup, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4837 Fix alignment of CPU/Memory usage on cluster details
  src/app/shared/components/property-usage/style.scss
  src/app/shared/components/property-usage/template.html
Labels: size/M, lgtm, release-note, approved, kind/design, dco-signoff: yes

#4840 Fix alignment of project overview details
  src/app/project-overview/template.html
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes

#4800 Change autocomplete to km select
  src/app/cluster/details/cluster/edit-cluster/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/style.scss
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
  src/app/shared/components/select/component.ts
  src/app/shared/components/select/template.html
  src/app/shared/module.ts
Labels: kind/bug, release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4838 External cluster UI improvements and bug fixes
  src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/component.ts
  src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/style.scss
  src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html
  src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts
  src/app/core/services/external-cluster.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
  src/app/project-overview/providers-overview/component.ts
  src/app/shared/components/autocomplete/component.ts
  src/app/shared/components/chip-autocomplete/component.ts
  src/assets/css/global/_main.scss
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4843 Reverse order of fields in backup credentials dialog
  src/app/settings/admin/bucket-settings/destinations/edit-credentials-dialog/template.html
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes

#4844 Rename rockylinux in the correct format
  src/app/cluster/details/cluster/machine-deployment-details/template.html
  src/app/cluster/details/cluster/node-list/template.html
  src/app/core/services/node.ts
  src/app/node-data/basic/provider/nutanix/component.ts
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/vsphere/component.ts
  src/app/node-data/component.ts
  src/app/node-data/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/datacenter.ts
  src/app/shared/entity/node.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/assets/css/_images.scss
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4845 Make KubeVirt affinity settings mutually exclusive
  src/app/node-data/basic/provider/kubevirt/component.ts
Labels: kind/feature, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4848 Fix indefinite quotas API requests
  src/app/core/services/project.ts
  src/app/dynamic/enterprise/quotas/service.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4835 Issues with resource quotas
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/core/services/project.ts
  src/app/dynamic/enterprise/quotas/project-quota-dialog/component.spec.ts
  src/app/dynamic/enterprise/quotas/project-quota-dialog/component.ts
  src/app/dynamic/enterprise/quotas/project-quota-dialog/style.scss
  src/app/dynamic/enterprise/quotas/project-quota-dialog/template.html
  src/app/dynamic/enterprise/quotas/quota-widget/template.html
  src/app/project/edit-project/component.ts
  src/app/shared/components/add-project-dialog/component.ts
  src/app/shared/components/number-stepper/component.ts
  src/app/shared/components/number-stepper/template.html
  src/app/shared/validators/async-label-form.validator.ts
  src/app/shared/validators/async.validators.ts
  src/app/wizard/step/cluster/component.ts
  src/assets/css/global/_main.scss
  src/assets/css/global/_theme.scss
Labels: kind/bug, release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes

#4846 add location list aks eks
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/template.html
  src/app/core/services/external-cluster.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
  src/app/shared/components/external-cluster-credentials/preset/template.html
  src/app/shared/components/external-cluster-credentials/provider/eks/component.ts
  src/app/shared/components/external-cluster-credentials/provider/eks/template.html
  src/app/shared/entity/external-cluster.ts
  src/app/shared/entity/provider/aks.ts
Labels: kind/feature, release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4852 Fix legacy reports table sorting and action buttons
  src/app/dynamic/enterprise/metering/legacy-reports/list/template.html
Labels: kind/cleanup, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4854 Add legacy report prefix to not show raw data csv files
  src/app/dynamic/enterprise/metering/service/metering.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4857 Add technology preview hint for dual-stack networking
  src/app/wizard/step/cluster/template.html
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes

#4861 Update node affinity preset values in node data service
  src/app/node-data/basic/provider/kubevirt/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4856 Update openstack configuration in edit provider dialog
  src/app/cluster/details/cluster/edit-provider-settings/openstack-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/openstack-provider-settings/style.scss
  src/app/cluster/details/cluster/edit-provider-settings/openstack-provider-settings/template.html
  src/app/shared/entity/cluster.ts
Labels: kind/bug, size/L, lgtm, release-note, approved, dco-signoff: yes

#4851 External Cluster EKS/AKS fields update and Error handling
  src/app/core/services/external-cluster.ts
  src/app/core/services/external-machine-deployment.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
  src/app/shared/components/combobox/component.ts
  src/app/shared/components/combobox/template.html
  src/app/shared/entity/provider/eks.ts
Labels: kind/bug, release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes

#4864 Rename title for MD dialog specific to cloud provider term
  src/app/cluster/details/external-cluster/external-cluster-add-machine-deployment/template.html
Labels: priority/low, release-note-none, size/XS, lgtm, approved, kind/design, dco-signoff: yes

#4862 Update applications documentation link
  src/app/shared/components/application-list/add-application-dialog/template.html
  src/app/shared/components/application-list/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4863 Add project `trackBy` function to avoid unnecessary re-rendering of DOM
  src/app/project/component.ts
  src/app/project/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4858 Set default values of selected application in YAML editor
  src/app/shared/components/application-list/add-application-dialog/component.ts
  src/app/shared/entity/application.ts
Labels: kind/feature, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4866 Update delete project quota success message
  src/app/dynamic/enterprise/quotas/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4868 Use flex layout to display project quota details
  src/app/dynamic/enterprise/quotas/quota-widget/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4869 Fix issue to display empty placeholder in case no nodes exists
  src/app/cluster/details/external-cluster/external-node-list/component.ts
  src/app/cluster/details/external-cluster/template.html
Labels: kind/bug, priority/low, lgtm, size/S, release-note, approved, dco-signoff: yes, sig/ui

#4865 Add the custom external cluster logo
  src/app/cluster/details/external-cluster/style.scss
  src/app/cluster/details/external-cluster/template.html
  src/app/cluster/list/external-cluster/template.html
  src/app/shared/entity/external-cluster.ts
  src/assets/css/_images.scss
  src/assets/images/clouds/customkubernetescluster.svg
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4867 Extra space in project tiles with no resource quotas
  src/app/dynamic/enterprise/quotas/module.ts
  src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  src/app/dynamic/enterprise/quotas/quota-widget/style.scss
  src/app/dynamic/enterprise/quotas/quota-widget/template.html
  src/app/dynamic/enterprise/quotas/service.ts
  src/app/project-overview/component.ts
  src/app/project-overview/routing.ts
  src/app/project-overview/template.html
  src/app/project/component.ts
  src/app/project/style.scss
  src/app/project/template.html
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4875 Fixed rendering delay of quota widgets on project cards.
  src/app/project/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4877 Quota UI fixes
  src/app/dynamic/enterprise/quotas/quota-widget/style.scss
  src/app/dynamic/enterprise/quotas/quota-widget/template.html
  src/assets/css/_images.scss
  src/assets/css/global/_main.scss
Labels: kind/bug, kind/cleanup, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4879 Fix issues in km-button migration
  src/app/cluster/details/cluster/mla/alertmanager-config/alertmanager-config-dialog/template.html
  src/app/cluster/details/cluster/mla/rule-groups/rule-group-dialog/template.html
  src/app/cluster/details/cluster/revoke-token/component.ts
  src/app/serviceaccount/edit-dialog/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4881 Parse application values as YAML for patch requests
  src/app/shared/components/application-list/edit-application-dialog/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4883 Dual-stack not allowed on Canal CNI version lower than 3.22
  src/app/wizard/step/cluster/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4884 External Cluster Fixes
  src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html
  src/app/core/services/external-cluster.ts
  src/app/core/services/external-machine-deployment.ts
  src/app/external-cluster-wizard/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
  src/app/external-cluster-wizard/template.html
  src/app/shared/components/external-cluster-credentials/preset/component.ts
  src/app/shared/components/external-cluster-credentials/provider/aks/template.html
  src/app/shared/components/external-cluster-credentials/provider/eks/template.html
  src/app/shared/components/external-cluster-credentials/provider/gke/template.html
  src/app/shared/entity/provider/gke.ts
Labels: kind/bug, kind/cleanup, release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4885 Disabled buttons in project view when user only has view-only permission
  src/app/cluster-template/component.ts
  src/app/cluster-template/template.html
  src/app/project-overview/create-resource-panel/component.ts
  src/app/project-overview/create-resource-panel/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4894 Add resource name validations where applicable
  src/app/dynamic/enterprise/metering/config/config-dialog/component.ts
  src/app/dynamic/enterprise/metering/config/config-dialog/template.html
  src/app/dynamic/enterprise/metering/schedule-config/add-dialog/component.ts
  src/app/dynamic/enterprise/metering/schedule-config/add-dialog/template.html
  src/app/settings/admin/presets/dialog/steps/preset/component.ts
Labels: kind/feature, release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4895 fixed quota widget logic
  src/app/cluster/list/cluster/component.ts
  src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  src/app/dynamic/enterprise/quotas/quota-widget/template.html
  src/app/project-overview/component.ts
  src/app/project-overview/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4897 Replace quota update PATCH with PUT
  src/app/dynamic/enterprise/quotas/service.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4904 Display OIDC groups in user settings
  src/app/settings/user/style.scss
  src/app/settings/user/template.html
  src/app/shared/entity/member.ts
Labels: kind/feature, release-note-none, lgtm, size/S, approved, dco-signoff: yes
