Repository kubermatic/dashboard, pull requests merged in 2022-07, with the labels that each got.

#4651 Check k8s dashboard health
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/template.html
  src/app/shared/entity/health.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4633 [release/v2.20] Show updated config instead of default values in edit machine deployment dialog
  src/app/node-data/basic/provider/alibaba/component.ts
  src/app/node-data/basic/provider/anexia/component.ts
  src/app/node-data/basic/provider/aws/component.ts
  src/app/node-data/basic/provider/gcp/component.ts
  src/app/node-data/basic/provider/openstack/component.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4656 Bump version to 2.20.5
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4661 Add validations for backup destination names in seed
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
  src/app/settings/admin/bucket-settings/destinations/destination-dialog/template.html
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#4657 Delete External Cluster MD
  src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html
  src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
  src/app/core/module.ts
  src/app/core/services/external-machine-deployment.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4641 Add project quotas page to admin settings
  src/app/core/services/settings.ts
  src/app/dynamic/community/quotas/module.ts
  src/app/dynamic/enterprise/quotas/component.spec.ts
  src/app/dynamic/enterprise/quotas/component.ts
  src/app/dynamic/enterprise/quotas/module.ts
  src/app/dynamic/enterprise/quotas/routing.ts
  src/app/dynamic/enterprise/quotas/style.scss
  src/app/dynamic/enterprise/quotas/template.html
  src/app/dynamic/module-registry.ce.ts
  src/app/dynamic/module-registry.ts
  src/app/settings/admin/nav/template.html
  src/app/settings/admin/routing.ts
  src/app/shared/entity/quota.ts
  src/assets/css/_images.scss
  src/assets/images/icons/quota.svg
  src/test/data/quota.ts
  src/test/services/settings-mock.ts
Labels: priority/high, lgtm, release-note, approved, size/XL, dco-signoff: yes, sig/ui

#4677 Fix control bindings and add typings
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4672 Create external cluster GKE
  src/app/core/services/external-cluster.ts
  src/app/external-cluster-wizard/component.ts
  src/app/external-cluster-wizard/module.ts
  src/app/external-cluster-wizard/steps/external-cluster/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
  src/app/external-cluster-wizard/steps/external-cluster/template.html
  src/app/shared/entity/external-cluster.ts
  src/app/shared/entity/provider/gke.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4642 Create External Cluster AKS
  src/app/core/services/external-cluster.ts
  src/app/external-cluster-wizard/component.ts
  src/app/external-cluster-wizard/module.ts
  src/app/external-cluster-wizard/steps/external-cluster/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/style.scss
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
  src/app/external-cluster-wizard/steps/external-cluster/template.html
  src/app/external-cluster-wizard/template.html
  src/app/project-overview/create-resource-panel/component.ts
  src/app/project-overview/create-resource-panel/template.html
  src/app/shared/entity/external-cluster.ts
  src/app/shared/entity/provider/aks.ts
  src/app/shared/types/error-type.ts
Labels: lgtm, release-note, approved, size/XL, dco-signoff: yes

#4682 Add IPv6 subnet ID and IPv6 subnet pool for OpenStack cluster provider
  src/app/core/services/wizard/provider/openstack.ts
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/provider/openstack.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/application/template.html
  src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/default/template.html
  src/app/wizard/step/provider-settings/provider/extended/openstack/shared/types/ip-version.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/shared/types/state.ts
  src/test/data/cluster.ts
Labels: lgtm, release-note, approved, size/XL, dco-signoff: yes

#4697 Bump version to 2.19.7
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4696 Bump version to 2.18.11
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4644 Add support for VMware Cloud Director provider
  src/app/cluster/details/cluster/edit-provider-settings/template.html
  src/app/cluster/details/cluster/edit-provider-settings/vmware-cloud-director-provider-settings/component.spec.ts
  src/app/cluster/details/cluster/edit-provider-settings/vmware-cloud-director-provider-settings/component.ts
  src/app/cluster/details/cluster/edit-provider-settings/vmware-cloud-director-provider-settings/template.html
  src/app/cluster/details/cluster/machine-deployment-details/style.scss
  src/app/cluster/details/cluster/machine-deployment-details/template.html
  src/app/cluster/module.ts
  src/app/core/module.ts
  src/app/core/services/node-data/provider/vmware-cloud-director.ts
  src/app/core/services/node-data/service.ts
  src/app/core/services/provider/vmware-cloud-director.ts
  src/app/core/services/wizard/presets.ts
  src/app/core/services/wizard/provider/vmware-cloud-director.ts
  src/app/node-data/basic/provider/template.html
  src/app/node-data/basic/provider/vmware-cloud-director/component.ts
  src/app/node-data/basic/provider/vmware-cloud-director/template.html
  src/app/node-data/component.ts
  src/app/node-data/module.ts
  src/app/project-overview/providers-overview/component.ts
  src/app/settings/admin/module.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/vmware-cloud-director/component.ts
  src/app/settings/admin/presets/dialog/steps/settings/provider/vmware-cloud-director/template.html
  src/app/settings/admin/presets/dialog/steps/settings/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/machine-networks-new/component.spec.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/entity/datacenter.ts
  src/app/shared/entity/node.ts
  src/app/shared/entity/preset.ts
  src/app/shared/entity/provider/vmware-cloud-director.ts
  src/app/shared/model/NodeProviderConstants.ts
  src/app/wizard/module.ts
  src/app/wizard/step/network/component.spec.ts
  src/app/wizard/step/provider-settings/component.ts
  src/app/wizard/step/provider-settings/provider/basic/template.html
  src/app/wizard/step/provider-settings/provider/basic/vmware-cloud-director/component.ts
  src/app/wizard/step/provider-settings/provider/basic/vmware-cloud-director/template.html
  src/app/wizard/step/provider-settings/provider/extended/template.html
  src/app/wizard/step/provider-settings/provider/extended/vmware-cloud-director/component.ts
  src/app/wizard/step/provider-settings/provider/extended/vmware-cloud-director/template.html
  src/assets/css/_images.scss
  src/assets/images/clouds/vmwareclouddirector.svg
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#4700 Enable OSM by default
  README.md
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/template.html
  src/app/core/services/feature-gate.ts
  src/app/node-data/component.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4701 Temporarily disable OSM by default
  src/app/wizard/step/cluster/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4699 Fix peer dependencies and `full` E2E tests
  .gitignore
  .npmrc
  .prow/build-image.yaml
  .prow/tests-e2e.yaml
  .prow/tests-unit.yaml
  .prow/verify.yaml
  Development.md
  containers/chrome-headless/Dockerfile
  containers/chrome-headless/release.sh
  containers/custom-dashboard/Dockerfile
  go.mod
  go.sum
  hack/e2e/fixtures/seed.yaml
  hack/e2e/run-tests.sh
  hack/e2e/setup-kubermatic-in-kind.sh
  package-lock.json
  package.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes

#4705 Disallow IPVS proxy mode for Cilium CNI
  src/app/wizard/step/cluster/component.ts
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4691 Delete external cluster from the cloud provider
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/component.ts
  src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/style.scss
  src/app/cluster/details/external-cluster/external-cluster-delete-confirmation/template.html
  src/app/cluster/details/external-cluster/template.html
  src/app/cluster/list/external-cluster/component.ts
  src/app/cluster/list/external-cluster/template.html
  src/app/cluster/module.ts
  src/app/core/services/cluster.ts
  src/app/core/services/external-cluster.ts
  src/app/shared/entity/external-cluster.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4710 migrate to yq4
  hack/e2e/run-tests.sh
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4714 fix a bunch of typos
  cypress/integration/stories/admin-settings/custom-links.spec.ts
  cypress/pages/v2/root/page.ts
  cypress/pages/v2/settings/admin/page.ts
  docs/manuals/customizing.md
  docs/proposals/testing.md
  src/app/cluster/details/cluster/gatekeeper-config/component.ts
  src/app/cluster/details/cluster/gatekeeper-config/template.html
  src/app/core/services/node-data/provider/kubevirt.ts
  src/app/dynamic/enterprise/metering/schedule-config/add-dialog/component.ts
  src/app/settings/admin/bucket-settings/destinations/style.scss
  src/app/shared/components/event-rate-limit/component.ts
  src/app/shared/components/property-health/component.ts
  src/app/shared/entity/external-cluster.ts
  src/app/shared/utils/health-status.ts
  src/assets/css/global/_main.scss
  src/assets/css/material/_theme.scss
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4716 Remove delete functionality for imported cluster
  src/app/cluster/details/external-cluster/template.html
  src/app/cluster/list/external-cluster/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4717 Skip polling for machine deployments when cluster is marked for deletion
  src/app/cluster/list/cluster/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4718 Use separate negation pseudo-class selector instead of list arguments
  src/assets/css/global/_main.scss
  src/assets/css/material/_theme.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4706 Replace text inputs with number stepper for project quota dialog
  src/app/dynamic/enterprise/quotas/component.spec.ts
  src/app/dynamic/enterprise/quotas/component.ts
  src/app/dynamic/enterprise/quotas/module.ts
  src/app/dynamic/enterprise/quotas/project-quota-dialog/component.spec.ts
  src/app/dynamic/enterprise/quotas/project-quota-dialog/component.ts
  src/app/dynamic/enterprise/quotas/project-quota-dialog/style.scss
  src/app/dynamic/enterprise/quotas/project-quota-dialog/template.html
  src/app/dynamic/enterprise/quotas/service.ts
  src/app/dynamic/enterprise/quotas/template.html
  src/app/shared/components/number-stepper/component.ts
  src/app/shared/components/number-stepper/template.html
  src/app/shared/entity/quota.ts
  src/assets/css/global/_main.scss
  src/test/data/quota.ts
Labels: priority/high, release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/ui

#4660 Add functionality to update kubelet version of external clusters
  src/app/cluster/details/external-cluster/external-machine-deployment-details/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-details/template.html
  src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
  src/app/cluster/details/external-cluster/replicas-dialog/component.ts
  src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/component.ts
  src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/style.scss
  src/app/cluster/details/external-cluster/update-external-cluster-machine-deployment-dialog/template.html
  src/app/cluster/module.ts
  src/app/core/services/cluster.ts
  src/app/core/services/external-cluster.ts
  src/app/core/services/external-machine-deployment.ts
  src/app/shared/entity/external-machine-deployment.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4720 Configure pod affinity/anti-affinity and node affinity preset settings
  src/app/cluster/details/cluster/node-list/template.html
  src/app/node-data/basic/provider/kubevirt/component.ts
  src/app/node-data/basic/provider/kubevirt/template.html
  src/app/shared/components/chip-list/component.ts
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/node.ts
  src/app/shared/entity/provider/kubevirt.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4704 Add machine deployment for eks
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/external-cluster-add-machine-deployment/component.ts
  src/app/cluster/details/external-cluster/external-cluster-add-machine-deployment/template.html
  src/app/cluster/details/external-cluster/template.html
  src/app/cluster/module.ts
  src/app/core/services/external-cluster.ts
  src/app/core/services/external-machine-deployment.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
  src/app/node-data/dialog/component.ts
  src/app/shared/entity/external-machine-deployment.ts
  src/app/shared/entity/machine-deployment.ts
  src/app/shared/entity/provider/eks.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4713 Add machine deployment for aks
  src/app/cluster/details/external-cluster/external-cluster-add-machine-deployment/template.html
  src/app/core/services/external-cluster.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
  src/app/shared/entity/external-machine-deployment.ts
  src/app/shared/entity/provider/aks.ts
  src/app/shared/validators/others.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4722 Add support for KubeVirt pre-allocated data volumes
  src/app/core/services/cluster-spec.ts
  src/app/node-data/basic/provider/kubevirt/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/module.ts
  src/app/wizard/step/provider-settings/component.ts
  src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
  src/app/wizard/step/provider-settings/provider/extended/kubevirt/style.scss
  src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
  src/app/wizard/step/provider-settings/provider/extended/template.html
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4724 Remove kubevirt specific check in Cluster Spec service
  src/app/core/services/cluster-spec.ts
  src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4725 Use `Gi` unit for pre-allocated data volume disk size
  src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4728 Add regex to allow cluster template name to only contain alphanumeric characters and dashes
  src/app/shared/components/save-cluster-template/component.ts
  src/app/shared/components/save-cluster-template/template.html
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4726 Incorrect number of secondary disks
  src/app/node-data/basic/provider/kubevirt/component.ts
  src/app/shared/components/combobox/component.ts
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#4719 Add machine deployment for gke
  src/app/cluster/details/external-cluster/external-cluster-add-machine-deployment/template.html
  src/app/cluster/details/external-cluster/template.html
  src/app/core/services/external-cluster.ts
  src/app/core/services/external-machine-deployment.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/style.scss
  src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
  src/app/shared/entity/external-machine-deployment.ts
  src/app/shared/entity/provider/gcp.ts
  src/app/shared/validators/others.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4709 Enable OSM by default during cluster creation
  src/app/wizard/step/cluster/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4729 Support for disabling kubernetes-dashboard for user clusters
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/cluster/details/cluster/edit-cluster/template.html
  src/app/cluster/details/cluster/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/cluster/component.ts
  src/app/wizard/step/cluster/template.html
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4727 Hide members and prevent API call when ownership is other than `owner`
  src/app/core/services/project.ts
  src/app/project-overview/component.ts
  src/app/project-overview/members-overview/component.ts
  src/app/project-overview/members-overview/template.html
  src/app/project-overview/template.html
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4733 KubeVirt UI improvements
  src/app/node-data/basic/provider/kubevirt/component.ts
  src/app/node-data/basic/provider/kubevirt/style.scss
  src/app/node-data/basic/provider/kubevirt/template.html
  src/app/wizard/step/provider-settings/provider/basic/kubevirt/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#4681 Extend external cluster specification
  src/app/cluster/details/external-cluster/component.ts
  src/app/cluster/details/external-cluster/template.html
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes

#4734 Disable OIDC kubeconfig if feature gates is disabled
  src/app/core/services/feature-gate.ts
  src/app/settings/admin/interface/component.ts
  src/app/settings/admin/interface/template.html
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#4736 Add mock request for `featuregates` API endpoint
  cypress/fixtures/feature-gates.json
  cypress/utils/endpoint.ts
  cypress/utils/mocks.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4738 Update external provider tile size
  src/app/shared/components/select-external-cluster-provider/style.scss
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4694 Add support for Applications
  cypress/integration/providers/alibaba.spec.ts
  cypress/integration/providers/anexia.spec.ts
  cypress/integration/providers/aws.spec.ts
  cypress/integration/providers/azure.spec.ts
  cypress/integration/providers/digitalocean.spec.ts
  cypress/integration/providers/equinix.spec.ts
  cypress/integration/providers/gcp.spec.ts
  cypress/integration/providers/hetzner.spec.ts
  cypress/integration/providers/kubeadm.spec.ts
  cypress/integration/providers/kubevirt.spec.ts
  cypress/integration/providers/nutanix.spec.ts
  cypress/integration/providers/openstack.spec.ts
  cypress/integration/providers/vsphere.spec.ts
  cypress/pages/v2/wizard/page.ts
  cypress/types/wizard.ts
  cypress/utils/wizard.ts
  src/app/cluster/details/cluster/component.spec.ts
  src/app/cluster/details/cluster/component.ts
  src/app/cluster/details/cluster/style.scss
  src/app/cluster/details/cluster/template.html
  src/app/core/module.ts
  src/app/core/services/application.ts
  src/app/shared/components/application-list/add-application-dialog/component.ts
  src/app/shared/components/application-list/add-application-dialog/style.scss
  src/app/shared/components/application-list/add-application-dialog/template.html
  src/app/shared/components/application-list/add-application-dialog/theme.scss
  src/app/shared/components/application-list/application-method-icon/component.ts
  src/app/shared/components/application-list/application-method-icon/template.html
  src/app/shared/components/application-list/component.ts
  src/app/shared/components/application-list/edit-application-dialog/component.ts
  src/app/shared/components/application-list/edit-application-dialog/style.scss
  src/app/shared/components/application-list/edit-application-dialog/template.html
  src/app/shared/components/application-list/style.scss
  src/app/shared/components/application-list/template.html
  src/app/shared/components/application-list/theme.scss
  src/app/shared/components/cluster-from-template/content/template.html
  src/app/shared/components/cluster-summary/component.ts
  src/app/shared/components/cluster-summary/style.scss
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/components/save-cluster-template/component.ts
  src/app/shared/components/validate-json-or-yaml/component.ts
  src/app/shared/entity/application.ts
  src/app/shared/entity/cluster-template.ts
  src/app/shared/entity/cluster.ts
  src/app/shared/module.ts
  src/app/wizard/component.ts
  src/app/wizard/config.ts
  src/app/wizard/module.ts
  src/app/wizard/step/applications/component.ts
  src/app/wizard/step/applications/template.html
  src/app/wizard/step/summary/component.ts
  src/app/wizard/step/summary/template.html
  src/app/wizard/template.html
  src/assets/css/_images.scss
  src/assets/css/theme/_component.scss
  src/assets/images/icons/application.svg
  src/assets/images/icons/git.svg
  src/assets/images/icons/helm.svg
  src/assets/images/icons/namespace.svg
  src/test/services/application-mock.ts
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#4739 List custom operating system profiles
  src/app/cluster/details/cluster/edit-cluster/component.ts
  src/app/cluster/details/cluster/edit-cluster/template.html
  src/app/cluster/details/cluster/template.html
  src/app/core/module.ts
  src/app/core/services/operating-system-manager.ts
  src/app/node-data/basic/provider/kubevirt/template.html
  src/app/node-data/component.ts
  src/app/node-data/template.html
  src/app/settings/admin/interface/template.html
  src/app/shared/components/application-list/template.html
  src/app/shared/entity/operating-system-profile.ts
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes
