Repository kubermatic/dashboard, pull requests merged in 2022-04, with the labels that each got.

#4381 Parameters extended for bug report
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4384 use OWNERS_ALIASES to keep team automatically in-sync
  OWNERS
  OWNERS_ALIASES
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4363 Disable buttons during API calls
  package.json
  src/app/backup/list/restore/template.html
  src/app/backup/list/snapshot/delete-dialog/component.ts
  src/app/backup/list/snapshot/delete-dialog/template.html
  src/app/cluster-template/template.html
  src/app/cluster/details/cluster/cluster-delete-confirmation/component.spec.ts
  src/app/cluster/details/cluster/cluster-delete-confirmation/component.ts
  src/app/cluster/details/cluster/cluster-delete-confirmation/template.html
  src/app/core/components/help-panel/component.ts
  src/app/member/add-member/component.spec.ts
  src/app/member/add-member/component.ts
  src/app/member/add-member/template.html
  src/app/serviceaccount/create-dialog/component.spec.ts
  src/app/serviceaccount/create-dialog/component.ts
  src/app/serviceaccount/create-dialog/template.html
  src/app/settings/admin/presets/dialog/component.ts
  src/app/settings/admin/presets/dialog/template.html
  src/app/shared/components/add-cluster-from-template-dialog/component.ts
  src/app/shared/components/add-cluster-from-template-dialog/template.html
  src/app/shared/components/add-external-cluster-dialog/component.ts
  src/app/shared/components/add-external-cluster-dialog/steps/service.ts
  src/app/shared/components/add-external-cluster-dialog/template.html
  src/app/shared/components/add-project-dialog/component.spec.ts
  src/app/shared/components/add-project-dialog/component.ts
  src/app/shared/components/add-project-dialog/template.html
  src/app/shared/components/add-ssh-key-dialog/component.spec.ts
  src/app/shared/components/add-ssh-key-dialog/component.ts
  src/app/shared/components/add-ssh-key-dialog/template.html
  src/app/shared/components/button/component.ts
  src/app/shared/components/button/style.scss
  src/app/shared/components/button/template.html
  src/app/shared/components/cluster-from-template/dialog/component.ts
  src/app/shared/components/cluster-from-template/dialog/template.html
  src/app/shared/module.ts
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes

#4370 Add autofocus to dialog where needed
  src/app/member/add-member/template.html
  src/app/serviceaccount/create-dialog/template.html
  src/app/shared/components/add-project-dialog/template.html
  src/app/shared/components/add-ssh-key-dialog/template.html
  src/app/shared/directives/autofocus/directive.ts
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4392 fix installation in e2e tests
  hack/e2e/setup-kubermatic-in-kind.sh
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4390 Rewrite SSH Keys e2e test
  cypress/integration/providers/alibaba.spec.ts
  cypress/integration/providers/anexia.spec.ts
  cypress/integration/providers/aws.spec.ts
  cypress/integration/providers/azure.spec.ts
  cypress/integration/providers/digitalocean.spec.ts
  cypress/integration/providers/equinix.spec.ts
  cypress/integration/providers/gcp.spec.ts
  cypress/integration/providers/hetzner.spec.ts
  cypress/integration/providers/kubeadm.spec.ts
  cypress/integration/providers/kubevirt.spec.ts
  cypress/integration/providers/nutanix.spec.ts
  cypress/integration/providers/openstack.spec.ts
  cypress/integration/providers/vsphere.spec.ts
  cypress/integration/stories/admin-settings/cluster-settings.spec.ts
  cypress/integration/stories/admin-settings/dynamic-datacenters.spec.ts
  cypress/integration/stories/admin-settings/machine-deployment-replicas.spec.ts
  cypress/integration/stories/admin-settings/opa-integration.spec.ts
  cypress/integration/stories/admin-settings/presets.spec.ts
  cypress/integration/stories/admin-settings/resource-quota.spec.ts
  cypress/integration/stories/cluster-templates.spec.ts
  cypress/integration/stories/opa.spec.ts
  cypress/integration/stories/ssh-keys.spec.ts
  cypress/integration/v2/stories/edition.spec.ts
  cypress/integration/v2/stories/members.spec.ts
  cypress/integration/v2/stories/service-accounts.spec.ts
  cypress/integration/v2/stories/ssh-keys.spec.ts
  cypress/pages/v2/clusters/detail/page.ts
  cypress/pages/v2/clusters/detail/strategy/factory.ts
  cypress/pages/v2/clusters/detail/strategy/mocked.ts
  cypress/pages/v2/clusters/detail/strategy/types.ts
  cypress/pages/v2/clusters/list/page.ts
  cypress/pages/v2/clusters/list/strategy/factory.ts
  cypress/pages/v2/clusters/list/strategy/mocked.ts
  cypress/pages/v2/clusters/list/strategy/types.ts
  cypress/pages/v2/clusters/proxy.ts
  cypress/pages/v2/pages.ts
  cypress/pages/v2/projects/page.ts
  cypress/pages/v2/root/page.ts
  cypress/pages/v2/root/strategy/mocked.ts
  cypress/pages/v2/serviceaccounts/page.ts
  cypress/pages/v2/sshkeys/page.ts
  cypress/pages/v2/sshkeys/strategy/factory.ts
  cypress/pages/v2/sshkeys/strategy/mocked.ts
  cypress/pages/v2/sshkeys/strategy/types.ts
  cypress/pages/v2/types.ts
  cypress/pages/v2/wizard/page.ts
  cypress/pages/v2/wizard/strategy/factory.ts
  cypress/pages/v2/wizard/strategy/mocked.ts
  cypress/pages/v2/wizard/strategy/types.ts
  cypress/plugins/index.ts
  cypress/utils/mocks.ts
  cypress/utils/provider.ts
  fixtures/db.json
  fixtures/routes.json
  hack/e2e/fixtures/seed.yaml
  hack/e2e/setup-kubermatic-in-kind.sh
  package.json
  src/app/cluster/details/cluster/edit-sshkeys/template.html
  src/app/core/services/datacenter.ts
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#4421 Bump version to 2.20.2
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4422 update Go dependencies
  go.mod
  go.sum
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes

#4420 Bump version to 2.19.5
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4419 Bump version to 2.18.10
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#4426 Fix alertmanager config edit
  src/app/cluster/details/cluster/mla/alertmanager-config/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4412 Extend presets view for stats
  src/app/core/services/wizard/presets.ts
  src/app/settings/admin/presets/component.ts
  src/app/settings/admin/presets/template.html
  src/app/shared/entity/preset.ts
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes

#4431 Fix KubeVirt wizard
  src/app/node-data/basic/provider/kubevirt/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#4434 Fix KubeVirt secondary disks wizard
  src/app/node-data/basic/provider/kubevirt/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes
