Repository kubermatic/dashboard, pull requests merged in 2023-05, with the labels that each got.

#5933 Hide the show advanced settings option
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/node-data/template.html
  modules/web/src/app/shared/model/NodeProviderConstants.ts
Labels: kind/bug, release-note-none, lgtm, approved, dco-signoff: yes, sig/ui, docs/none

#5934 Credentials configuration for KubeOne clusters on Hetzner and Digital Ocean
  modules/api/pkg/handler/v2/external_cluster/kubeone.go
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5827 Add support to import digitalocean kubeone cluster
  modules/web/src/app/kubeone-wizard/module.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/digitalocean/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/digitalocean/template.html
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
  modules/web/src/app/kubeone-wizard/steps/provider/component.ts
  modules/web/src/app/kubeone-wizard/steps/summary/template.html
  modules/web/src/app/shared/entity/kubeone-cluster.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5830 Add support to import hetzner kubeone cluster
  modules/web/src/app/kubeone-wizard/module.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/hetzner/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/hetzner/template.html
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
  modules/web/src/app/kubeone-wizard/steps/provider/component.ts
  modules/web/src/app/kubeone-wizard/steps/summary/template.html
  modules/web/src/app/shared/entity/kubeone-cluster.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5936 Span applications table to full width
  modules/web/src/app/shared/components/application-list/style.scss
  modules/web/src/app/shared/components/application-list/template.html
Labels: release-note-none, size/XS, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5937 Add secondary color to form field required indicator
  modules/web/src/assets/css/material/_theme.scss
Labels: size/XS, lgtm, release-note, approved, kind/design, dco-signoff: yes, docs/none

#5941 Fix recreate nodes warning on edit MD dialog
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
  modules/web/src/app/node-data/component.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none

#5942 Add external link icon
  modules/web/src/app/backup/list/automatic-backup/add-dialog/template.html
  modules/web/src/app/backup/list/snapshot/add-dialog/template.html
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/aws-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/machine-deployment-list/template.html
  modules/web/src/app/cluster/details/cluster/mla/alertmanager-config/template.html
  modules/web/src/app/cluster/details/cluster/share-kubeconfig/template.html
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/cluster/details/shared/version-change-dialog/template.html
  modules/web/src/app/dynamic/enterprise/metering/schedule-config/add-dialog/template.html
  modules/web/src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/template.html
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/aks/template.html
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
  modules/web/src/app/project/template.html
  modules/web/src/app/settings/admin/defaults/template.html
  modules/web/src/app/settings/user/template.html
  modules/web/src/app/shared/components/addon-list/install-addon-dialog/template.html
  modules/web/src/app/shared/components/addon-list/template.html
  modules/web/src/app/shared/components/application-list/add-application-dialog/template.html
  modules/web/src/app/shared/components/application-list/template.html
  modules/web/src/app/shared/components/external-cluster-credentials/provider/aks/template.html
  modules/web/src/app/shared/components/external-cluster-credentials/provider/eks/template.html
  modules/web/src/app/wizard/step/cluster/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/aws/template.html
  modules/web/src/assets/css/_images.scss
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/global/_theme.scss
  modules/web/src/assets/css/material/_main.scss
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5943 Use version as query param to cache bust theme styles
  modules/web/src/app/component.ts
  modules/web/src/app/dynamic/enterprise/theming/services/manager.ts
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes, docs/none

#5951 Add support to import openstack kubeone cluster
  modules/api/pkg/handler/v2/external_cluster/kubeone.go
  modules/web/src/app/kubeone-wizard/module.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/openstack/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/openstack/template.html
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
  modules/web/src/app/kubeone-wizard/steps/provider/component.ts
  modules/web/src/app/kubeone-wizard/steps/summary/template.html
  modules/web/src/app/shared/entity/kubeone-cluster.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, sig/ui, sig/api, docs/none

#5953 Fix vertical space between label and value for km-property
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/wizard/step/cluster/template.html
  modules/web/src/assets/css/global/_main.scss
Labels: release-note-none, size/XS, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5954 Pagination support and UI fixes
  modules/web/src/app/backup/details/automatic-backup/backups/template.html
  modules/web/src/app/backup/details/automatic-backup/template.html
  modules/web/src/app/backup/list/automatic-backup/template.html
  modules/web/src/app/backup/list/restore/template.html
  modules/web/src/app/backup/list/snapshot/template.html
  modules/web/src/app/cluster-template/template.html
  modules/web/src/app/cluster/details/cluster/constraints/template.html
  modules/web/src/app/cluster/details/cluster/constraints/violation-details/component.spec.ts
  modules/web/src/app/cluster/details/cluster/constraints/violation-details/template.html
  modules/web/src/app/cluster/details/cluster/machine-deployment-list/template.html
  modules/web/src/app/cluster/details/cluster/mla/rule-groups/template.html
  modules/web/src/app/cluster/details/cluster/node-list/template.html
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
  modules/web/src/app/cluster/details/external-cluster/external-node-list/template.html
  modules/web/src/app/cluster/details/kubeone/machine-deployment-list/template.html
  modules/web/src/app/cluster/list/cluster/template.html
  modules/web/src/app/cluster/list/external-cluster/template.html
  modules/web/src/app/cluster/list/kubeone/template.html
  modules/web/src/app/dynamic/enterprise/allowed-registries/template.html
  modules/web/src/app/dynamic/enterprise/group/template.html
  modules/web/src/app/dynamic/enterprise/metering/schedule-config/report-list/template.html
  modules/web/src/app/dynamic/enterprise/quotas/template.html
  modules/web/src/app/member/template.html
  modules/web/src/app/project/template.html
  modules/web/src/app/serviceaccount/template.html
  modules/web/src/app/settings/admin/accounts/template.html
  modules/web/src/app/settings/admin/admins/template.html
  modules/web/src/app/settings/admin/bucket-settings/template.html
  modules/web/src/app/settings/admin/dynamic-datacenters/template.html
  modules/web/src/app/settings/admin/opa/constraint-templates/template.html
  modules/web/src/app/settings/admin/opa/default-constraints/template.html
  modules/web/src/app/settings/admin/presets/template.html
  modules/web/src/app/settings/admin/rule-groups/template.html
  modules/web/src/app/settings/user/component.ts
  modules/web/src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/template.html
  modules/web/src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/eks/template.html
  modules/web/src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/gke/template.html
  modules/web/src/app/shared/components/event-list/template.html
  modules/web/src/app/shared/components/pagination-page-size/component.ts
  modules/web/src/app/shared/components/pagination-page-size/template.html
  modules/web/src/app/shared/module.ts
  modules/web/src/app/sshkey/template.html
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/global/_theme.scss
  modules/web/src/assets/css/material/_theme.scss
  modules/web/src/assets/themes/light.scss
Labels: lgtm, release-note, approved, size/XL, kind/design, dco-signoff: yes, docs/none

#5956 Clarify vSphere credentials
  modules/web/src/app/wizard/step/provider-settings/provider/basic/vsphere/template.html
Labels: release-note-none, size/XS, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5957 Fix spacing in edit preset dialog
  modules/web/src/app/settings/admin/presets/dialog/style.scss
  modules/web/src/app/settings/admin/presets/edit-dialog/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none

#5959 Rework vSphere credentials UI/UX
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/component.ts
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/vsphere/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/basic/vsphere/template.html
Labels: kind/bug, kind/cleanup, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5961 [release/v2.21] Bump version to v2.21.9 && add new changelog
  Makefile
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes

#5962 [release/v2.20] Bump version to v2.20.16 && add new changelog
  Makefile
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes

#5963 Fix update default backup destination
  modules/api/pkg/handler/v1/admin/seed.go
  modules/web/src/app/settings/admin/bucket-settings/destinations/destination-dialog/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none

#5960 [release/v2.22] Update KKP && bump version
  Makefile
  modules/api/Makefile
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/provider/cloud/gke/provider.go
  modules/api/pkg/provider/cloud/nutanix/client.go
  modules/api/pkg/provider/kubernetes/constraint_test.go
  modules/api/pkg/test/e2e/utils/apiclient/models/anything.go
  modules/api/pkg/test/e2e/utils/apiclient/models/code.go
  modules/api/pkg/test/e2e/utils/apiclient/models/target.go
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes, sig/api

#5971 Add toggele option to default constraints
  modules/web/src/app/settings/admin/opa/default-constraints/component.ts
  modules/web/src/app/settings/admin/opa/default-constraints/style.scss
  modules/web/src/app/settings/admin/opa/default-constraints/template.html
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none

#5944 Add `errorMessage` field to `GET /api/v2/projects/{project_id}/clusters` response
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v2/cluster/cluster.go
  modules/api/pkg/handler/v2/cluster/cluster_test.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/provider/cloud/nutanix/client.go
  modules/api/pkg/test/e2e/api/util.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/list_clusters_v2_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/models/project_cluster_list.go
  modules/api/pkg/test/e2e/utils/client.go
  modules/api/pkg/test/e2e/utils/http_test.go
  modules/web/cypress/fixtures/alibaba/clusters.json
  modules/web/cypress/fixtures/anexia/clusters.json
  modules/web/cypress/fixtures/aws/clusters.json
  modules/web/cypress/fixtures/azure/clusters.json
  modules/web/cypress/fixtures/bringyourown/clusters.json
  modules/web/cypress/fixtures/digitalocean/clusters.json
  modules/web/cypress/fixtures/empty-project-cluster-list.json
  modules/web/cypress/fixtures/gcp/clusters.json
  modules/web/cypress/fixtures/hetzner/clusters.json
  modules/web/cypress/fixtures/kubevirt/clusters.json
  modules/web/cypress/fixtures/nutanix/clusters.json
  modules/web/cypress/fixtures/openstack/clusters.json
  modules/web/cypress/fixtures/packet/clusters.json
  modules/web/cypress/fixtures/vsphere/clusters.json
  modules/web/cypress/intercept/clusters.ts
  modules/web/cypress/types/fixtures.ts
  modules/web/src/app/core/services/cluster.ts
  modules/web/src/app/shared/entity/cluster.ts
Labels: kind/feature, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, sig/api, docs/none

#5970 Notification UI/UX update
  modules/web/src/app/cluster/details/cluster/node-list/component.spec.ts
  modules/web/src/app/cluster/details/shared/version-change-dialog/component.spec.ts
  modules/web/src/app/core/components/notification-panel/component.ts
  modules/web/src/app/core/components/notification-panel/style.scss
  modules/web/src/app/core/components/notification-panel/template.html
  modules/web/src/app/core/components/notification-panel/theme.scss
  modules/web/src/app/core/components/notification/component.ts
  modules/web/src/app/core/components/notification/style.scss
  modules/web/src/app/core/components/notification/template.html
  modules/web/src/app/core/components/notification/theme.scss
  modules/web/src/app/core/interceptors/error-notifications.ts
  modules/web/src/app/core/services/node.spec.ts
  modules/web/src/app/core/services/notification.ts
  modules/web/src/assets/css/_images.scss
  modules/web/src/assets/css/_variables.scss
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/global/_theme.scss
  modules/web/src/assets/images/icons/check-white.svg
Labels: size/L, lgtm, release-note, approved, kind/design, dco-signoff: yes, docs/none

#5981 Add functionality to delete disabled label
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/settings/admin/opa/default-constraints/template.html
  modules/web/src/app/shared/components/label-form/component.ts
  modules/web/src/app/shared/components/label-form/template.html
  modules/web/src/app/shared/utils/cluster.ts
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
Labels: kind/bug, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/tbd

#5983 Remove code coverage report from description
  README.md
Labels: kind/cleanup, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none

#5980 Bump k8c.io/kubermatic/v2 to fcae2c473ece
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/v1/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
  modules/api/pkg/handler/v2/cluster_template/cluster_template_test.go
  modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5984 [release/v2.22] Add functionality to delete disabled label
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/shared/components/label-form/component.ts
  modules/web/src/app/shared/components/label-form/template.html
  modules/web/src/app/shared/utils/cluster.ts
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
Labels: kind/bug, size/L, lgtm, release-note, approved, dco-signoff: yes

#5982 Add warnning message in case some seed are not reachable
  modules/web/src/app/cluster/list/cluster/component.spec.ts
  modules/web/src/app/cluster/list/cluster/component.ts
  modules/web/src/app/cluster/list/cluster/style.scss
  modules/web/src/app/cluster/list/cluster/template.html
  modules/web/src/app/shared/entity/cluster.ts
Labels: size/M, lgtm, release-note, approved, kind/design, dco-signoff: yes, docs/none

#5987 Set Azure data disk size default value to 0
  modules/web/src/app/node-data/basic/provider/azure/component.ts
  modules/web/src/app/node-data/basic/provider/azure/template.html
Labels: kind/feature, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/tbd

#5993 Migrate Angular Material Snackbar component from legacy to v15
  modules/web/src/app/core/components/notification/component.ts
  modules/web/src/app/core/services/cluster.spec.ts
  modules/web/src/app/core/services/node.spec.ts
  modules/web/src/app/core/services/notification.ts
  modules/web/src/app/shared/components/terminal/component.spec.ts
  modules/web/src/app/shared/module.ts
  modules/web/src/assets/css/_variables.scss
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/global/_theme.scss
  modules/web/src/assets/css/material/_theme.scss
Labels: release-note-none, size/M, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#6001 Ignore notification outside click if target element is toggle button
  modules/web/src/app/core/components/notification-panel/component.ts
  modules/web/src/app/core/components/notification-panel/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none
