Repository kubermatic/dashboard, pull requests merged in 2023-07, with the labels that each got.

#6055 disable all button in cluster detail page on cluster deletion
  modules/web/src/app/cluster/details/cluster/component.ts
  modules/web/src/app/cluster/details/cluster/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, do-not-merge/code-freeze

#6068 Add VM anti-affinity setting for vSphere machine deployments
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/api/v1/types_test.go
  modules/api/pkg/machine/convert.go
  modules/api/pkg/resources/machine/common.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere_node_spec.go
  modules/web/src/app/cluster/details/cluster/node-list/template.html
  modules/web/src/app/node-data/extended/provider/vsphere/component.ts
  modules/web/src/app/node-data/extended/provider/vsphere/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/node.ts
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/tbd

#6069 Support for configuring multiple networks for vSphere
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/provider/kubernetes/preset.go
  modules/api/pkg/resources/machine/common.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere_cloud_spec.go
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/component.ts
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html
  modules/web/src/app/shared/components/cluster-summary/component.ts
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/cluster.ts
  modules/web/src/app/shared/entity/preset.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
  modules/web/src/test/data/cluster-with-machine-networks.ts
  modules/web/src/test/data/cluster.ts
Labels: kind/feature, lgtm, release-note, approved, size/XL, dco-signoff: yes, sig/api, docs/none

#6072 Dependabot: group Angular updates
  .github/dependabot.yml
Labels: lgtm, approved

#6078 Fix project scoped endpoints for GCP
  modules/api/pkg/handler/v2/provider/gcp.go
Labels: kind/bug, size/M, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none, backport-needed

#6091 Default OS for vSphere to Ubuntu, if template exists
  modules/web/src/app/node-data/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none

#6095 bump KKP, Kubernetes to 1.27, ctrl-runtime 0.15
  modules/api/cmd/kubermatic-api/main.go
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/ee/resource-quota/provider_test.go
  modules/api/pkg/handler/common/cluster.go
  modules/api/pkg/handler/routes_v1_websocket.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v1/project/project_test.go
  modules/api/pkg/handler/v2/constraint/constraint_test.go
  modules/api/pkg/handler/v2/gatekeeperconfig/gatekeeperconfig.go
  modules/api/pkg/handler/v2/gatekeeperconfig/gatekeeperconfig_test.go
  modules/api/pkg/handler/v2/provider/kubevirt_test.go
  modules/api/pkg/handler/websocket/terminal.go
  modules/api/pkg/provider/cloud/kubevirt/client.go
  modules/api/pkg/provider/cloud/kubevirt/manifests/manifests_test.go
  modules/api/pkg/provider/cloud/nutanix/client.go
  modules/api/pkg/provider/kubernetes/admission_plugin_test.go
  modules/api/pkg/provider/kubernetes/alertmanager_test.go
  modules/api/pkg/provider/kubernetes/application_definition_test.go
  modules/api/pkg/provider/kubernetes/cluster.go
  modules/api/pkg/provider/kubernetes/cluster_internal_test.go
  modules/api/pkg/provider/kubernetes/cluster_test.go
  modules/api/pkg/provider/kubernetes/constraint_template_test.go
  modules/api/pkg/provider/kubernetes/constraint_test.go
  modules/api/pkg/provider/kubernetes/external_cluster_test.go
  modules/api/pkg/provider/kubernetes/ipampool_test.go
  modules/api/pkg/provider/kubernetes/member_test.go
  modules/api/pkg/provider/kubernetes/mla_admin_setting_test.go
  modules/api/pkg/provider/kubernetes/preset_test.go
  modules/api/pkg/provider/kubernetes/project_test.go
  modules/api/pkg/provider/kubernetes/rulegroup_test.go
  modules/api/pkg/provider/kubernetes/sa_test.go
  modules/api/pkg/provider/kubernetes/sa_token_test.go
  modules/api/pkg/provider/kubernetes/seed_test.go
  modules/api/pkg/provider/kubernetes/user_test.go
  modules/api/pkg/provider/types_test.go
  modules/api/pkg/provider/watcher/kubernetes/user.go
  modules/api/pkg/test/clusterexposer/controller/controller.go
  modules/api/pkg/test/e2e/api/util.go
  modules/api/pkg/test/e2e/utils/apiclient/models/ip_block.go
  modules/api/pkg/test/e2e/utils/apiclient/models/json.go
  modules/api/pkg/test/e2e/utils/apiclient/models/json_schema_props.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_egress_rule.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_ingress_rule.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_port.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/resource_requirements.go
  modules/api/pkg/test/e2e/utils/apiclient/models/validation_rule.go
  modules/api/pkg/test/e2e/utils/client.go
  modules/api/pkg/test/e2e/utils/dex/client.go
  modules/api/pkg/test/e2e/utils/kubernetes.go
  modules/api/pkg/test/e2e/utils/util.go
  modules/api/pkg/watcher/kubernetes/settings.go
  modules/api/pkg/watcher/kubernetes/user.go
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes, sig/api, kind/chore, docs/none

#6094 VMware Cloud Director: Support for configuring placement policy for machines
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/handler/v2/provider/vmwareclouddirector.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/machine/convert.go
  modules/api/pkg/provider/cloud/vmwareclouddirector/provider.go
  modules/api/pkg/resources/machine/common.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_compute_policies_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_compute_policies_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_compute_policies_no_credentials_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_compute_policies_no_credentials_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/vmwareclouddirector_client.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_compute_policy.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_compute_policy_list.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_node_spec.go
  modules/web/src/app/core/services/node-data/provider/vmware-cloud-director.ts
  modules/web/src/app/core/services/provider/vmware-cloud-director.ts
  modules/web/src/app/core/services/wizard/provider/vmware-cloud-director.ts
  modules/web/src/app/node-data/basic/provider/vmware-cloud-director/component.ts
  modules/web/src/app/node-data/basic/provider/vmware-cloud-director/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/node.ts
  modules/web/src/app/shared/entity/provider/vmware-cloud-director.ts
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, sig/api, docs/none

#6103 Mark sizing and placement policy as optional fields for VMware Cloud Director
  modules/web/src/app/node-data/basic/provider/vmware-cloud-director/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none

#6106 [release/v2.23] Bump version to v2.23.1
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore

#6108 [release/v2.21] Bump version to v2.21.11
  Makefile
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#6114 [release/v2.23] Bump root Makefile to v2.23.1
  Makefile
Labels: kind/cleanup, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#6113 [release/v2.22] Bump root Makefile to v2.22.5
  Makefile
Labels: kind/cleanup, release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#6117 [release/v2.21] mention MC update in changelog
  src/assets/config/changelog.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore

#6118 [release/v2.22] update changelog.json, remove some non-user-facing changes from it
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#6119 [release/v2.23] update changelog.json, remove some non-user-facing changes from it
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#6123 Add vertical scroll in dialogs with material horizontal stepper
  modules/web/src/app/shared/components/cluster-from-template/content/style.scss
  modules/web/src/app/shared/components/cluster-from-template/content/template.html
  modules/web/src/assets/css/material/_main.scss
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes, docs/none

#6126 Keep the show all projects toggel displayed when the user is admin
  modules/web/src/app/project/style.scss
  modules/web/src/app/project/template.html
Labels: kind/feature, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#6128 Fix network and subnet pool dropdowns of Openstack provider
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none

#6131 [release/v2.22] Fix network and subnet pool dropdowns of Openstack provider
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes

#6132 [release/v2.23] Fix network and subnet pool dropdowns of Openstack provider
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes

#6125 Add support for encrypted root volumes in AWS
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/api/v1/types_test.go
  modules/api/pkg/machine/convert.go
  modules/api/pkg/resources/machine/common.go
  modules/api/pkg/test/e2e/utils/apiclient/models/a_w_s_node_spec.go
  modules/web/src/app/cluster/details/cluster/node-list/template.html
  modules/web/src/app/node-data/extended/provider/aws/component.ts
  modules/web/src/app/node-data/extended/provider/aws/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/node.ts
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/tbd
