Repository kubermatic/dashboard, pull requests merged in 2023-01, with the labels that each got.

#5460 Add support to import GCP KubeOne cluster
  modules/web/src/app/kubeone-wizard/module.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/gcp/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/gcp/template.html
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
  modules/web/src/app/kubeone-wizard/steps/provider/component.ts
  modules/web/src/app/kubeone-wizard/steps/summary/template.html
  modules/web/src/app/shared/entity/kubeone-cluster.ts
  modules/web/src/app/wizard/step/cluster/template.html
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5487 Update Copyright Year
  modules/web/package.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#5488 Add support to import Azure KubeOne cluster
  modules/web/src/app/kubeone-wizard/module.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/azure/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/azure/template.html
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
  modules/web/src/app/kubeone-wizard/steps/provider/component.ts
  modules/web/src/app/kubeone-wizard/steps/summary/template.html
  modules/web/src/app/shared/entity/kubeone-cluster.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/tbd

#5478 Kubevirt resource quota calculation
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/ee/resource-quota/handler.go
  modules/api/pkg/ee/resource-quota/handler_test.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/calculate_project_resource_quota_update_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_node_size.go
Labels: kind/feature, release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5491 Pass labels between internal and public ApplicationInstallation + include them in ApplicationDefinition/Installation list
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v2/application_definition/conversion.go
  modules/api/pkg/handler/v2/application_installation/conversion.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_definition_list_item_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_installation.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_body.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_list_item_spec.go
Labels: kind/feature, release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5492 Bump k8c.io/kubermatic/v2 dependency to include new Kubernetes versions
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/common/provider/openstack.go
  modules/api/pkg/handler/v1/provider/openstack_test.go
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
  modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5481 Anexia: fix panic when configuring Node Pool with new Disks attribute
  modules/api/pkg/resources/machine/common.go
  modules/api/pkg/resources/machine/common_test.go
Labels: kind/bug, size/L, lgtm, release-note, approved, ok-to-test, dco-signoff: yes, sig/api, docs/none

#5489 Add project-scoped API endpoints for OpenStack
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v2/provider/openstack.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_server_groups_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_subnet_pools_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_availability_zones_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_availability_zones_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_networks_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_networks_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_security_groups_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_security_groups_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_server_groups_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_server_groups_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_sizes_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_sizes_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_subnet_pools_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_subnet_pools_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_subnets_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_subnets_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_tenants_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/list_project_openstack_tenants_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/openstack/openstack_client.go
Labels: kind/feature, lgtm, approved, size/XXL, kind/api-change, release-note-action-required, dco-signoff: yes, sig/api, docs/none

#5464 Cluster details RBAC enhancements.
  modules/web/cypress/pages/v2/sshkeys/page.ts
  modules/web/src/app/cluster/details/cluster/rbac/add-binding-dialog/component.spec.ts
  modules/web/src/app/cluster/details/cluster/rbac/add-binding-dialog/component.ts
  modules/web/src/app/cluster/details/cluster/rbac/add-binding-dialog/style.scss
  modules/web/src/app/cluster/details/cluster/rbac/add-binding-dialog/template.html
  modules/web/src/app/cluster/details/cluster/rbac/add-binding-dialog/theme.scss
  modules/web/src/app/cluster/details/cluster/rbac/add-service-account-binding-dialog/component.ts
  modules/web/src/app/cluster/details/cluster/rbac/add-service-account-binding-dialog/style.scss
  modules/web/src/app/cluster/details/cluster/rbac/add-service-account-binding-dialog/template.html
  modules/web/src/app/cluster/details/cluster/rbac/add-service-account-dialog/component.ts
  modules/web/src/app/cluster/details/cluster/rbac/add-service-account-dialog/template.html
  modules/web/src/app/cluster/details/cluster/rbac/component.spec.ts
  modules/web/src/app/cluster/details/cluster/rbac/component.ts
  modules/web/src/app/cluster/details/cluster/rbac/service-account/component.ts
  modules/web/src/app/cluster/details/cluster/rbac/service-account/service-account-detail/component.ts
  modules/web/src/app/cluster/details/cluster/rbac/service-account/service-account-detail/style.scss
  modules/web/src/app/cluster/details/cluster/rbac/service-account/service-account-detail/template.html
  modules/web/src/app/cluster/details/cluster/rbac/service-account/template.html
  modules/web/src/app/cluster/details/cluster/rbac/template.html
  modules/web/src/app/cluster/details/cluster/rbac/users-or-groups/component.ts
  modules/web/src/app/cluster/details/cluster/rbac/users-or-groups/template.html
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/cluster/list/cluster/component.ts
  modules/web/src/app/cluster/module.ts
  modules/web/src/app/core/services/cluster-service-account.ts
  modules/web/src/app/core/services/cluster.ts
  modules/web/src/app/core/services/rbac.ts
  modules/web/src/app/shared/entity/rbac.ts
  modules/web/src/assets/css/theme/_component.scss
  modules/web/src/test/data/rbac.ts
  modules/web/src/test/services/cluster-service-account-mock.ts
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/tbd

#5485 Endpoint for total resource quota availiability/usage
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/ee/resource-quota/handler.go
  modules/api/pkg/ee/resource-quota/handler_test.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/resource_quota/list_resource_quotas_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/resource_quota/resource_quota_client.go
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none

#5498 Add project-scoped endpoints for DigitalOcean
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v2/provider/digitalocean.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/resources/reconciling/zz_generated_reconcile.go
  modules/api/pkg/test/e2e/utils/apiclient/client/digitalocean/digitalocean_client.go
  modules/api/pkg/test/e2e/utils/apiclient/client/digitalocean/list_project_digitalocean_sizes_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/digitalocean/list_project_digitalocean_sizes_responses.go
Labels: kind/feature, lgtm, release-note, approved, size/XL, kind/api-change, dco-signoff: yes, sig/api, docs/none

#5508 Add project-scoped API endpoints for vSphere
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v2/provider/vsphere.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vsphere/list_project_v_sphere_datastores_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vsphere/list_project_v_sphere_datastores_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vsphere/list_project_v_sphere_folders_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vsphere/list_project_v_sphere_folders_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vsphere/list_project_v_sphere_networks_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vsphere/list_project_v_sphere_networks_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vsphere/vsphere_client.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, kind/api-change, dco-signoff: yes, sig/api, docs/none

#5509 Add project-scoped API endpoints for KubeVirt
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v2/provider/kubevirt.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/kubevirt_client.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_storage_classes_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_storage_classes_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_kubevirt_storage_classes_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_kubevirt_storage_classes_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_project_kube_virt_instancetypes_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_project_kube_virt_instancetypes_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_project_kube_virt_preferences_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_project_kube_virt_preferences_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_project_kube_virt_storage_classes_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_project_kube_virt_storage_classes_responses.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, kind/api-change, dco-signoff: yes, sig/api, docs/none

#5510 Hide KKP managed applications
  modules/web/src/app/shared/components/application-list/add-application-dialog/component.ts
  modules/web/src/app/shared/components/application-list/component.ts
  modules/web/src/app/shared/components/application-list/style.scss
  modules/web/src/app/shared/components/application-list/template.html
  modules/web/src/app/shared/entity/application.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5522 Default to IPv4 address family in the cluster default endpoint
  modules/api/pkg/handler/v2/cluster_default/cluster_default.go
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5520 Make Konnectivity generally available without feature gate
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/core/services/feature-gate.ts
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
Labels: kind/feature, lgtm, size/S, release-note, approved, dco-signoff: yes, docs/tbd

#5526 Default TunnelingAgentIP only when Tunneling expose strategy is set
  modules/api/pkg/handler/v2/cluster_default/cluster_default.go
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none

#5512 Add project-scoped API endpoints for VMware Cloud Director
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v2/provider/vmwareclouddirector.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_catalogs_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_catalogs_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_networks_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_networks_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_storage_profiles_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_storage_profiles_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_templates_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_project_v_mware_cloud_director_templates_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/vmwareclouddirector_client.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, kind/api-change, dco-signoff: yes, sig/api, docs/none

#5521 Add support for OIDC provider logout URL
  modules/web/src/app/core/components/user-panel/component.spec.ts
  modules/web/src/app/core/components/user-panel/component.ts
  modules/web/src/app/core/services/auth/service.ts
  modules/web/src/app/shared/model/Config.ts
  modules/web/src/test/services/auth-mock.ts
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/tbd

#5527 Remove references to the KonnectivityService feature gate
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/hack/run-api.sh
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v2/feature_gates/feature_gates_test.go
  modules/api/pkg/provider/kubernetes/featuregates.go
  modules/api/pkg/test/e2e/utils/apiclient/models/feature_gates.go
Labels: kind/cleanup, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none

#5529 Drop SLES support
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/handler/common/machine.go
  modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
  modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
  modules/api/pkg/machine/convert.go
  modules/api/pkg/machine/util.go
  modules/api/pkg/resources/machine/common.go
  modules/api/pkg/resources/machine/machinedeployment.go
  modules/api/pkg/test/e2e/utils/apiclient/models/operating_system_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/s_l_e_s_spec.go
  modules/web/src/app/cluster/details/cluster/machine-deployment-details/template.html
  modules/web/src/app/cluster/details/cluster/node-list/template.html
  modules/web/src/app/core/services/node.ts
  modules/web/src/app/node-data/basic/provider/nutanix/component.ts
  modules/web/src/app/node-data/basic/provider/openstack/component.ts
  modules/web/src/app/node-data/basic/provider/vsphere/component.ts
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/node-data/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/datacenter.ts
  modules/web/src/app/shared/entity/node.ts
  modules/web/src/app/shared/model/NodeProviderConstants.ts
  modules/web/src/assets/css/_images.scss
  modules/web/src/assets/images/os/sles.svg
  modules/web/src/test/data/datacenter.ts
Labels: kind/cleanup, size/L, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none

#5531 Add project-scoped API endpoints for Alibaba
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v2/provider/alibaba.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/alibaba/alibaba_client.go
  modules/api/pkg/test/e2e/utils/apiclient/client/alibaba/list_project_alibaba_instance_types_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/alibaba/list_project_alibaba_instance_types_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/alibaba/list_project_alibaba_v_switches_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/alibaba/list_project_alibaba_v_switches_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/alibaba/list_project_alibaba_zones_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/alibaba/list_project_alibaba_zones_responses.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, kind/api-change, dco-signoff: yes, sig/api, docs/none

#5497 Cluster Template Creation, Edit and Customize UX
  modules/web/src/app/cluster-template/component.ts
  modules/web/src/app/core/components/sidenav/component.spec.ts
  modules/web/src/app/core/components/sidenav/component.ts
  modules/web/src/app/shared/components/add-cluster-from-template-dialog/component.ts
  modules/web/src/app/shared/components/add-cluster-from-template-dialog/steps/template/component.ts
  modules/web/src/app/shared/components/add-cluster-from-template-dialog/template.html
  modules/web/src/app/wizard/component.ts
  modules/web/src/app/wizard/template.html
  modules/web/src/app/wizard/types/wizard-mode.ts
Labels: size/L, lgtm, release-note, approved, kind/design, dco-signoff: yes, docs/none

#5441 Add project scoped API endpoints for AWS
  .prow/api.yaml
  .prow/frontend.yaml
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/hack/gen-api-client.sh
  modules/api/hack/update-swagger.sh
  modules/api/hack/verify-licenses.sh
  modules/api/pkg/handler/v2/provider/aws.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/list_project_a_w_s_security_groups_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/list_project_a_w_s_security_groups_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/list_project_a_w_s_sizes_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/list_project_a_w_s_sizes_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/list_project_a_w_s_subnets_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/list_project_a_w_s_subnets_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/list_project_a_w_s_v_p_cs_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/list_project_a_w_s_v_p_cs_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: lgtm, release-note, approved, size/XXL, kind/api-change, dco-signoff: yes, sig/api, docs/none

#5530 Add route to list Seeds and their status
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/handler/v2/seedoverview/seedoverview.go
  modules/api/pkg/test/e2e/utils/apiclient/client/seed/list_seed_status_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/seed/list_seed_status_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/seed/seed_client.go
  modules/api/pkg/test/e2e/utils/apiclient/models/seed_status.go
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes, sig/api, docs/none

#5537 Add External Cluster label to KubeOne secrets
  modules/api/pkg/handler/v2/external_cluster/external_cluster.go
  modules/api/pkg/handler/v2/external_cluster/kubeone.go
  modules/api/pkg/provider/kubernetes/credentials.go
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5504 Add support to select preset in credentials step of KubeOne wizard
  modules/web/src/app/cluster/list/external-cluster/component.spec.ts
  modules/web/src/app/cluster/list/kubeone/component.ts
  modules/web/src/app/cluster/list/kubeone/template.html
  modules/web/src/app/core/module.ts
  modules/web/src/app/core/services/external-cluster.ts
  modules/web/src/app/core/services/kubeone-wizard/kubeone-presets.ts
  modules/web/src/app/kubeone-wizard/module.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/preset/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/preset/style.scss
  modules/web/src/app/kubeone-wizard/steps/credentials/preset/template.html
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/aws/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/azure/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/gcp/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/template.html
  modules/web/src/app/kubeone-wizard/steps/summary/component.ts
  modules/web/src/app/kubeone-wizard/steps/summary/template.html
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5539 Use project aware API endpoints
  modules/web/cypress/utils/endpoint.ts
  modules/web/src/app/core/services/external-cluster.ts
  modules/web/src/app/core/services/kubeone-wizard/kubeone-presets.ts
  modules/web/src/app/core/services/node-data/provider/nutanix.ts
  modules/web/src/app/core/services/project.ts
  modules/web/src/app/core/services/wizard/presets.ts
  modules/web/src/app/core/services/wizard/provider/alibaba.ts
  modules/web/src/app/core/services/wizard/provider/anexia.ts
  modules/web/src/app/core/services/wizard/provider/aws.ts
  modules/web/src/app/core/services/wizard/provider/azure.ts
  modules/web/src/app/core/services/wizard/provider/digitalocean.ts
  modules/web/src/app/core/services/wizard/provider/equinix.ts
  modules/web/src/app/core/services/wizard/provider/gcp.ts
  modules/web/src/app/core/services/wizard/provider/hetzner.ts
  modules/web/src/app/core/services/wizard/provider/kubevirt.ts
  modules/web/src/app/core/services/wizard/provider/nutanix.ts
  modules/web/src/app/core/services/wizard/provider/openstack.spec.ts
  modules/web/src/app/core/services/wizard/provider/openstack.ts
  modules/web/src/app/core/services/wizard/provider/provider.ts
  modules/web/src/app/core/services/wizard/provider/vmware-cloud-director.ts
  modules/web/src/app/core/services/wizard/provider/vsphere.ts
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/eks/component.ts
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/preset/component.ts
  modules/web/src/app/settings/admin/presets/component.ts
  modules/web/src/app/shared/components/external-cluster-credentials/preset/component.ts
  modules/web/src/app/shared/components/external-cluster-credentials/provider/aks/component.ts
  modules/web/src/app/shared/components/external-cluster-credentials/provider/eks/component.ts
  modules/web/src/app/shared/components/external-cluster-credentials/provider/gke/component.ts
  modules/web/src/app/wizard/step/provider-settings/preset/component.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, sig/ui, docs/none

#5541 bump kkp version
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/test/e2e/utils/apiclient/models/custom_network_policy.go
  modules/api/pkg/test/e2e/utils/apiclient/models/datacenter_spec_kubevirt.go
  modules/api/pkg/test/e2e/utils/apiclient/models/image_cloning.go
  modules/api/pkg/test/e2e/utils/apiclient/models/int_or_string.go
  modules/api/pkg/test/e2e/utils/apiclient/models/ip_block.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_egress_rule.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_ingress_rule.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_peer.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_port.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/policy_type.go
  modules/api/pkg/test/e2e/utils/apiclient/models/protocol.go
  modules/api/pkg/test/e2e/utils/apiclient/models/type.go
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, sig/api, kind/chore, docs/none

#5518 Refactor KubeOne Patch
  modules/api/pkg/handler/v2/external_cluster/external_cluster.go
  modules/api/pkg/handler/v2/external_cluster/kubeone.go
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, docs/tbd

#5545 Fix health API request polling issue
  modules/web/src/app/core/services/cluster.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#5548 [release/v2.21] changelog update 2.21.5
  src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, kind/chore

#5546 [release/v2.19] changelog update 2.19.14
  src/assets/config/changelog.json
Labels: lgtm, size/S, approved, dco-signoff: yes

#5536 project overview follow up
  modules/web/src/app/project-overview/component.ts
  modules/web/src/app/project-overview/create-resource-panel/template.html
  modules/web/src/app/project-overview/style.scss
  modules/web/src/app/project-overview/template.html
  modules/web/src/app/shared/components/labels/style.scss
  modules/web/src/app/shared/components/labels/template.html
Labels: size/L, lgtm, release-note, approved, kind/design, dco-signoff: yes, docs/none

#5499 Add support to migrate KubeOne cluster container runtime
  modules/web/src/app/cluster/details/kubeone/component.ts
  modules/web/src/app/cluster/details/kubeone/edit-cluster-dialog/component.ts
  modules/web/src/app/cluster/details/kubeone/edit-cluster-dialog/template.html
  modules/web/src/app/cluster/details/kubeone/template.html
  modules/web/src/app/cluster/module.ts
  modules/web/src/app/shared/entity/external-cluster.ts
  modules/web/src/app/shared/entity/kubeone-cluster.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/tbd

#5553 [release/v2.19] Bump version v2.19.14
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5554 [release/v2.20] Bump version v2.20.12
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5555 [release/v2.21] Bump version v2.21.5
  Makefile
  package-lock.json
  package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5559 Update KubeVirt logo to mark end of technology preview
  modules/web/src/assets/images/clouds/kubevirt-dark.svg
  modules/web/src/assets/images/clouds/kubevirt.svg
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5556 bump kkp version
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/test/e2e/utils/apiclient/models/datacenter_spec_kubevirt.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kube_virt_infra_storage_class.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5562 Fix credentials handing for GCP
  modules/api/pkg/handler/v2/provider/gcp.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5544 Changing Provider after choosing Kubeadm Break the wizard
  modules/web/src/app/core/services/wizard/wizard.ts
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/wizard/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#5563 update premmisions for service accounts and groups
  modules/web/src/app/project-overview/component.ts
  modules/web/src/app/shared/model/Config.ts
  modules/web/src/assets/config/userGroupConfig.json
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#5564 Some fixes for RQ calculation
  modules/api/pkg/ee/resource-quota/handler.go
  modules/api/pkg/ee/resource-quota/handler_test.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none

#5567 fix style for combobox component
  modules/web/src/app/cluster/details/kubeone/template.html
  modules/web/src/app/shared/components/combobox/style.scss
  modules/web/src/assets/css/material/_main.scss
Labels: release-note-none, size/XS, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5566 Add KubeVirt images endpoint
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/common/provider/kubevirt.go
  modules/api/pkg/handler/v2/provider/kubevirt.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/kubevirt_client.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_kubevirt_images_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/kubevirt/list_kubevirt_images_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/models/datacenter_spec_kubevirt.go
  modules/api/pkg/test/e2e/utils/apiclient/models/http_source.go
  modules/api/pkg/test/e2e/utils/apiclient/models/image_cloning.go
  modules/api/pkg/test/e2e/utils/apiclient/models/image_list_with_versions.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kube_virt_http_source.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kube_virt_image_source_type.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kube_virt_image_sources.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kube_virt_images.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kube_virt_images_list.go
  modules/api/pkg/test/e2e/utils/apiclient/models/o_s_versions.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, sig/api, docs/none

#5569 KubeVirt switch StorageClass config from annotation to DC
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/provider/cloud/kubevirt/provider.go
  modules/api/pkg/provider/cloud/kubevirt/storage_class.go
  modules/api/pkg/provider/cloud/provider.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kube_virt_infra_storage_class.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, sig/virtualization, sig/api, docs/tbd

#5568 Update KubeVirt operating system image support
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/core/services/node-data/provider/kubevirt.ts
  modules/web/src/app/core/services/provider/kubevirt.ts
  modules/web/src/app/core/services/wizard/provider/kubevirt.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/components/kubevirt-pre-allocated-data-volumes/component.ts
  modules/web/src/app/shared/components/kubevirt-pre-allocated-data-volumes/template.html
  modules/web/src/app/shared/entity/provider/kubevirt.ts
  modules/web/src/app/shared/model/NodeProviderConstants.ts
  modules/web/src/app/shared/module.ts
  modules/web/src/app/wizard/module.ts
  modules/web/src/app/wizard/step/provider-settings/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/kubevirt/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/kubevirt/style.scss
  modules/web/src/app/wizard/step/provider-settings/provider/extended/kubevirt/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/extended/template.html
Labels: kind/feature, lgtm, release-note, approved, size/XL, dco-signoff: yes, docs/none

#5561 Upgrade KubeOne MD version
  modules/web/src/app/cluster/details/kubeone/machine-deployment-details/component.ts
  modules/web/src/app/cluster/details/kubeone/machine-deployment-details/template.html
  modules/web/src/app/cluster/details/kubeone/machine-deployment-dialog/component.ts
  modules/web/src/app/cluster/details/kubeone/machine-deployment-dialog/style.scss
  modules/web/src/app/cluster/details/kubeone/machine-deployment-dialog/template.html
  modules/web/src/app/cluster/details/kubeone/machine-deployment-list/component.ts
  modules/web/src/app/cluster/details/kubeone/machine-deployment-list/template.html
  modules/web/src/app/cluster/details/kubeone/template.html
  modules/web/src/app/cluster/module.ts
  modules/web/src/app/shared/entity/external-cluster.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5572 hide create external cluster in the create resources button when external cluster disabled in the admin panel
  modules/web/src/app/project-overview/create-resource-panel/component.ts
  modules/web/src/app/project-overview/create-resource-panel/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#5534 Introduce middleware leveraging Seed's OIDC config
  modules/api/.golangci.yml
  modules/api/cmd/kubermatic-api/main.go
  modules/api/cmd/kubermatic-api/options.go
  modules/api/pkg/handler/auth/oidc.go
  modules/api/pkg/handler/auth/plugin.go
  modules/api/pkg/handler/auth/sa.go
  modules/api/pkg/handler/common/kubeconfig.go
  modules/api/pkg/handler/middleware/middleware.go
  modules/api/pkg/handler/routes_v1_optional.go
  modules/api/pkg/handler/routes_v1_websocket.go
  modules/api/pkg/handler/routing.go
  modules/api/pkg/handler/test/fake_auth.go
  modules/api/pkg/handler/test/hack/hack.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v1/cluster/kubeconfig.go
  modules/api/pkg/handler/v1/common/common.go
  modules/api/pkg/handler/v2/kubernetes-dashboard/login.go
  modules/api/pkg/handler/v2/kubernetes-dashboard/request.go
  modules/api/pkg/handler/v2/kubernetes-dashboard/response.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/handler/v2/routing.go
  modules/api/pkg/handler/v2/webterminal/webterminal.go
  modules/api/pkg/provider/auth/oidc.go
  modules/api/pkg/provider/auth/types/types.go
  modules/api/pkg/provider/types.go
Labels: kind/feature, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, sig/api, docs/tbd

#5573 Fix vsphere resource calculation
  modules/api/pkg/ee/resource-quota/handler.go
  modules/api/pkg/ee/resource-quota/handler_test.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5565 Add functionality to configure default project quota
  modules/web/src/app/dynamic/enterprise/quotas/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/default-project-quota/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/default-project-quota/style.scss
  modules/web/src/app/dynamic/enterprise/quotas/default-project-quota/template.html
  modules/web/src/app/dynamic/enterprise/quotas/module.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
  modules/web/src/app/dynamic/enterprise/quotas/style.scss
  modules/web/src/app/dynamic/enterprise/quotas/template.html
  modules/web/src/app/project/edit-project/component.ts
  modules/web/src/app/project/edit-project/template.html
  modules/web/src/app/project/style.scss
  modules/web/src/app/shared/entity/settings.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5519 Add functionality for live quota update
  modules/web/src/app/cluster/details/cluster/machine-deployment-details/component.ts
  modules/web/src/app/cluster/details/cluster/machine-deployment-details/template.html
  modules/web/src/app/cluster/details/cluster/machine-deployment-list/component.ts
  modules/web/src/app/core/services/node.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/theme.scss
  modules/web/src/app/dynamic/enterprise/quotas/services/quota-calculation.ts
  modules/web/src/app/node-data/basic/provider/alibaba/component.ts
  modules/web/src/app/node-data/basic/provider/anexia/component.ts
  modules/web/src/app/node-data/basic/provider/aws/component.ts
  modules/web/src/app/node-data/basic/provider/azure/component.ts
  modules/web/src/app/node-data/basic/provider/digitalocean/component.ts
  modules/web/src/app/node-data/basic/provider/equinix/component.ts
  modules/web/src/app/node-data/basic/provider/gcp/component.ts
  modules/web/src/app/node-data/basic/provider/hetzner/component.ts
  modules/web/src/app/node-data/basic/provider/nutanix/component.ts
  modules/web/src/app/node-data/basic/provider/openstack/component.ts
  modules/web/src/app/node-data/basic/provider/vmware-cloud-director/component.ts
  modules/web/src/app/node-data/basic/provider/vsphere/component.ts
  modules/web/src/app/node-data/basic/provider/vsphere/template.html
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/node-data/dialog/component.ts
  modules/web/src/app/node-data/dialog/template.html
  modules/web/src/app/node-data/template.html
  modules/web/src/app/shared/entity/node.ts
  modules/web/src/app/shared/entity/quota.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/aws/component.ts
  modules/web/src/assets/css/theme/_component.scss
  modules/web/src/assets/themes/dark.scss
  modules/web/src/assets/themes/light.scss
Labels: lgtm, release-note, approved, size/XL, dco-signoff: yes, docs/tbd

#5574 Add missing external cluster error states in `ExternalClusterState`
  modules/web/src/app/shared/entity/external-cluster.ts
Labels: kind/feature, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none

#5577 Add live quota functionality for KubeVirt
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/project/edit-project/template.html
  modules/web/src/app/shared/entity/node.ts
  modules/web/src/app/shared/entity/provider/kubevirt.ts
  modules/web/src/app/shared/entity/quota.ts
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes, docs/tbd

#5581 Propagate InitialCNIValuesRequestAnnotation to backend
  modules/api/pkg/handler/common/cluster.go
  modules/api/pkg/handler/v2/cluster_template/cluster_template.go
Labels: kind/feature, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none

#5595 Show progress bars when defaulting is applied to projects
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
  modules/web/src/app/dynamic/enterprise/quotas/template.html
Labels: kind/bug, release-note-none, size/L, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5596 Prevent blockage when quota resources is not configured to any project
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5597 Display tooltip message on default project quota label
  modules/web/src/app/dynamic/enterprise/quotas/template.html
Labels: release-note-none, size/XS, lgtm, approved, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#5602 Pass ReconciliationInterval & DeployOptions between internal and API ApplicationInstallation
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v2/application_installation/conversion.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_spec.go
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5599 add an option for restricting presets to projects
  modules/web/src/app/settings/admin/presets/dialog/steps/preset/component.ts
  modules/web/src/app/settings/admin/presets/dialog/steps/preset/template.html
  modules/web/src/app/shared/components/select/component.ts
  modules/web/src/app/shared/components/select/template.html
  modules/web/src/app/shared/entity/preset.ts
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5605 Downgrade version of xterm-addon-fit package
  modules/web/package-lock.json
  modules/web/package.json
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5611 Do not set nonAMD64WithCanalAndIPVS condition on upgrade
  modules/api/pkg/handler/common/upgrade.go
Labels: kind/bug, kind/cleanup, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5609 Fix default quota api - introduce settings v2
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v2/convert.go
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/ee/resource-quota/handler.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v1/admin/settings.go
  modules/api/pkg/handler/v1/admin/settings_test.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/global_settings.go
Labels: kind/bug, release-note-none, lgtm, approved, size/XL, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5614 Refactor endpoints to list OperatingSystemProfiles
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
  modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
  modules/api/pkg/provider/kubernetes/operating_system_profile.go
  modules/api/pkg/provider/types.go
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5613 Move Labels in ApplicationInstallationListItem to the top level
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v2/application_installation/conversion.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_list_item.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_list_item_spec.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5628 Prevent version upgrade for system applications
  modules/web/src/app/shared/components/application-list/add-application-dialog/template.html
  modules/web/src/app/shared/components/application-list/component.ts
  modules/web/src/app/shared/components/application-list/edit-application-dialog/component.ts
  modules/web/src/app/shared/components/application-list/edit-application-dialog/template.html
  modules/web/src/app/shared/entity/application.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5626 opa constraint: handle enforcementAction in UI
  modules/web/src/app/shared/entity/opa.ts
Labels: kind/feature, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved
