Repository kubermatic/dashboard, pull requests merged in 2023-02, with the labels that each got.

#5625 [release/v2.19] Bump version to 2.19.15
  Makefile
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, do-not-merge/code-freeze

#5624 Update dependency for k8c.io/kubermatic/v2 to `62c8bfb`
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/common/cluster.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v1/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
  modules/api/pkg/handler/v2/cniversion/cniversion.go
  modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
  modules/api/pkg/resources/cluster/cluster.go
  modules/api/pkg/resources/machine/common.go
  modules/api/pkg/test/e2e/utils/apiclient/models/constraint_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/tag_category.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere_cloud_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere_tag.go
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5627 [release/v2.20] Bump version to 2.20.13
  Makefile
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore, code-freeze-approved

#5630 Load application definition details to display method and source icons
  modules/web/src/app/core/services/application.ts
  modules/web/src/app/shared/components/application-list/component.ts
Labels: kind/bug, release-note-none, size/L, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5623 Forbid upgrading to Kubernetes v1.25 if Pod Security Policy are enabled
  modules/web/src/app/cluster/details/shared/version-change-dialog/component.ts
  modules/web/src/app/cluster/details/shared/version-change-dialog/template.html
  modules/web/src/app/shared/entity/cluster.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/tbd, code-freeze-approved

#5631 Allow User to Go Through the Cluster Template Wizard When Quota Exceeded
  modules/web/src/app/dynamic/enterprise/quotas/services/quota-calculation.ts
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/node-data/template.html
  modules/web/src/app/wizard/component.ts
  modules/web/src/app/wizard/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5633 Prepare dashboard for KKP 2.22.0-alpha.0 release
  Makefile
  modules/api/Makefile
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, sig/release, code-freeze-approved

#5636 Revamp support for tag association for vSphere machines
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/handler/v2/provider/vsphere.go
  modules/api/pkg/machine/convert.go
  modules/api/pkg/resources/machine/common.go
  modules/api/pkg/test/e2e/utils/apiclient/models/tag_category.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere_cloud_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/v_sphere_tag.go
  modules/web/src/app/core/module.ts
  modules/web/src/app/core/services/node-data/provider/vsphere.ts
  modules/web/src/app/core/services/node-data/service.ts
  modules/web/src/app/core/services/provider/vsphere.ts
  modules/web/src/app/core/services/wizard/provider/vsphere.ts
  modules/web/src/app/machine-networks/component.spec.ts
  modules/web/src/app/node-data/extended/provider/vsphere/component.ts
  modules/web/src/app/node-data/extended/provider/vsphere/tag-categories/component.ts
  modules/web/src/app/node-data/extended/provider/vsphere/tag-categories/style.scss
  modules/web/src/app/node-data/extended/provider/vsphere/tag-categories/template.html
  modules/web/src/app/node-data/extended/provider/vsphere/template.html
  modules/web/src/app/node-data/module.ts
  modules/web/src/app/shared/components/machine-networks-new/component.spec.ts
  modules/web/src/app/shared/entity/node.ts
  modules/web/src/app/wizard/step/network/component.spec.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Labels: kind/feature, lgtm, release-note, approved, size/XL, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5634 Fix Restrict Preset to Projects
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/preset/component.ts
  modules/web/src/app/settings/admin/presets/dialog/steps/preset/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5640 Load category tags when new tag with category is added
  modules/web/src/app/node-data/extended/provider/vsphere/tag-categories/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5641 Fix font-size and hide extended progress bars if no quota configured
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5645 Use router state to communicate `mode` value to cluster wizard
  modules/web/src/app/cluster-template/component.ts
  modules/web/src/app/core/components/sidenav/component.spec.ts
  modules/web/src/app/core/components/sidenav/component.ts
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/project-overview/component.ts
  modules/web/src/app/project-overview/create-resource-panel/component.ts
  modules/web/src/app/shared/components/add-cluster-from-template-dialog/component.ts
  modules/web/src/app/shared/components/side-nav-field/component.ts
  modules/web/src/app/wizard/component.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5615 Fix resource quota calculation - support MD edit
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/ee/resource-quota/handler.go
  modules/api/pkg/ee/resource-quota/handler_test.go
  modules/api/pkg/test/e2e/utils/apiclient/client/project/calculate_project_resource_quota_update_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/models/replaced_resources.go
Labels: kind/bug, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5649 hide the quota in edit project dialog for non-admin users
  modules/web/src/app/project/edit-project/component.ts
  modules/web/src/app/project/edit-project/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5659 add template reference variable for instance type
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/eks/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5646 Fix resource quota calculation for Edit MD
  modules/web/src/app/core/services/node.ts
  modules/web/src/app/dynamic/enterprise/quotas/services/quota-calculation.ts
  modules/web/src/app/node-data/basic/provider/alibaba/component.ts
  modules/web/src/app/node-data/basic/provider/anexia/component.ts
  modules/web/src/app/node-data/basic/provider/aws/component.ts
  modules/web/src/app/node-data/basic/provider/azure/component.ts
  modules/web/src/app/node-data/basic/provider/digitalocean/component.ts
  modules/web/src/app/node-data/basic/provider/equinix/component.ts
  modules/web/src/app/node-data/basic/provider/gcp/component.ts
  modules/web/src/app/node-data/basic/provider/hetzner/component.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
  modules/web/src/app/node-data/basic/provider/nutanix/component.ts
  modules/web/src/app/node-data/basic/provider/openstack/component.ts
  modules/web/src/app/node-data/basic/provider/vmware-cloud-director/component.ts
  modules/web/src/app/node-data/basic/provider/vsphere/component.ts
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/node-data/dialog/component.ts
  modules/web/src/app/node-data/dialog/template.html
  modules/web/src/app/shared/entity/quota.ts
  modules/web/src/app/shared/model/NodeSpecChange.ts
Labels: release-note-none, lgtm, approved, size/XL, dco-signoff: yes, docs/none, code-freeze-approved

#5662 Mark KubeVirt node affinity preset key and values as required
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/template.html
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5648 Fixes GKE zone and version list endpoint
  modules/api/pkg/handler/v2/external_cluster/gke.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5664 Add `undefined` value check on user `projects`
  modules/web/src/app/project/edit-project/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5668 Mark KubeVirt node affinity preset key and values as required
  src/app/node-data/basic/provider/kubevirt/component.ts
  src/app/node-data/basic/provider/kubevirt/template.html
  src/app/shared/components/chip-list/component.ts
  src/app/shared/components/chip-list/template.html
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes, do-not-merge/code-freeze

#5669 Fix KubeVirt client scheme creation
  modules/api/pkg/provider/cloud/kubevirt/client.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5672 Reset OS image value if there are no matches in dropdown options
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5666 Persist annotations when upgrading a cluster
  modules/api/pkg/handler/common/cluster.go
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5673 Assign provider value on initialize ProviderSettingsStepComponent
  modules/web/src/app/dynamic/enterprise/quotas/services/quota-calculation.ts
  modules/web/src/app/wizard/step/provider-settings/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5675 Fixes after introducing project id to routes
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v2/external_cluster/external_cluster.go
  modules/api/pkg/handler/v2/provider/aws.go
  modules/api/pkg/handler/v2/provider/gcp.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/gcp/gcp_client.go
  modules/api/pkg/test/e2e/utils/apiclient/client/gcp/list_project_g_c_p_subnetworks_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/gcp/list_project_g_c_p_subnetworks_responses.go
  modules/api/pkg/test/e2e/utils/apiclient/client/gke/gke_client.go
  modules/api/pkg/test/e2e/utils/apiclient/client/gke/list_project_g_c_p_zones_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/gke/list_project_g_c_p_zones_responses.go
Labels: kind/bug, release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5678 Update version to v2.22.0-alpha.1
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#5661 Fix KubeVirt Node marshalling error
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/api/v1/types_test.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5682 Fix Quota Calculation for Kubevirt Edit MD
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5685 Mark KubeVirt node affinity preset values as optional
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5686 Mark KubeVirt node affinity preset values as optional
  src/app/node-data/basic/provider/kubevirt/component.ts
  src/app/node-data/basic/provider/kubevirt/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, do-not-merge/code-freeze

#5692 Display creation date in cluster template list view
  modules/web/src/app/cluster-template/component.ts
  modules/web/src/app/cluster-template/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5688 Update proxy mode options on initial page load
  modules/web/src/app/wizard/step/cluster/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5689 adjust Azure Node Size values in the quota calculation payload
  modules/web/src/app/node-data/basic/provider/azure/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5693 Hotfix: Validation for cron expressions for etcd backups and metering schedule
  modules/web/src/app/backup/list/automatic-backup/add-dialog/template.html
  modules/web/src/app/dynamic/enterprise/metering/schedule-config/add-dialog/template.html
  modules/web/src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/template.html
  modules/web/src/app/shared/validators/cron.validator.ts
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5695 Bump KKP dependency to latest commit
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
  modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
  modules/api/pkg/test/e2e/utils/apiclient/models/resource_requirements.go
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5700 Remove dynamic kubelet config setting and set it to always disabled
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/node-data/dialog/component.ts
  modules/web/src/app/node-data/dialog/template.html
  modules/web/src/app/node-data/template.html
Labels: kind/bug, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5699 Update image for web terminal
  modules/api/pkg/handler/websocket/terminal.go
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5698 Restore flavor fields of KubeVirt node spec
  modules/api/pkg/machine/convert.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5696 Add periodic "ping to client" to keep the Web Terminal connection alive
  modules/api/pkg/handler/routes_v1_websocket.go
  modules/api/pkg/handler/websocket/terminal.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5703 Fix sorting on provider overview table
  modules/web/src/app/settings/admin/seed-configurations/seed-configurations-details/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5704 Hotfix: handling for default project quotas
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/api/v2/convert.go
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v1/admin/settings.go
  modules/api/pkg/handler/v1/admin/settings_test.go
  modules/api/pkg/handler/websocket/settings.go
  modules/api/pkg/test/e2e/api/settings_test.go
  modules/api/pkg/test/e2e/utils/apiclient/models/global_settings.go
  modules/api/pkg/test/e2e/utils/apiclient/models/project_resource_quota.go
  modules/api/pkg/test/e2e/utils/apiclient/models/resource_details.go
  modules/api/pkg/test/e2e/utils/apiclient/models/setting_spec.go
  modules/api/pkg/test/e2e/utils/client.go
Labels: kind/bug, release-note-none, lgtm, approved, size/XL, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5707 Update default project quota layout
  modules/web/src/app/dynamic/enterprise/quotas/default-project-quota/template.html
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#5710 Hotfix: project list for inactive projects
  modules/api/pkg/handler/v1/project/project.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5706 Fix Initial Value for Projects in Create Preset
  modules/web/src/app/settings/admin/presets/dialog/steps/preset/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/ui, docs/none, code-freeze-approved

#5709 Only take single subscription of project quota API request
  modules/web/src/app/dynamic/enterprise/quotas/service.ts
  modules/web/src/app/project/component.ts
  modules/web/src/app/project/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5708 Update the Conditions for Enable get kubeconfig and add MD Buttons
  modules/web/src/app/cluster/details/external-cluster/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
  modules/web/src/app/cluster/details/external-cluster/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5697 Fix edit application
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v2/application_installation/application_installation_test.go
  modules/api/pkg/handler/v2/application_installation/conversion.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_installation_list_item.go
  modules/web/src/app/core/services/application.ts
Labels: kind/bug, release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5715 Add unknown status for installed applications
  modules/web/src/app/shared/components/application-list/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5712 Display hints in edit schedule dialog for metering
  modules/web/src/app/dynamic/enterprise/metering/schedule-config/edit-dialog/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5716 [release/v2.21] Bump patch version & update changelog for 2.21.6
  Makefile
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, do-not-merge/code-freeze

#5713 Minor UI/UX improvements
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#5717 Update `sizes` endpoint of Equinix provider
  modules/web/cypress/types/endpoints.ts
  modules/web/cypress/utils/endpoint.ts
  modules/web/src/app/core/services/provider/equinix.ts
  modules/web/src/app/core/services/wizard/provider/equinix.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5721 Include annotations for nodeDeployments in get cluster templates response
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v2/cluster_template/cluster_template.go
  modules/api/pkg/test/e2e/utils/apiclient/models/cluster_template_node_deployment.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5723 Fix payload for Kubevirt quota calculation
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5724 Add image for web-terminal
  hack/images/web-terminal/Dockerfile
  hack/images/web-terminal/release.sh
  modules/api/pkg/handler/websocket/terminal.go
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5727 Handle "pong" messages from web terminal client
  modules/api/pkg/handler/websocket/terminal.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5729 cherrypick hide external cluster from project overview
  src/app/project-overview/create-resource-panel/component.ts
  src/app/project-overview/create-resource-panel/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, do-not-merge/code-freeze

#5730 Update header names for Equinix provider endpoints
  modules/web/src/app/core/services/wizard/provider/equinix.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5733 Fix IP ranges pattern error message + labels
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/wizard/step/cluster/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5726 Keep WS connection alive by exchange of messages
  modules/web/src/app/shared/components/terminal/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5739 Fixes for EKS clusters
  modules/api/pkg/handler/v2/routes_v2.go
  modules/web/src/app/shared/components/external-cluster-credentials/provider/eks/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5736 Add project-scoped endpoints for AKS
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v2/external_cluster/aks.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/client/aks/aks_client.go
  modules/api/pkg/test/e2e/utils/apiclient/client/aks/list_project_a_k_s_versions_parameters.go
  modules/api/pkg/test/e2e/utils/apiclient/client/aks/list_project_a_k_s_versions_responses.go
Labels: kind/feature, size/L, lgtm, release-note, approved, kind/api-change, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5737 List AKS machinedeployments for Warning state
  modules/api/pkg/handler/v2/external_cluster/node.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5742 Update dependencies for API
  modules/api/go.mod
  modules/api/go.sum
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5746 Display documentation link under Allowed IP Ranges field
  modules/web/src/app/cluster/details/cluster/edit-cluster/style.scss
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/shared/components/chip-list/template.html
  modules/web/src/app/wizard/step/cluster/style.scss
  modules/web/src/app/wizard/step/cluster/template.html
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#5744 Disable Web Terminal Button when no Machine Deployment is on Running State
  modules/web/src/app/cluster/details/cluster/component.ts
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/shared/utils/health-status.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5743 Update conditions to disable download KubeOne kubeconfig button
  modules/web/src/app/cluster/details/kubeone/component.ts
  modules/web/src/app/cluster/details/kubeone/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5747 Fix fetching of resources base on preset or manually entering credentials
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/aks/component.ts
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5749 Remove support of KubeOne cluster container runtime migration
  modules/web/src/app/cluster/details/kubeone/component.ts
  modules/web/src/app/cluster/details/kubeone/edit-cluster-dialog/component.ts
  modules/web/src/app/cluster/details/kubeone/edit-cluster-dialog/template.html
  modules/web/src/app/cluster/details/kubeone/template.html
  modules/web/src/app/cluster/module.ts
  modules/web/src/app/shared/entity/external-cluster.ts
Labels: kind/cleanup, release-note-none, size/L, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5750 Consider AKS cluster with warning state as a running cluster.
  modules/web/src/app/cluster/details/external-cluster/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/template.html
  modules/web/src/app/cluster/details/external-cluster/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5741 Bump version to v2.22.0-rc.0
  Makefile
  modules/api/Makefile
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5753 Disable deletion for default project quotas
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/dynamic/enterprise/quotas/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5757 Fix method to deduce the KKP git hash
  hack/lib.sh
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#5751 Fix quota calculation for Kubevirt resources
  modules/api/pkg/ee/resource-quota/handler.go
  modules/api/pkg/handler/common/provider/kubevirt.go
  modules/api/pkg/handler/common/provider/kubevirt_test.go
  modules/api/pkg/handler/v2/provider/kubevirt_test.go
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5748 openstack annotion md: do not set security if c.Spec.Cloud.OpenstackSecurityGroups is empty
  modules/api/pkg/resources/machine/common.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5761 Update KKP dependency to latest commit
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/v1/cluster/upgrade_test.go
  modules/api/pkg/handler/v2/cluster/upgrade_test.go
  modules/api/pkg/handler/v2/version/version_test.go
  modules/api/pkg/test/e2e/utils/apiclient/models/helm_deploy_options.go
  modules/api/pkg/test/e2e/utils/apiclient/models/provider_type.go
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5759 Add changelog.json for end user facing changes in KKP 2.22.0
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/L, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none, code-freeze-approved

#5762 Fix changelog JSON syntax error
  modules/web/src/assets/config/changelog.json
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#5754 Bump version to v2.22.0-rc.1
  Makefile
  modules/api/Makefile
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5766 Extend swagger doc mentioning API as being internal
  modules/api/cmd/kubermatic-api/main.go
  modules/api/cmd/kubermatic-api/swagger.json
Labels: release-note-none, size/M, lgtm, approved, kind/documentation, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5770 Update dependencies for dashboard
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#5772 Bump k8c.io/kubermatic/v2 dependency to Feb 22 commit
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/common/upgrade.go
Labels: kind/cleanup, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#5773 Update k8c.io/kubermatic/v2 dependency to latest
  modules/api/go.mod
  modules/api/go.sum
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5767 Bump version to v2.22.0
  Makefile
  modules/api/Makefile
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#5760 Use registry.k8s.io for preloaded kube-controller-manager image
  hack/ci/setup-kind-cluster.sh
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#5765 Add assertion for delete project button
  modules/web/cypress/pages/v2/projects/page.ts
  modules/web/cypress/pages/v2/settings/admin/dynamic-datacenters/page.ts
Labels: release-note-none, size/XS, lgtm, approved, kind/failing-test, dco-signoff: yes, docs/none

#5774 Add script for updating swagger in kubermatic/docs
  modules/api/hack/ci/update-docs.sh
Labels: kind/bug, release-note-none, size/M, lgtm, approved, kind/documentation, dco-signoff: yes, sig/api, kind/regression, kind/chore, docs/none

#5764 Show/Hide share cluster button from admin default settings
  docs/manuals/customizing.md
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/test/helper.go
  modules/web/src/app/cluster/details/cluster/component.spec.ts
  modules/web/src/app/cluster/details/cluster/component.ts
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/settings/admin/defaults/component.ts
  modules/web/src/app/settings/admin/defaults/template.html
  modules/web/src/app/shared/entity/settings.ts
  modules/web/src/app/shared/model/Config.ts
  modules/web/src/assets/config/config.json
  modules/web/src/test/services/app-config-mock.ts
  modules/web/src/test/services/settings-mock.ts
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/tbd

#5784 UI fixes and improvements
  modules/web/src/app/cluster/details/cluster/machine-deployment-details/template.html
  modules/web/src/app/core/components/navigation/project/template.html
  modules/web/src/app/settings/admin/custom-link-form/style.scss
  modules/web/src/app/settings/admin/customization/style.scss
  modules/web/src/app/shared/components/side-nav-field/style.scss
  modules/web/src/app/shared/components/side-nav-field/theme.scss
  modules/web/src/app/shared/components/spinner-with-confirmation/style.scss
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/material/_main.scss
  modules/web/src/assets/themes/dark.scss
  modules/web/src/assets/themes/light.scss
Labels: release-note-none, size/M, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5781 KubeVirt prevent marshalling of resources both in instancetype and NodeSpec
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/api/v1/types_test.go
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/virtualization, sig/api, docs/none
