Repository kubermatic/dashboard, pull requests merged in 2023-03, with the labels that each got.

#5783 Add a Button to Allow Hide/Show of Sensitive Information
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/alibaba-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/anexia-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/aws-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/azure-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/digitalocean-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/equinix-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/hetzner-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/nutanix-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/openstack-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/vmware-cloud-director-provider-settings/template.html
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/vsphere-provider-settings/template.html
  modules/web/src/app/dynamic/enterprise/metering/config/credentials-dialog/template.html
  modules/web/src/app/kubeone-wizard/steps/cluster/template.html
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/aws/template.html
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/azure/template.html
  modules/web/src/app/node-data/template.html
  modules/web/src/app/settings/admin/bucket-settings/destinations/edit-credentials-dialog/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/aks/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/alibaba/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/anexia/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/aws/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/azure/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/digitalocean/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/eks/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/equinix/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/hetzner/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/nutanix/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vmware-cloud-director/template.html
  modules/web/src/app/settings/admin/presets/dialog/steps/settings/provider/vsphere/template.html
  modules/web/src/app/shared/components/external-cluster-credentials/provider/aks/template.html
  modules/web/src/app/shared/components/external-cluster-credentials/provider/eks/template.html
  modules/web/src/app/shared/components/openstack-credentials/application/template.html
  modules/web/src/app/shared/components/openstack-credentials/default/template.html
  modules/web/src/app/shared/directives/input-password.ts
  modules/web/src/app/shared/module.ts
  modules/web/src/app/wizard/step/provider-settings/provider/basic/alibaba/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/anexia/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/aws/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/azure/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/digitalocean/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/equinix/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/hetzner/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/nutanix/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/vmware-cloud-director/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/vsphere/template.html
  modules/web/src/assets/css/material/_main.scss
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5787 Fix DC MachineFlavorFilter not used
  modules/api/pkg/handler/common/filter.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none

#5786 Add Tooltip for Disabled Button in Cluster Menu
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/assets/css/global/_theme.scss
Labels: release-note-none, size/M, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5792 Upgrade dependencies
  modules/web/.eslintrc.yml
  modules/web/jest.config.cjs
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/app/settings/admin/dynamic-datacenters/datacenter-data-dialog/template.html
  modules/web/src/app/settings/admin/dynamic-datacenters/template.html
  modules/web/src/app/wizard/step/provider-datacenter/template.html
  modules/web/src/assets/css/root.scss
  modules/web/src/tsconfig.spec.json
  modules/web/tsconfig.spec.json
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#5791 API support for share cluster kubeconfig configuration
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/v1/admin/settings.go
  modules/api/pkg/provider/kubernetes/settings.go
  modules/api/pkg/test/e2e/api/settings_test.go
  modules/api/pkg/test/e2e/utils/apiclient/models/anything.go
  modules/api/pkg/test/e2e/utils/apiclient/models/code.go
  modules/api/pkg/test/e2e/utils/apiclient/models/global_settings.go
  modules/api/pkg/test/e2e/utils/apiclient/models/instancetype_matcher.go
  modules/api/pkg/test/e2e/utils/apiclient/models/preference_matcher.go
  modules/api/pkg/test/e2e/utils/apiclient/models/target.go
  modules/api/pkg/test/e2e/utils/client.go
Labels: kind/bug, release-note-none, lgtm, approved, size/XL, dco-signoff: yes, sig/api, docs/none

#5800 Apply Disabled Style for the Disabled Preset
  modules/web/src/app/core/components/sidenav/style.scss
  modules/web/src/app/settings/admin/presets/template.html
  modules/web/src/assets/css/global/_main.scss
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none

#5799 Add a Back Button to Preset Dialog
  modules/web/src/app/settings/admin/presets/dialog/component.ts
  modules/web/src/app/settings/admin/presets/dialog/style.scss
  modules/web/src/app/settings/admin/presets/dialog/template.html
Labels: release-note-none, size/M, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5801 Improve responsiveness for smaller screen sizes
  modules/web/src/app/core/components/sidenav/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/style.scss
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
  modules/web/src/app/settings/admin/customization/template.html
  modules/web/src/app/settings/admin/nav/component.ts
  modules/web/src/app/shared/constants/common.ts
  modules/web/src/assets/css/global/_main.scss
Labels: size/M, lgtm, release-note, approved, kind/design, dco-signoff: yes, docs/none

#5803 Allow updating of clusterNetwork.proxyMode via the KKP API
  modules/api/pkg/handler/common/cluster.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none, backport-needed

#5789 Bump API version and clean up changelog.json
  modules/api/cmd/kubermatic-api/main.go
  modules/api/cmd/kubermatic-api/swagger.json
  modules/web/src/assets/config/changelog.json
Labels: kind/cleanup, release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#5809 Quota UI Adjustment
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
  modules/web/src/app/project/component.ts
  modules/web/src/app/project/style.scss
  modules/web/src/app/project/template.html
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none

#5810 Change kubeconfig context name from default to cluster ID
  modules/api/pkg/handler/common/kubeconfig.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v1/cluster/kubeconfig_test.go
  modules/api/pkg/handler/v2/cluster/kubeconfig.go
  modules/api/pkg/handler/v2/cluster/kubeconfig_test.go
  modules/api/pkg/handler/v2/routes_v2.go
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none

#5811 Enable concurrency for golangci-lint
  .prow/api.yaml
  modules/api/.golangci.yml
Labels: release-note-none, size/XS, lgtm, approved, kind/failing-test, dco-signoff: yes, sig/api, kind/chore, docs/none

#5813 OPA and Backup UI fixes
  modules/web/src/app/backup/details/automatic-backup/backups/template.html
  modules/web/src/app/backup/list/automatic-backup/template.html
  modules/web/src/app/backup/list/snapshot/restore-dialog/template.html
  modules/web/src/app/cluster/details/cluster/constraints/constraint-dialog/component.ts
  modules/web/src/app/cluster/details/cluster/constraints/style.scss
  modules/web/src/app/cluster/details/cluster/constraints/template.html
  modules/web/src/app/settings/admin/bucket-settings/style.scss
  modules/web/src/assets/images/icons/restore.svg
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none

#5814 Use Alpine Linux 3.17
  Dockerfile
  hack/images/web-terminal/Dockerfile
Labels: kind/cleanup, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#5816 API: Bump dependency for KKP
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/test/helper.go
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5818 [release/v2.21] Bump version v2.21.7
  Makefile
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, kind/chore

#5817 [release/v2.20] Bump version v2.20.14
  Makefile
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#5821 [release/v2.22] Bump version v2.22.1
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore

#5831 Login page visual changes
  modules/web/src/app/pages/frontpage/style.scss
  modules/web/src/app/pages/frontpage/template.html
  modules/web/src/assets/images/branding/bg.svg
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#5836 Update xterm to latest version
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore, docs/none

#5837 Correctly handle MD health if no replicas are configured
  modules/web/src/app/shared/utils/health-status.ts
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, backport-needed

#5840 [release/v2.21] Correctly handle MD health if no replicas are configured
  src/app/shared/utils/health-status.ts
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#5854 Bump k8c.io/kubermatic/v2 dependency
  modules/api/go.mod
  modules/api/go.sum
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5857 Update GitHub SSH key
  hack/lib.sh
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#5855 api: fix logger error fmt mismatch
  modules/api/cmd/kubermatic-api/main.go
Labels: kind/cleanup, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#5861 Configure OpenStack ingress cluster settings
  modules/web/src/app/node-data/basic/provider/openstack/component.ts
  modules/web/src/app/node-data/basic/provider/openstack/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/cluster.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
  modules/web/src/app/wizard/step/provider-settings/provider/extended/openstack/template.html
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/provided

#5865 [release/v2.21] Configure OpenStack ingress cluster settings
  src/app/node-data/basic/provider/openstack/component.ts
  src/app/node-data/basic/provider/openstack/template.html
  src/app/shared/components/cluster-summary/template.html
  src/app/shared/entity/cluster.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/application/component.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/component.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/default/component.ts
  src/app/wizard/step/provider-settings/provider/extended/openstack/template.html
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes

#5866 Remove unused cloud provider code
  modules/api/pkg/handler/v2/kubernetes-dashboard/login.go
  modules/api/pkg/handler/v2/networkdefaults/networkdefaults.go
  modules/api/pkg/provider/cloud/alibaba/provider.go
  modules/api/pkg/provider/cloud/anexia/provider.go
  modules/api/pkg/provider/cloud/aws/provider.go
  modules/api/pkg/provider/cloud/aws/provider_test.go
  modules/api/pkg/provider/cloud/aws/security_group.go
  modules/api/pkg/provider/cloud/aws/security_group_test.go
  modules/api/pkg/provider/cloud/azure/client.go
  modules/api/pkg/provider/cloud/azure/provider.go
  modules/api/pkg/provider/cloud/bringyourown/provider.go
  modules/api/pkg/provider/cloud/digitalocean/provider.go
  modules/api/pkg/provider/cloud/fake/provider.go
  modules/api/pkg/provider/cloud/gcp/provider.go
  modules/api/pkg/provider/cloud/gke/provider.go
  modules/api/pkg/provider/cloud/hetzner/provider.go
  modules/api/pkg/provider/cloud/kubevirt/provider.go
  modules/api/pkg/provider/cloud/kubevirt/storage_class.go
  modules/api/pkg/provider/cloud/nutanix/provider.go
  modules/api/pkg/provider/cloud/openstack/helper.go
  modules/api/pkg/provider/cloud/openstack/provider.go
  modules/api/pkg/provider/cloud/packet/provider.go
  modules/api/pkg/provider/cloud/vmwareclouddirector/provider.go
  modules/api/pkg/provider/cloud/vsphere/provider.go
  modules/api/pkg/provider/cloud/vsphere/provider_test.go
  modules/api/pkg/provider/types.go
  modules/api/pkg/test/e2e/utils/dex/client.go
  modules/api/pkg/test/e2e/utils/kubernetes.go
  modules/api/pkg/test/e2e/utils/util.go
Labels: kind/cleanup, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, sig/api, docs/none

#5867 dashboard: allow http for cookie store
  modules/web/src/app/core/services/auth/service.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#5868 Mutate partial cluster before validating its spec
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/common/cluster.go
  modules/api/pkg/resources/cluster/cluster.go
Labels: kind/cleanup, release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, docs/none
