Repository kubermatic/dashboard, pull requests merged in 2023-08, with the labels that each got.

#6142 Migrate material slide-toggle component from legacy to latest version
  modules/web/src/app/shared/components/application-list/style.scss
  modules/web/src/app/shared/module.ts
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/material/_main.scss
  modules/web/src/assets/css/material/_theme.scss
  modules/web/src/assets/themes/dark.scss
  modules/web/src/assets/themes/light.scss
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#6141 Fix script for building themes
  modules/web/hack/extract-themes.sh
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none

#6140 Migrate material paginator component from legacy to latest version
  modules/web/src/app/backup/details/automatic-backup/backups/component.ts
  modules/web/src/app/backup/list/automatic-backup/component.ts
  modules/web/src/app/backup/list/restore/component.ts
  modules/web/src/app/backup/list/snapshot/component.ts
  modules/web/src/app/cluster-template/component.ts
  modules/web/src/app/cluster/details/cluster/constraints/component.ts
  modules/web/src/app/cluster/details/cluster/constraints/violation-details/component.ts
  modules/web/src/app/cluster/details/cluster/machine-deployment-list/component.ts
  modules/web/src/app/cluster/details/cluster/mla/rule-groups/component.ts
  modules/web/src/app/cluster/details/cluster/node-list/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-machine-deployment-list/component.ts
  modules/web/src/app/cluster/details/external-cluster/external-node-list/component.ts
  modules/web/src/app/cluster/details/kubeone/machine-deployment-list/component.ts
  modules/web/src/app/cluster/list/cluster/component.ts
  modules/web/src/app/cluster/list/external-cluster/component.ts
  modules/web/src/app/cluster/list/kubeone/component.ts
  modules/web/src/app/dynamic/enterprise/allowed-registries/component.ts
  modules/web/src/app/dynamic/enterprise/group/component.ts
  modules/web/src/app/dynamic/enterprise/metering/legacy-reports/list/component.ts
  modules/web/src/app/dynamic/enterprise/metering/schedule-config/report-list/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/component.ts
  modules/web/src/app/member/component.ts
  modules/web/src/app/project/component.ts
  modules/web/src/app/serviceaccount/component.ts
  modules/web/src/app/settings/admin/accounts/component.ts
  modules/web/src/app/settings/admin/admins/component.ts
  modules/web/src/app/settings/admin/bucket-settings/component.ts
  modules/web/src/app/settings/admin/dynamic-datacenters/component.ts
  modules/web/src/app/settings/admin/opa/constraint-templates/component.ts
  modules/web/src/app/settings/admin/opa/default-constraints/component.ts
  modules/web/src/app/settings/admin/presets/component.ts
  modules/web/src/app/settings/admin/rule-groups/component.ts
  modules/web/src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/aks/component.ts
  modules/web/src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/eks/component.ts
  modules/web/src/app/shared/components/add-external-cluster-dialog/steps/cluster/provider/gke/component.ts
  modules/web/src/app/shared/components/event-list/component.ts
  modules/web/src/app/shared/components/spinner-with-confirmation/style.scss
  modules/web/src/app/shared/module.ts
  modules/web/src/app/sshkey/component.ts
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#6144 Fix the redirect url for keycloak logout
  modules/web/src/app/core/services/auth/service.ts
  modules/web/src/app/project/template.html
  modules/web/src/app/shared/model/Config.ts
Labels: kind/bug, size/M, lgtm, release-note, approved, dco-signoff: yes, sig/ui, docs/tbd

#6153 [release/v2.23] Fix the redirect URI for keycloak
  modules/web/src/app/core/services/auth/service.ts
  modules/web/src/app/shared/model/Config.ts
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes

#6157 docs: remove Zenhub guide
  Zenhub.md
Labels: kind/cleanup, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none

#6166 Skip fetching metrics if metric-server is not available
  modules/api/pkg/handler/common/cluster.go
  modules/api/pkg/handler/common/machine.go
  modules/api/pkg/handler/v2/machine/machine_test.go
  modules/web/src/app/cluster/details/cluster/component.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, docs/none

#6171 Fix filter for quota calculation
  modules/web/src/app/node-data/basic/provider/hetzner/component.ts
  modules/web/src/app/node-data/basic/provider/nutanix/component.ts
  modules/web/src/app/node-data/basic/provider/vsphere/component.ts
Labels: kind/bug, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none

#6170 [release/v2.22] Update web for v2.22.6 patch release
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore

#6176 [release/v2.21] Updates for v2.21.12 patch release
  Makefile
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore

#6177 [release/v2.22] Add information about telemetry update
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore

#6178 [release/v2.23] Updates for v2.23.2 patch release
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore

#6175 Bump k8c.io/kubermatic/v2 dependency to f0cb4e1a1357
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/v1/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
  modules/api/pkg/handler/v2/cluster_template/cluster_template_test.go
  modules/api/pkg/test/e2e/utils/apiclient/models/metering_report_configuration.go
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#6179 Fix: vSphere tags for initial machine deployments
  modules/web/src/app/node-data/extended/provider/vsphere/tag-categories/component.ts
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#6188 Support multiple NodePort allowed IP ranges
  modules/web/src/app/shared/components/cluster-summary/component.ts
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
Labels: customer-request, kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#6189 Update tooltip to document vSphere folder tags support
  modules/web/src/app/wizard/step/provider-settings/provider/extended/vsphere/template.html
Labels: release-note-none, size/XS, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none

#6196 Fix preset to cluster mapping for VMware Cloud Director
  modules/api/pkg/provider/kubernetes/preset.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none

#6198 Update k8c.io/kubermatic/v2 to `5aa989ae9870`
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
  modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none
