Repository kubermatic/dashboard, pull requests merged in 2023-06, with the labels that each got.

#5989 Add support to import a vsphere kubeone cluster
  modules/api/go.mod
  modules/api/pkg/handler/v2/external_cluster/kubeone.go
  modules/web/src/app/kubeone-wizard/module.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/template.html
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/vsphere/component.ts
  modules/web/src/app/kubeone-wizard/steps/credentials/provider/basic/vsphere/template.html
  modules/web/src/app/kubeone-wizard/steps/provider/component.ts
  modules/web/src/app/kubeone-wizard/steps/summary/template.html
  modules/web/src/app/shared/entity/kubeone-cluster.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, sig/ui, sig/api, docs/none

#6005 API: Bump KKP dependency to latest commit
  modules/api/go.mod
  modules/api/go.sum
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#6015 Update go dependencies for web
  modules/web/go.mod
  modules/web/go.sum
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#6016 Update packages for UI
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/app/pages/page-not-found/style.scss
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#6025 Update Golang veresion to 1.20.5
  .prow/api.yaml
  .prow/common.yaml
  .prow/frontend.yaml
  hack/images/web-terminal/Dockerfile
  hack/images/web-terminal/release.sh
  hack/verify-spelling.sh
  modules/api/hack/gen-api-client.sh
  modules/api/hack/update-swagger.sh
  modules/api/hack/verify-licenses.sh
  modules/web/containers/chrome-headless/Dockerfile
  modules/web/containers/chrome-headless/release.sh
  modules/web/containers/custom-dashboard/Dockerfile
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, do-not-merge/code-freeze

#6028 API: Update dependency for KubeOne
  modules/api/go.mod
  modules/api/go.sum
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#6038 UI UX fixes
  modules/web/src/app/backup/details/snapshot/component.ts
  modules/web/src/app/backup/list/snapshot/component.ts
  modules/web/src/app/backup/routing.ts
  modules/web/src/app/cluster/details/cluster/edit-provider-settings/azure-provider-settings/template.html
  modules/web/src/app/core/components/sidenav/component.ts
  modules/web/src/app/node-data/basic/provider/aws/component.ts
  modules/web/src/app/node-data/basic/provider/kubevirt/component.ts
  modules/web/src/app/node-data/basic/provider/openstack/component.ts
  modules/web/src/app/shared/components/application-list/add-application-dialog/template.html
  modules/web/src/app/shared/components/application-list/component.ts
  modules/web/src/app/shared/components/application-list/template.html
  modules/web/src/app/shared/components/cluster-summary/component.ts
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/wizard/step/provider-settings/provider/basic/vsphere/template.html
Labels: kind/bug, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, docs/none, do-not-merge/code-freeze

#6040 Minor improvements for UI/UX
  modules/web/package-lock.json
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/member/add-member/component.ts
  modules/web/src/app/settings/admin/admins/add-admin-dialog/component.ts
  modules/web/src/app/shared/components/cluster-summary/template.html
Labels: release-note-none, lgtm, approved, size/XXL, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#6042 Disable Add/Save machine deployment button during quota estimation
  modules/web/src/app/node-data/dialog/component.ts
  modules/web/src/app/node-data/dialog/template.html
  modules/web/src/assets/css/_images.scss
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none, do-not-merge/code-freeze

#6043 Prevent creating cluster from template if quota exceeded
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/service.ts
  modules/web/src/app/shared/components/add-cluster-from-template-dialog/component.ts
  modules/web/src/app/shared/components/add-cluster-from-template-dialog/style.scss
  modules/web/src/app/shared/components/add-cluster-from-template-dialog/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6046 Clear AWS subnets dropdown when there are no subnets available
  modules/web/src/app/node-data/basic/provider/aws/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6045 Fix the filter for accelerated networking for azure
  modules/web/src/app/node-data/basic/provider/azure/component.ts
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6048 Minor improvements
  .dockerignore
  .github/ISSUE_TEMPLATE/pre-release.md
  .github/ISSUE_TEMPLATE/release.md
  docs/manuals/release.md
  modules/web/tsconfig.json
Labels: kind/cleanup, release-note-none, lgtm, size/S, approved, dco-signoff: yes, kind/chore, docs/none, do-not-merge/code-freeze

#6049 Prevent calling availability zone api request if assign availability set
  modules/web/src/app/node-data/basic/provider/azure/component.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6052 [release/v2.21] Bump version to 2.21.10 and update changelog.json
  package-lock.json
  package.json
  src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, kind/chore, do-not-merge/code-freeze

#6051 [release/v2.22] Bump version to v2.22.4 and update changelog.json
  modules/api/Makefile
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
  modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
  modules/api/pkg/test/e2e/utils/apiclient/models/datacenter_spec_kubevirt.go
  modules/api/pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, do-not-merge/code-freeze

#6053 Use `async` pipe to handle quota calculation observable in template
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/component.ts
  modules/web/src/app/dynamic/enterprise/quotas/quota-widget/template.html
  modules/web/src/app/node-data/dialog/component.ts
  modules/web/src/app/node-data/dialog/template.html
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, do-not-merge/code-freeze

#6047 Bump version to KKP 2.23.0-beta.2
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
  modules/api/pkg/handler/v2/external_cluster/external_cluster_test.go
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#6058 Update to Go 1.19.10
  .prow/api.yaml
  .prow/common.yaml
  .prow/frontend.yaml
  hack/verify-spelling.sh
  modules/api/hack/gen-api-client.sh
  modules/api/hack/update-swagger.sh
  modules/api/hack/verify-licenses.sh
  modules/web/containers/chrome-headless/Dockerfile
  modules/web/containers/custom-dashboard/Dockerfile
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes, sig/api, kind/chore, do-not-merge/code-freeze

#6057 Bump kubermatic/build image
  .prow/api.yaml
  .prow/common.yaml
  .prow/frontend.yaml
  hack/verify-spelling.sh
  modules/api/hack/update-swagger.sh
  modules/api/hack/verify-licenses.sh
  modules/web/containers/chrome-headless/Dockerfile
  modules/web/containers/custom-dashboard/Dockerfile
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, do-not-merge/code-freeze

#6059 Bump to v2.23.0-rc.0
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, do-not-merge/code-freeze
