Repository kubermatic/dashboard, pull requests merged in 2024-03, with the labels that each got.

#6572 Fix invalid project ID in API requests for Nutanix provider
  modules/web/src/app/core/services/wizard/provider/nutanix.ts
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6579 Fix edge provider issues
  modules/web/src/app/cluster/details/cluster/component.ts
  modules/web/src/app/core/services/wizard/wizard.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6581 Fix icon and toggle button border color issues
  modules/web/src/assets/css/material/_theme.scss
  modules/web/src/assets/themes/dark.scss
Labels: release-note-none, size/XS, lgtm, approved, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#6583 Fix application status message
  modules/web/src/app/shared/components/application-list/component.ts
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#6586 update to Go 1.22.1
  .prow/api.yaml
  .prow/common.yaml
  .prow/frontend.yaml
  hack/images/web-terminal/Dockerfile
  hack/verify-spelling.sh
  modules/api/hack/gen-api-client.sh
  modules/api/hack/update-swagger.sh
  modules/api/hack/verify-licenses.sh
  modules/web/containers/chrome-headless/Dockerfile
  modules/web/containers/chrome-headless/release.sh
  modules/web/containers/custom-dashboard/Dockerfile
Labels: size/M, lgtm, release-note, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#6588 fix race condition in unit tests
  modules/api/pkg/test/e2e/utils/http_test.go
Labels: release-note-none, size/M, lgtm, approved, kind/failing-test, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#6587 Disable restore backup button if snabshot/automatic are on deletion
  modules/web/src/app/backup/details/automatic-backup/backups/component.ts
  modules/web/src/app/backup/details/automatic-backup/component.ts
  modules/web/src/app/backup/details/automatic-backup/style.scss
  modules/web/src/app/backup/details/automatic-backup/template.html
  modules/web/src/app/backup/details/snapshot/component.ts
  modules/web/src/app/backup/details/snapshot/style.scss
  modules/web/src/app/backup/details/snapshot/template.html
  modules/web/src/app/backup/list/snapshot/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6590 bump to future KKP 2.25.0-beta.3
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#6578 Set replicas to 1 when edge provider is used
  modules/api/pkg/resources/machine/machinedeployment.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#6591 add valuesblock to api type used by cluster generation
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/test/e2e/utils/apiclient/models/application_spec.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#6592 Fix OSP list for VMware Cloud Director
  modules/web/src/app/node-data/component.ts
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6593 [release/v2.24] Bump to Go 1.21.8
  .prow/api.yaml
  .prow/common.yaml
  .prow/frontend.yaml
  hack/verify-spelling.sh
  modules/api/hack/gen-api-client.sh
  modules/api/hack/update-swagger.sh
  modules/api/hack/verify-licenses.sh
  modules/web/containers/chrome-headless/Dockerfile
  modules/web/containers/custom-dashboard/Dockerfile
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes, sig/api, kind/chore, code-freeze-approved

#6599 Edge provider improvements
  modules/web/src/app/cluster/details/cluster/machine-deployment-list/template.html
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
  modules/web/src/assets/css/_images.scss
Labels: kind/feature, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6594 [release/v2.23] Bump to Go 1.20.13
  .prow/api.yaml
  .prow/common.yaml
  .prow/frontend.yaml
  hack/verify-spelling.sh
  modules/api/hack/gen-api-client.sh
  modules/api/hack/update-swagger.sh
  modules/api/hack/verify-licenses.sh
  modules/web/containers/chrome-headless/Dockerfile
  modules/web/containers/custom-dashboard/Dockerfile
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes, sig/api, kind/chore, code-freeze-approved

#6600 Fix wrong color for some icons in dark mode
  modules/web/src/assets/themes/dark.scss
Labels: release-note-none, size/XS, lgtm, approved, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#6602 Enable web terminal button when at least one MD replica is ready
  modules/web/src/app/cluster/details/cluster/component.ts
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6603 bump KKP to e09bc21d4, clean up go.mod
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: kind/cleanup, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#6604 Set Replica count to `0` for Edge provider
  modules/web/src/app/node-data/component.ts
Labels: kind/feature, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#6605 Revert the machine deployment status
  modules/api/pkg/resources/machine/machinedeployment.go
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#6606 Include Edge provider in the OSP list
  modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
  modules/api/pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#6589 Allow non admin users to manage BSL
  modules/api/cmd/kubermatic-api/main.go
  modules/api/cmd/kubermatic-api/wrappers_ce.go
  modules/api/cmd/kubermatic-api/wrappers_ee.go
  modules/api/pkg/ee/clusterbackup/storage-location/handler.go
  modules/api/pkg/ee/clusterbackup/storage-location/provider.go
  modules/api/pkg/ee/cmd/kubermatic-api/wrappers.go
  modules/api/pkg/handler/v2/clusterbackup/storage-location/cbsl.go
  modules/api/pkg/handler/v2/clusterbackup/storage-location/wrappers_ce.go
  modules/api/pkg/handler/v2/clusterbackup/storage-location/wrappers_ee.go
  modules/api/pkg/provider/types.go
Labels: kind/bug, release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#6609 Prepare 2.25.0-rc.0
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#6584 Bump version and changelog for March Minor release 2.25.0
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/L, lgtm, approved, kind/documentation, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#6611 Hide the update available icon when there is no updates
  modules/web/src/app/cluster/details/cluster/machine-deployment-list/template.html
  modules/web/src/app/cluster/details/shared/version-change-dialog/component.ts
  modules/web/src/app/cluster/details/shared/version-change-dialog/template.html
  modules/web/src/app/cluster/details/shared/version-picker/component.ts
  modules/web/src/app/wizard/step/cluster/component.ts
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none

#6619 [release/v2.23] bump for 2.23.12
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api

#6621 [release/v2.23] update changelog.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#6620 [release/v2.24] update changelog.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes

#6617 Append grafana organization id parameter
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/handler/v1/common/conversion.go
  modules/web/src/app/cluster/details/cluster/mla/alertmanager-config/component.spec.ts
  modules/web/src/app/cluster/details/cluster/mla/alertmanager-config/component.ts
  modules/web/src/app/shared/entity/project.ts
  modules/web/src/test/data/project.ts
Labels: kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, sig/ui, sig/api, docs/none

#6627 Remove defaultProject from angular.json
  modules/web/angular.json
Labels: kind/cleanup, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none

#6270 Add basic support for OpenNebula machine deployments
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/machine/convert.go
  modules/api/pkg/test/e2e/utils/apiclient/models/node_cloud_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/open_nebula_node_spec.go
Labels: kind/feature, size/L, lgtm, release-note, approved, ok-to-test, dco-signoff: yes, sig/api, docs/none

#6631 Remove changelog dialog
  modules/web/cypress/types/endpoints.ts
  modules/web/cypress/utils/endpoint.ts
  modules/web/cypress/utils/mocks.ts
  modules/web/src/app/core/components/changelog/dialog.ts
  modules/web/src/app/core/components/changelog/style.scss
  modules/web/src/app/core/components/changelog/template.html
  modules/web/src/app/core/components/changelog/theme.scss
  modules/web/src/app/core/components/help-panel/component.ts
  modules/web/src/app/core/components/help-panel/template.html
  modules/web/src/app/core/module.ts
  modules/web/src/app/core/services/changelog.ts
  modules/web/src/app/module.ts
  modules/web/src/app/shared/model/changelog.ts
  modules/web/src/assets/config/changelog.json
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/global/_theme.scss
  modules/web/src/assets/css/theme/_component.scss
  modules/web/src/assets/themes/dark.scss
  modules/web/src/assets/themes/light.scss
  modules/web/src/environments/environment.e2e.local.ts
  modules/web/src/environments/environment.e2e.mock.ts
  modules/web/src/environments/environment.e2e.ts
  modules/web/src/environments/environment.prod.ts
  modules/web/src/environments/environment.ts
Labels: kind/cleanup, lgtm, release-note, approved, size/XL, dco-signoff: yes, docs/tbd

#6638 Migrate to MDC classes
  modules/web/cypress/pages/admin-settings.po.ts
  modules/web/cypress/pages/clusters.po.ts
  modules/web/cypress/pages/v2/clusters/list/page.ts
  modules/web/src/app/cluster/details/cluster/cni-version/theme.scss
  modules/web/src/app/cluster/details/shared/version-picker/theme.scss
  modules/web/src/app/shared/components/tab-card/style.scss
  modules/web/src/app/shared/components/tab-card/theme.scss
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/global/_theme.scss
  modules/web/src/assets/css/material/_main.scss
  modules/web/src/assets/css/material/_theme.scss
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#6639 Upgrade to Angular version 17
  modules/web/angular.json
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/app/core/services/cluster-service-account.ts
  modules/web/src/app/external-cluster-wizard/steps/summary/style.scss
  modules/web/src/app/node-data/basic/provider/nutanix/component.ts
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/shared/validators/larger-than.validator.ts
  modules/web/src/assets/css/theme/_component.scss
Labels: kind/feature, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, docs/none

#6640 migrate mat-radio component to v15
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/gke/style.scss
  modules/web/src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
  modules/web/src/app/shared/directives/value-changed-indicator.ts
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/global/_theme.scss
  modules/web/src/assets/css/material/_main.scss
  modules/web/src/assets/css/material/_theme.scss
Labels: release-note-none, size/M, lgtm, approved, dco-signoff: yes, kind/chore, docs/none
