Repository kubermatic/dashboard, pull requests merged in 2024-05, with the labels that each got.

#6682 Cluster Backup: CA bundle and Prefix configuration for backup storage
  modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/component.ts
  modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/template.html
  modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/template.html
  modules/web/src/app/shared/entity/backup.ts
Labels: customer-request, kind/feature, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none

#6681 Add enable/disable etcd backups option in admin settings
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/api/v2/types.go
  modules/api/pkg/handler/test/helper.go
  modules/api/pkg/handler/v1/admin/settings.go
  modules/api/pkg/handler/v1/admin/settings_test.go
  modules/api/pkg/handler/v2/etcdbackupconfig/etcdbackupconfig.go
  modules/api/pkg/handler/v2/etcdbackupconfig/etcdbackupconfig_test.go
  modules/api/pkg/handler/v2/etcdrestore/etcdrestore.go
  modules/api/pkg/handler/v2/etcdrestore/etcdrestore_test.go
  modules/api/pkg/handler/v2/routes_v2.go
  modules/api/pkg/test/e2e/utils/apiclient/models/global_settings.go
  modules/api/pkg/test/e2e/utils/client.go
  modules/web/src/app/backup/list/component.ts
  modules/web/src/app/backup/list/template.html
  modules/web/src/app/cluster/list/cluster/component.ts
  modules/web/src/app/core/components/sidenav/template.html
  modules/web/src/app/project-overview/component.ts
  modules/web/src/app/project-overview/template.html
  modules/web/src/app/settings/admin/defaults/template.html
  modules/web/src/app/shared/entity/settings.ts
Labels: kind/feature, size/L, lgtm, release-note, approved, dco-signoff: yes, sig/ui, sig/api, docs/none

#6683 OSM is always enabled
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/cluster/details/cluster/template.html
  modules/web/src/app/node-data/component.ts
  modules/web/src/app/node-data/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/components/save-cluster-template/component.ts
  modules/web/src/app/shared/entity/cluster.ts
  modules/web/src/app/wizard/component.ts
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
  modules/web/src/app/wizard/step/summary/component.ts
Labels: kind/cleanup, size/L, lgtm, release-note, approved, dco-signoff: yes, kind/deprecation, docs/none

#6685 Migrate the rest of MDC-based Angular Material Components
  modules/web/src/app/cluster/details/cluster/edit-cluster/style.scss
  modules/web/src/app/cluster/details/cluster/machine-deployment-list/style.scss
  modules/web/src/app/cluster/details/cluster/rbac/add-binding-dialog/style.scss
  modules/web/src/app/cluster/details/cluster/rbac/add-binding-dialog/theme.scss
  modules/web/src/app/cluster/details/cluster/rbac/add-service-account-binding-dialog/style.scss
  modules/web/src/app/cluster/details/cluster/style.scss
  modules/web/src/app/cluster/list/cluster/template.html
  modules/web/src/app/dynamic/enterprise/theming/picker/style.scss
  modules/web/src/app/kubeone-wizard/steps/cluster/style.scss
  modules/web/src/app/kubeone-wizard/steps/provider/style.scss
  modules/web/src/app/node-data/style.scss
  modules/web/src/app/project-overview/style.scss
  modules/web/src/app/project/style.scss
  modules/web/src/app/project/theme.scss
  modules/web/src/app/settings/admin/defaults/style.scss
  modules/web/src/app/settings/admin/presets/dialog/steps/provider/style.scss
  modules/web/src/app/settings/user/style.scss
  modules/web/src/app/shared/components/add-external-cluster-dialog/style.scss
  modules/web/src/app/shared/components/application-list/style.scss
  modules/web/src/app/shared/components/application-list/theme.scss
  modules/web/src/app/shared/components/external-cluster-data-dialog/style.scss
  modules/web/src/app/shared/components/number-stepper/style.scss
  modules/web/src/app/shared/components/openstack-credentials/template.html
  modules/web/src/app/shared/components/openstack-credentials/theme.scss
  modules/web/src/app/shared/components/select-external-cluster-provider/style.scss
  modules/web/src/app/shared/components/tab-card/style.scss
  modules/web/src/app/shared/components/tab-card/template.html
  modules/web/src/app/shared/components/tab-card/theme.scss
  modules/web/src/app/shared/directives/value-changed-indicator.ts
  modules/web/src/app/style.scss
  modules/web/src/app/wizard/step/cluster/style.scss
  modules/web/src/app/wizard/step/provider-datacenter/style.scss
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/global/_theme.scss
  modules/web/src/assets/css/material/_main.scss
  modules/web/src/assets/css/material/_theme.scss
  modules/web/src/assets/themes/dark.scss
Labels: size/L, lgtm, release-note, approved, dco-signoff: yes, docs/none

#6687 General style enhancement
  modules/web/src/app/cluster/details/cluster/style.scss
  modules/web/src/app/cluster/details/external-cluster/style.scss
  modules/web/src/app/cluster/details/kubeone/style.scss
  modules/web/src/app/project-overview/style.scss
  modules/web/src/assets/css/global/_main.scss
  modules/web/src/assets/css/material/_main.scss
Labels: release-note-none, size/M, lgtm, approved, kind/design, dco-signoff: yes, docs/none

#6689 [release/v2.25] Bump version and add changelog for KKP patch release 2.25.4
  Makefile
  modules/api/Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/web/Makefile
  modules/web/package-lock.json
  modules/web/package.json
  modules/web/src/assets/config/changelog.json
Labels: release-note-none, size/M, lgtm, approved, kind/documentation, dco-signoff: yes, sig/api

#6690 Adjust the preset domain field to accept emails
  modules/web/src/app/settings/admin/presets/dialog/steps/preset/component.ts
  modules/web/src/app/settings/admin/presets/dialog/steps/preset/template.html
  modules/web/src/app/shared/validators/others.ts
  modules/web/src/assets/css/material/_main.scss
Labels: kind/bug, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none

#6691 fix: Added nil check to prevent exception on policy load
  modules/api/pkg/provider/cloud/vmwareclouddirector/provider.go
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes, sig/api, docs/none

#6696 Bump node version in local run scripts
  modules/web/hack/development/Dockerfile
  modules/web/hack/run-in-docker.sh
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none

#6695 Fix Azure location bug
  modules/api/pkg/handler/common/provider/azure.go
Labels: kind/bug, release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, docs/none

#6704 [release/v2.25] Update github.com/gophercloud/gophercloud to 1.11.0
  modules/api/go.mod
  modules/api/go.sum
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, sig/api, kind/regression

#6697 bump KKP to eec75550ae15
  modules/api/cmd/kubermatic-api/swagger.json
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/api/v1/types.go
  modules/api/pkg/handler/common/cluster.go
  modules/api/pkg/handler/v1/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster/cluster_test.go
  modules/api/pkg/handler/v2/cluster_default/cluster_default.go
  modules/api/pkg/handler/v2/cluster_default/cluster_default_test.go
  modules/api/pkg/handler/v2/cluster_template/cluster_template.go
  modules/api/pkg/handler/v2/cluster_template/cluster_template_test.go
  modules/api/pkg/resources/cluster/cluster.go
  modules/api/pkg/test/clusterexposer/controller/controller.go
  modules/api/pkg/test/e2e/utils/apiclient/models/cluster_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/ip_block.go
  modules/api/pkg/test/e2e/utils/apiclient/models/json_schema_props.go
  modules/api/pkg/test/e2e/utils/apiclient/models/json_schema_props_or_array.go
  modules/api/pkg/test/e2e/utils/apiclient/models/json_schema_props_or_string_array.go
  modules/api/pkg/test/e2e/utils/apiclient/models/label_selector.go
  modules/api/pkg/test/e2e/utils/apiclient/models/label_selector_requirement.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_egress_rule.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_ingress_rule.go
  modules/api/pkg/test/e2e/utils/apiclient/models/network_policy_spec.go
  modules/api/pkg/test/e2e/utils/apiclient/models/pod_dns_config.go
  modules/api/pkg/test/e2e/utils/apiclient/models/policy_rule.go
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, kind/chore, docs/none

#6706 fix dev deployment
  Makefile
Labels: release-note-none, size/XS, lgtm, approved, dco-signoff: yes, kind/chore, docs/none
