Repository kubermatic/dashboard, pull requests merged in 2025-06, with the labels that each got.

#7387 Fix UI kyverno issues
  modules/api/pkg/ee/kyverno/policy-template/handler.go
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/dynamic/enterprise/kyverno-policies/cluster-policies/template.html
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/component.ts
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/template.html
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/template.html
  modules/web/src/app/settings/admin/nav/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
  modules/web/src/app/shared/entity/kyverno.ts
  modules/web/src/app/wizard/step/cluster/template.html
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#7388 UI fixes for system applications
  modules/web/src/app/shared/components/application-list/component.ts
  modules/web/src/app/shared/components/application-list/style.scss
  modules/web/src/app/shared/components/application-list/template.html
  modules/web/src/app/shared/components/cluster-summary/template.html
Labels: kind/bug, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#7389 Fix token cookie cleaning by passing path argument to delete method
  modules/web/src/app/core/services/auth/service.ts
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#7401 Kyverno bug fixes and enhancements
  modules/api/pkg/ee/kyverno/policy-template/handler.go
  modules/web/src/app/dynamic/enterprise/kyverno-policies/cluster-policies/add-policy-dialog/component.ts
  modules/web/src/app/dynamic/enterprise/kyverno-policies/cluster-policies/component.ts
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/component.ts
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/template.html
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/component.ts
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/template.html
Labels: kind/bug, release-note-none, size/L, lgtm, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#7396 Fix: Add labels to backup objects created by a schedule.
  modules/api/pkg/ee/clusterbackup/backup/handler.go
  modules/api/pkg/ee/clusterbackup/schedule/handler.go
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#7403 Kyverno Policies UI/UX fixes
  modules/web/src/app/core/components/sidenav/template.html
  modules/web/src/app/dynamic/enterprise/kyverno-policies/cluster-policies/template.html
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/template.html
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/component.ts
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/template.html
  modules/web/src/app/settings/admin/nav/template.html
  modules/web/src/app/settings/admin/routing.ts
  modules/web/src/app/shared/components/application-list/component.ts
  modules/web/src/app/shared/components/label-form/style.scss
  modules/web/src/app/shared/components/side-nav-field/theme.scss
  modules/web/src/app/shared/entity/common.ts
Labels: release-note-none, size/L, lgtm, approved, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#7404 Rework KubeLB validation
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
Labels: kind/bug, release-note-none, size/XS, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#7410 Fix UX issues for Kyverno
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/component.ts
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/add-template/template.html
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/style.scss
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/template.html
  modules/web/src/app/shared/components/editor/component.ts
Labels: kind/bug, release-note-none, size/M, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#7411 Bump kkp go dependency for 2.28.0-rc.1
  modules/api/go.mod
  modules/api/go.sum
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#7423 Change `Experimental` to Beta label
  modules/web/src/app/dynamic/enterprise/kyverno-policies/policy-template/template.html
  modules/web/src/app/settings/admin/nav/style.scss
  modules/web/src/app/settings/admin/nav/template.html
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, docs/none, code-freeze-approved

#7424 Allow manual installation of system applications except with type `cni`
  modules/web/src/app/shared/components/application-list/add-application-dialog/component.ts
  modules/web/src/app/shared/components/application-list/component.ts
  modules/web/src/app/shared/entity/application.ts
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#7426 Fix OPA Checkbox alignment
  modules/web/src/app/wizard/step/cluster/template.html
Labels: release-note-none, lgtm, size/S, approved, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#7437 Removing TenantID filter for listing openstack networks
  modules/api/pkg/provider/cloud/openstack/provider.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#7427 Remove flakiness from ssh-keys integration tests
  modules/web/cypress.config.ts
  modules/web/cypress/e2e/v2/stories/admin-settings/defaults.spec.ts
  modules/web/cypress/e2e/v2/stories/admin-settings/dynamic-datacenters.spec.ts
  modules/web/cypress/e2e/v2/stories/ssh-keys.spec.ts
  modules/web/cypress/fixtures/cni-versions.json
  modules/web/cypress/fixtures/db.json
  modules/web/cypress/fixtures/routes.json
  modules/web/cypress/intercept/settings/admin.ts
  modules/web/cypress/pages/v2/projects/page.ts
  modules/web/cypress/pages/v2/wizard/page.ts
  modules/web/cypress/types/condition.ts
  modules/web/cypress/utils/endpoint.ts
  modules/web/cypress/utils/mocks.ts
  modules/web/fixtures/OWNERS
  modules/web/fixtures/routes.json
  modules/web/package.json
  modules/web/src/app/wizard/step/provider-datacenter/template.html
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#7443 prepare for 2.28.0-rc.1
  modules/api/go.mod
  modules/api/go.sum
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore, docs/none, code-freeze-approved

#7444 Set default backup sync period to null if value is empty
  modules/web/src/app/dynamic/enterprise/cluster-backups/list/backup-storage-location/add-dialog/component.ts
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#7453 KubeLB: Fix a bug with kubelb enforcement
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/wizard/step/cluster/component.ts
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes, docs/none

#7455 [release/v2.27] KubeLB: Fix a bug with enforcement
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/wizard/step/cluster/component.ts
Labels: kind/bug, lgtm, size/S, release-note, approved, dco-signoff: yes

#7450 [release/v2.27] Bump Go version to 1.23.10
  .prow/api.yaml
  .prow/common.yaml
  .prow/frontend.yaml
  hack/verify-spelling.sh
  modules/api/hack/gen-api-client.sh
  modules/api/hack/update-swagger.sh
  modules/api/hack/verify-licenses.sh
  modules/web/containers/chrome-headless/Dockerfile
  modules/web/containers/custom-dashboard/Dockerfile
Labels: lgtm, size/S, release-note, approved, dco-signoff: yes, sig/api, kind/chore, do-not-merge/code-freeze

#7458 Fix KubeLB checkbox state tooltip and rendering issues
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
Labels: kind/bug, size/M, lgtm, release-note, approved, dco-signoff: yes, docs/none

#7464 Improve tooltips for KubeLB
  modules/web/src/app/cluster/details/cluster/edit-cluster/component.ts
  modules/web/src/app/cluster/details/cluster/edit-cluster/template.html
  modules/web/src/app/wizard/step/cluster/component.ts
  modules/web/src/app/wizard/step/cluster/template.html
Labels: release-note-none, size/L, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#7463 [release/v2.26] Bump KKP and MC dependencies
  modules/api/go.mod
  modules/api/go.sum
Labels: release-note-none, lgtm, size/S, approved, dco-signoff: yes, sig/api, kind/chore
